### ISSUE TITLE
RAK7240 - cache directory location issue

### ISSUE THREAD

**Issue by disk91** [helium/gateway-rs#100]
The cache directory on /etc/helium_gateway/cache is a problem on RAK7240
this is blocking the filesystem remount as read-only on restart apparently due to a too small free space on it.
Then is it impossible to save any change on the gateway settings

**Comment by madninja** [comment]
What would you suggest we do instead? Keep the state channels in a different location or in memory?

Or have a configuration where no packets are ever paid for?

**Comment by shawaj** [comment]
Doesn't the rak7240 have a micro SD card? Could the cache be stored on that?

Presumably if necessary the size of that card can be upgraded.

**Comment by disk91** [comment]
I agree, there is a micro-sd and it would be the best place to store this.
I think the location is /mnt/mmcblk0p1

**Comment by madninja** [comment]
> I agree, there is a micro-sd and it would be the best place to store this.
> I think the location is /mnt/mmcblk0p1

Ok so you can set that in the settings.toml file by adding a `cache` section at the end of the file like the example below:

```
[cache]
store="/mnt/mmcblk0p1/helium_gateway/cache"
```

**Comment by jmarcelino** [comment]
I'll test it out since the filesystem which comes on the SD card is VFAT, not sure it it will work.

By the way are there any expected performance requirements for this cache? Will 10MiB/s read be enough?

**Comment by madninja** [comment]
I'm still trying to figure out what the best approach is for the state channel storage. It's worst case right now and written every time a purchase is received from router (which updates the state channel). I need to see what the memory profile is of state channels, since perhaps we can just keep them in RAM instead, or just them to disk less frequently

**Comment by madninja** [comment]
@disk91 since you're likely running against larger state channels, could you give me an idea of how big the files are that are put in that cache folder?

**Comment by madninja** [comment]
I'm going to switch the state channel to be RAM based for now since disk storage is likely going to be  problematic for other types too whereas RAM seems to be more plentiful

**Comment by madninja** [comment]
Jus shipped alpha.17 which no longer stores state channels on disk. 

You'll have to clean up your cache folder to remove all the router key subfolders since they're no longer used and just taking up space

**Comment by disk91** [comment]
I purged the cache files but the total was around 3Mb

**Comment by disk91** [comment]
I'll setup a second gateway and let you know the new impact (will do it in a couple of days).
