### ISSUE TITLE
Running gateway-rs add command without curl returns a low-information error message

### ISSUE THREAD

**Issue by mullerch** [helium/gateway-rs#118]
If curl is missing, the `add` command returns the following message:

`Error: IO(Os { code: 2, kind: NotFound, message: "No such file or directory" })`

I would expect an error message with a relation to curl, e.g. : 

`Error: IO(Os { code: 2, kind: NotFound, message: "curl: No such file or directory" })`

Also, [the README](https://github.com/helium/gateway-rs#linux-dependencies) states:

> curl: for fetching releases over SSL, curl is used. This was a simple way to use SSL without bloating the helium_gateway binary with additional libraries. Note that the updater may be disabled and thus this dependency may be removed.

But taht last sentence its not true as the add command requires it too.

**Comment by madninja** [comment]
Closing this, since Info logging was added and curl is no longer needed for chain variable access.
