### ISSUE TITLE
Improve curl requests errors handling

### ISSUE THREAD

**Issue by mullerch** [helium/gateway-rs#120]
If the remote certificate is not considered as valid when using the `add` command, the following message is displayed:
`Error: Decode(Json(Error("EOF while parsing a value", line: 1, column: 0)))`

I would have expected a message like:
`The remote certificate of https://.... is not valid`

Programatically speaking, I guess the curl return code/output is not correctly interpreted in case of an error.

**Comment by mullerch** [comment]
Yes this is the error.

No, the CA store was recently updated. The reason the certificate was not valid is detailed [here](https://blog.devgenius.io/lets-encrypt-change-affects-openssl-1-0-x-and-centos-7-49bd66016af3). But you may find this interesting as any up-to date gateway will have the same error with curl when contacting a server with a Let's Encrypt certificate.

For people coming to this issue from the same error, you can fix properly the issue by removing the expired DST Root CA X3 with:
`sudo sed -i 's|mozilla/DST_Root_CA_X3.crt|!mozilla/DST_Root_CA_X3.crt|' /etc/ca-certificates.conf`

**Comment by madninja** [comment]
curl is no longer used to get chain information since we can now ask validators for this info. So the only place curl is still used is in the update check. I propose we close this.
