### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by disk91** [helium/gateway-rs#121]
Currently the uplink are logged the following way:
```
INFO uplink @1195622011 us, 867.10 MHz, Ok(DataRate(SF7, BW125)), snr: -11.25, len: 145 from MacAddress(31:33:30:37:39:00:00), module: gateway
```
it would be great to also get the RSSI in the log for statistics of coverage area, devaddr could also be nice for device statistics. I'm not sure MaxAddress is relevant as it should be a constant in case you want to reduce some other fields

**Comment by jpmeijers** [comment]
+1

I also want to see the DevAddr, as I am curious which network's data is actually being received. The gateway only earns HNT for Helium DevAddr's. If I see a lot of logs being printed, but not earning anything, showing the DevAddr (or NetID) will help to explain why.

I also agree with @disk91 that the MacAddress of the gateway is not really useful here, and can be removed to save space.

**Comment by jpmeijers** [comment]
Looking at the code where you print the RSSI, it seems like the raw payload of the uplink packet is available.
https://github.com/helium/gateway-rs/blob/edf40564d1edf5c1df025a8d2e57901d0956d429/src/packet.rs#L59

https://github.com/helium/gateway-rs/blob/edf40564d1edf5c1df025a8d2e57901d0956d429/src/packet.rs#L50-L51

https://github.com/helium/gateway-rs/blob/edf40564d1edf5c1df025a8d2e57901d0956d429/src/packet.rs#L34

The DevAddr is not encrypted and by calculating the correct offset one can extract the DevAddr and Frame Count from it, like done here:
https://github.com/kersing/packet_forwarder/blob/e84e9a38d3c5deeaf6792b1e77449cf119cd542b/mp_pkt_fwd/src/stats.c#L197-L205
