### ISSUE TITLE
mipsel_24kc support (Onion omega2, others)

### ISSUE THREAD

**Issue by kallisti5** [helium/gateway-rs#132]
This actually runs on the onion omega2 by manually extracting the ramips_24kec.ipk and putting the files onto the filesystem manually.

This package doesn't auto install because ramips_24kec is missing as an architecture on the Onion Omega2.

Would it make sense to build for mipsel_24kc as well as ramips_24kec?  It's the same toolchain triplet, just different ipk architecture identifiers.

**Comment by madninja** [comment]
Closing per #339
