### ISSUE TITLE
OUI 2 Down?

### ISSUE THREAD

**Issue by nicklesb8787** [helium/gateway-rs#139]
I am getting gateway stream errors for the last 12 hours or so:

gateway steam error: CryptoError (Signature(signature::Error ( source: None))), module: dispatcher

**Comment by tweemeterjop** [comment]
Im also getting these errors. Running a data-only node on a Dragino LPS8.

Could it be related to the new version 0.20? The error seems to originate from [gateway-rs/src/traits/msg_sign.rs](https://github.com/helium/gateway-rs/compare/v1.0.0-alpha.19...main#diff-044460446af6b798c54a8268e54184ff63ea62c76378e7909abfcfdfb16bd724) which was added in 0.20.

**Comment by nicklesb8787** [comment]
All of my data only gateways were working 100% fine before I woke up this morning to this error and they are no longer accepting join requests from my GLAMOS either.

**Comment by nicklesb8787** [comment]
My data only gateways were on 20 yesterday and transferred data packets no problem. It seems like after they fixed the discovery issue this occurred but could be unrelated. However, there is definitely an issue.

**Comment by tweemeterjop** [comment]
I just reflashed my LPS8 to factory defaults and installed `helium-gateway-v1.0.0-alpha.19-dragino.ipk` and still getting these errors. It was running fine before so could it be a server side issue?

**Comment by nicklesb8787** [comment]
I did the same and errors still exist, that is why I posted this under issues because I believe it is server side. Waiting for dev team to answer hopefully.

**Comment by nicklesb8787** [comment]
Seems to be fixed now.... I didn't do anything either....

**Comment by tweemeterjop** [comment]
I was still on `helium-gateway-v1.0.0-alpha.19-dragino.ipk` and getting the errors. After upgrading to `helium-gateway-v1.0.0-alpha.21-dragino.ipk`, which was released 1h ago, everything seems fine..

**Comment by nicklesb8787** [comment]
interesting, I did not see version 21 but mine auto update. I just checked and sure enough, they are all 21 and working perfect lol

**Comment by madninja** [comment]
There was an announcement made in Discors about the outage and the fix in alpha.21
