### ISSUE TITLE
Errors when running alpha 21 .deb

### ISSUE THREAD

**Issue by pe1mew** [helium/gateway-rs#140]
When I try to execute alpha 21 .deb in a docker environment I get these errors:
```
 Service(Service(tonic::transport::Error(Transport, hyper::Error(Connect,ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })))))
```
This is happening with the deployment on Balena: https://github.com/mpous/helium-data-hotspot , and from Disk91: https://github.com/disk91/helium-gateway-rs-docker

**Comment by madninja** [comment]
Please include more of the log. Hard to tell what grpc service it is struggling to connect to

**Comment by pe1mew** [comment]
Yes, I agree. 

When running inside a docker container some scripting is executed to manage key- and configuration files in persistent memory. 

One executed command is: 
```
/usr/bin/helium_gateway -c /etc/helium_gateway key info
```
All required files are available and have been used with alpha19 of gateway-rs. 

When the command is executed the response is:
```
root@14932ab:/opt/nebra-gatewayrs# /usr/bin/helium_gateway -c /etc/helium_gateway key info
Error: Service(Service(tonic::transport::Error(Transport, hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })))))
```

The configuration worked with alpha19 but fails to work with alpha21.

There is not much more to tell. sorry.

**Comment by disk91** [comment]
I did the upgrade to alpha-21 and did not had the same issue.
What was your previous version you where upgrading from ?

**Comment by pe1mew** [comment]
It was a clean install when it occurs.

**Comment by shawaj** [comment]
@pe1mew are you trying to reinstall the alpha 21 deb over the alpha19 in the data only hotspot setup?

**Comment by madninja** [comment]
Ahh but the context helps a lot @pe1mew! Alpha.19 did not require the helium_gateway service to be running whereas alpha.21 does. This is due to it needing to support crypto chips while the service is running

**Comment by pe1mew** [comment]
Ok thanks for the calrification
