### ISSUE TITLE
 CryptoError(Signature(signature::Error { source: None }))

### ISSUE THREAD

**Issue by disk91** [helium/gateway-rs#141]
Gateway-rs stop transfering packets with the following error for each of the packets
( this was seen on alpha-19) it has disappeared after an upgrade to alpha-21, don't know if related to upgrade or restart.

```
Nov 07 18:20:39.715 INFO using gateway, uri: http://54.251.77.229:8080/, pubkey: 11Gx2yPEmBGUrbHUiUWQs9vV7JDHQLZSddQs6e3WB2uvqSMUDBW, module: dispatcher
Nov 07 18:20:40.474 WARN gateway stream error: CryptoError(Signature(signature::Error { source: None })), module: dispatcher
Nov 07 18:20:45.476 INFO using gateway, uri: http://3.132.190.192:8080/, pubkey: 115PmCR6fpFihdjw626JXYdUEdzwjh66yoWzWkMvB9CRGEx1U6G, module: dispatcher
Nov 07 18:20:45.956 WARN gateway stream error: CryptoError(Signature(signature::Error { source: None })), module: dispatcher
Nov 07 18:20:49.499 INFO uplink @3969801540 us, 868.10 MHz, Ok(DataRate(SF12, BW125)), snr: -14.5, len: 23 from MacAddress(AC:1F:09:FF:FE:05:89), module: gateway
Nov 07 18:20:50.957 INFO using gateway, uri: http://52.49.199.40:8080/, pubkey: 11tk4zzbyfMPYYHYda255ACoqfYFVdrUSoCWrCYfn8BoyuYrERK, module: dispatcher
Nov 07 18:20:51.123 WARN gateway stream error: CryptoError(Signature(signature::Error { source: None })), module: dispatcher
```

**Comment by pe1mew** [comment]
Hi, My experience is that after the upgrade to 21 and then restart it disappears. 
In my situation it was observed and cured on as RAK gateway type 7258 that uses helium-gateway-v1.0.0-alpha.21-ramips_24kec.ipk

**Comment by shawaj** [comment]
IIRC the gateways were updated to require signing of the packets so alpha19 would have no longer been compatible. But maybe I'm misremembering 🤔

**Comment by madninja** [comment]
Additional data was added to the signature that the validator (not router) applies over RPC results. Alpha.19 did not know about these new fields. Alpha.21 does know

**Comment by yaser7us** [comment]
I have the same problem now. Data-only hotspots I have are not able to conenct to the gateway and forward data.

**Comment by madninja** [comment]
> I have the same problem now. Data-only hotspots I have are not able to conenct to the gateway and forward data.

You have crypto errors in the log?

**Comment by yaser7us** [comment]
Yes,
gateway region stream error: CryptoError(Signature(signature::Error { source: None })), module: dispatcher

**Comment by madninja** [comment]
> Yes,
> gateway region stream error: CryptoError(Signature(signature::Error { source: None })), module: dispatcher

while the the error isn't the same as this issue. Would you be able to create a new issue please so we can keep track?

**Comment by madninja** [comment]
Looks like this was already filed recently as #246
