### ISSUE TITLE
Dragino LPS8 helium_gateway add --mode light fails with {invalid,wrong_staking_fee} 

### ISSUE THREAD

**Issue by alorbach** [helium/gateway-rs#142]
I am trying to add a Dragino LPS8 hotspot to the Helium network. 
I have installed latest helium_gateway release (Release v1.0.0-alpha.21) and added the gateway in light mode: 
`helium_gateway add --mode light --owner 13vK6Cd7... --payer 13vK6Cd7...`

Then I have loaded about 2 HNT to my helium wallet (Created with the helium-wallet CLI util), and converted them into DC already (Because I thought this would solve the problem). helium-wallet info shows this: 

> +--------------------+-----------------------------------------------------+
> | Key                | Value                                               |
> +--------------------+-----------------------------------------------------+
> | Address            | 13vK6Cd7... |
> +--------------------+-----------------------------------------------------+
> | Network            | mainnet                                             |
> +--------------------+-----------------------------------------------------+
> | Type               | ed25519                                             |
> +--------------------+-----------------------------------------------------+
> | Sharded            | false                                               |
> +--------------------+-----------------------------------------------------+
> | PwHash             | Argon2id13                                          |
> +--------------------+-----------------------------------------------------+
> | Balance            | 0.03929774                                          |
> +--------------------+-----------------------------------------------------+
> | DC Balance         | 5648423                                             |
> +--------------------+-----------------------------------------------------+
> | Securities Balance | 0.00000000                                          |
> +--------------------+-----------------------------------------------------+

So I tried to add the helium hotspot to my wallet using:
`helium-wallet hotspots add --commit CrQBCiEBgH...CS9AFA6PsD`

I have tried many times now, but it always fails with: 
> "failed_reason": "{invalid,wrong_staking_fee}"

What am I doing wrong?

**Comment by madninja** [comment]
You can only add a non hip19 approved gateway as a `dataonly` gateway. Please use that as the mode option.

**Comment by madninja** [comment]
> Thanks I have done so, and it worked. Does this device has a chance to become a Light Hotspot anytime soon?

As the docs indicate, a dataonly hotspot can not "become a light hotspot". The hardware needs to be hip19 approved

**Comment by alorbach** [comment]
I understand, thanks.

**Comment by alorbach** [comment]
Sorry to bother again, I have setup everything according to your help articles successfully: 
https://docs.helium.com/mine-hnt/data-only-hotspots/#add-hotspot

My hotspot is appearing on the map, how do I verify it is working properly and is being used in the network?

**Comment by madninja** [comment]
Your hotspot is a dataonly hotspot. Use an end device, register it on console, send some data... see it in console

**Comment by LynnL4** [comment]
> Your hotspot is a dataonly hotspot. Use an end device, register it on console, send some data... see it in console

Hi， I could see package forward log in console， but I cloud't earn any HNT. What can I do now?
