### ISSUE TITLE
Missing log file

### ISSUE THREAD

**Issue by ZEROF** [helium/gateway-rs#143]
Hello,

I'm using Dragino LPS8 to run gateway-rs and I detected one error in the logs. You package is not creating /var/provision.log file. I created this file manually with **touch /var/provision.log** and this resolved this "issue".

**Comment by madninja** [comment]
Sorry, what is  var/provision.log required for?

**Comment by ZEROF** [comment]
This is where gateway-rs write related packet forwarding activity logs, example:

https://paste.lugons.org/?4ac1e72fb76ebe3f#4nk8iwuzNYEAixbBN9GMjJJvvXwDwKPGfTQsMd8kdPst

**Comment by madninja** [comment]
This the packet forwarder log which is not controlled at all by gateway-rs.

**Comment by ZEROF** [comment]
Ok, in that case why error is saying gateway-rs can't write to /var/provision.log? I think that gateway-rs should create this file when installed on this device. When I disable gateway-rs error don't come back. I know it's related to opewrt used by Dragino, but this specific log is used only if gateway-rs is installed.

**Comment by madninja** [comment]
Could you show me that actual error from helium_gateway? I don’t quite see it

**Comment by ZEROF** [comment]
Hi,

Sorry for late update. I removed file, rebooted Dragino and provision.log file was created successfully. Guess it was some system "glitch" impacting creation of this file before.

**Comment by madninja** [comment]
Ah ok, thanks for the heads up. Not related to this service then. Closing
