### ISSUE TITLE
MacAddress(...) in gateway module logs only shows 7 bytes

### ISSUE THREAD

**Issue by gregtoth** [helium/gateway-rs#146]
The MacAddress(...) log lines from gateway module only show 7 bytes of the gateway eui. Should it be showing all 8 bytes? Example: For gateway eui 11:22:33:44:55:66:77:88 the log line shows MacAddress(11:22:33:44:55:66:88). Have noticed same thing in several logs people have posted in other issues.

**Comment by lthiery** [comment]
Thanks for catching this. I'll be fixing this in the semtech-udp library

https://github.com/helium/semtech-udp/pull/38
