### ISSUE TITLE
DevEUI in Logs is byte wise backwards?

### ISSUE THREAD

**Issue by jkowalcz** [helium/gateway-rs#151]
while looking at loks of log output I noticed the the DevEUI is Bytewise backwards..  (alpha21, dragino LPS8 Dataonly hotspot)
Log output

```PKT_FWD~ JOIN_REQ+ {"AppEUI":,"AF02000000000080", "DevEUI":,"57398D1334B50D00"``` 

and the DevEui is actually 000DB534138D3957 on the device and QR code?

**Comment by IoTThinks** [comment]
Yes, I saw the same too.

**Comment by madninja** [comment]
uhh.. that's not output from gateway-rs is it? But output from the packet forwarder? I don't know how they display things in the logs, but if you see traffic in console you're good.
