### ISSUE TITLE
can't add gateway to blockchain

### ISSUE THREAD

**Issue by chengjianwen** [helium/gateway-rs#152]
version: 1.0.0-alpha.21
platform: raspi234
region: CN470

and I wish to add it to helium blockchain, but failed.

I create an account use helium-wallet-v1.6.8 on another macOS machine.

my command:

helium_gateway add --owner 148xvk6ZnEgM9nLp3LAZAhenwbAqA4niXsE39YrScwyRCzWrZyN --payer 148xvk6ZnEgM9nLp3LAZAhenwbAqA4niXsE39YrScwyRCzWrZyN

but it returned with:

Service(Rpc(Status { code: Internal, message: "Failed to get config", metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Wed, 17 Nov 2021 12:17:08 GMT"} }, source: None }))

I don't known what happened. 
sudo grep helium_gateway /var/log/syslog

Nov 17 12:06:44 rak-gateway helium_gateway[490]: starting server, key: 13tJmwbWoYqYtxUMm2XQftZVKBd9rWUyebvwEAhhjBm24Tdu1UN, version: 1.0.0-alpha.21
Nov 17 12:06:44 rak-gateway helium_gateway[490]: starting, module: gateway
Nov 17 12:06:44 rak-gateway helium_gateway[490]: starting, module: dispatcher
Nov 17 12:06:44 rak-gateway helium_gateway[490]: default router, module: dispatcher, uri: http://54.176.88.149:8080/, pubkey: 1124CJ9yJaHq4D6ugyPCDnSBzQik61C1BqD9VMh1vsUmjwt16HNB
Nov 17 12:06:44 rak-gateway helium_gateway[490]: using gateway, module: dispatcher, uri: http://3.38.70.101:8080/, pubkey: 11yJXQPG9deHqvw2ac6VWtNP7gZj8X3t3Qb3Gqm9j729p4AsdaA
Nov 17 12:06:44 rak-gateway helium_gateway[490]: starting, module: updater
Nov 17 12:06:44 rak-gateway helium_gateway[490]: starting, listen: 127.0.0.1:4467, module: api
Nov 17 12:06:44 rak-gateway helium_gateway[490]: gateway error: Service(Rpc(Status { code: Unavailable, message: "error trying to connect: tcp connect error: Network is unreachable (os error 101)", source: Some(tonic::transport::Error(Transport, hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 101, kind: NetworkUnreachable, message: "Network is unreachable" })))) })), module: dispatcher
Nov 17 12:06:45 rak-gateway helium_gateway[490]: no update found, module: updater
Nov 17 12:06:49 rak-gateway helium_gateway[490]: using gateway, module: dispatcher, uri: http://54.251.77.229:8080/, pubkey: 11Gx2yPEmBGUrbHUiUWQs9vV7JDHQLZSddQs6e3WB2uvqSMUDBW
Nov 17 12:06:49 rak-gateway helium_gateway[490]: gateway error: Service(Rpc(Status { code: Unavailable, message: "error trying to connect: tcp connect error: Network is unreachable (os error 101)", source: Some(tonic::transport::Error(Transport, hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 101, kind: NetworkUnreachable, message: "Network is unreachable" })))) })), module: dispatcher
Nov 17 12:09:22 rak-gateway helium_gateway[490]: using gateway, module: dispatcher, uri: http://35.84.173.125:8080/, pubkey: 11pUovhssQdXzrfcYMTUrNNTQossgny8WqhfdbprrAVFyHcmvAN
Nov 17 12:09:24 rak-gateway helium_gateway[490]: starting, oui: 16, uri: http://217.164.136.49:8080/, pubkey: 11afuQSrmk52mgxLu91AdtDXbJ9wmqWBUxC3hvjejoXkxEZfPvY, module: router
Nov 17 12:09:24 rak-gateway helium_gateway[490]: starting, oui: 15, uri: http://66.23.231.34:8080/, pubkey: 117FMcZy77Ehz6gbTtSdSEs38vF784NLkxmWXUPcA2Ze3QxwJhG, module: router
Nov 17 12:09:24 rak-gateway helium_gateway[490]: starting, oui: 13, uri: http://46.246.38.248:8080/, pubkey: 115ZS5of9wsV3M5sH3mePp9NVnKayUXG7qT2W7Sn4KJLMzd3eMr, module: router
Nov 17 12:09:24 rak-gateway helium_gateway[490]: starting, oui: 12, uri: http://54.219.236.122:8080/, pubkey: 112ewJNEUfSg3Jvo276tMjzFC2JzmmZcJJ32CWz2fzYqbyCMMTe1, module: router
Nov 17 12:09:25 rak-gateway helium_gateway[490]: starting, oui: 10, uri: http://54.228.141.195:8080/, pubkey: 11YmZtwTPEuMSFGxze1x9TfDfGezN7vXevLu71iJe9FBbvNRAgk, module: router
Nov 17 12:09:25 rak-gateway helium_gateway[490]: starting, oui: 9, uri: http://44.238.156.97:8080/, pubkey: 11w77YQLhgUt8HUJrMtntGGr97RyXmot1ofs5Ct2ELTmbFoYsQa, module: router
Nov 17 12:09:25 rak-gateway helium_gateway[490]: starting, oui: 4, uri: http://54.193.165.228:8080/, pubkey: 11263KvqW3GZPAvag5sQYtBJSjb25azSTSwoi5Tza9kboaLRxcsv, module: router
Nov 17 12:09:25 rak-gateway helium_gateway[490]: starting, oui: 2, uri: http://54.176.88.149:8080/, pubkey: 1124CJ9yJaHq4D6ugyPCDnSBzQik61C1BqD9VMh1vsUmjwt16HNB, module: router
Nov 17 12:09:26 rak-gateway helium_gateway[490]: updated routing to height 1100572, module: dispatcher
Nov 17 12:09:26 rak-gateway helium_gateway[490]: starting, oui: 1, uri: http://52.8.80.146:8080/, pubkey: 112qB3YaH5bZkCnKA5uRH7tBtGNv2Y5B4smv1jsmvGUzgKT71QpE, module: router
Nov 17 12:19:25 rak-gateway helium_gateway[490]: no update found, module: updater

**Comment by madninja** [comment]
Please see status.helium.com and the announcements channel on Discord. The chain went through a complete halt. The validators for the light gateways have not recovered yet. I'm going to close this as a known issue. Pleas try again in a day or so
