### ISSUE TITLE
Stable toolchain compatible build by default

### ISSUE THREAD

**Issue by mullerch** [helium/gateway-rs#156]
Actually, gateway-rs needs a nightly version of cargo/rust to build, as it requires `strip` ~and `edition2021`~ features.

As this is acceptable for an alpha development build, it's not for a production version.

We should be able to build gateway-rs with the stable toolchain.

Edit : my bad, it looks like edition2021 is now release in stable 1.56. `strip` is planned for 1.58 who just landed in the beta channel.

**Comment by madninja** [comment]
Edition 2021 is part of the stable tool chain. So we’re really only using the strip functionality out of nightly. 

If you have an alternate proposal for how to strip the resulting binary that works with the cross build system please suggest it?

**Comment by mullerch** [comment]
I don't know cargo well enough to suggest an alternative. My binaries get stripped through the Yocto build process.

Anyway, I would put a stable build as a higher priority than stripped binaries.

**Comment by mullerch** [comment]
More generally, the strip feature issue will resolve by itself in a few weeks but it would be good to have a stable toolchain based build for the non alpha/beta release and ensure there is no regression about that.

**Comment by madninja** [comment]
> More generally, the strip feature issue will resolve by itself in a few weeks but it would be good to have a stable toolchain based build for the non alpha/beta release and ensure there is no regression about that.

yeah for sure.. 

> Anyway, I would put a stable build as a higher priority than stripped binaries.

Not if you are not able to load the resulting binaries on targets.. they're literally 2 or 3x the binary size

Either way this'll be in stable before this repo goes to production

**Comment by mullerch** [comment]
> Not if you are not able to load the resulting binaries on targets.. they're literally 2 or 3x the binary size

For production on a networking equipment, stability is my number one requirement. If it's not stable, I will not try to deploy it at all. I couldn't find any information regarding nightly and beta channels stability, so I'll probably stick to the stable channel.

I totally understand that a prototyping build would prioritize easy deployment over stability.

> Either way this'll be in stable before this repo goes to production

Thanks :+1:
