### ISSUE TITLE
RSSI 27 for Join Accept?

### ISSUE THREAD

**Issue by IoTThinks** [helium/gateway-rs#164]
Just curious why the RSSI=27 for Join-Accept?
The RSSI for Join-Request and Uplink is OK.

By right, the value should be similar to the value of Join-Request and uplink packets?
This is helium_gateway 1.0.0-alpha.21 on Dragino LPS8 (Data hotspot).

Thanks a lot.

![image](https://user-images.githubusercontent.com/29994971/147346471-17ab00c7-a58b-4a2e-ba48-48c306e130fa.png)

**Comment by madninja** [comment]
This is not really related to this repo. The helium_gateway just reports what it gets from your packet forwarder.
