### ISSUE TITLE
wrong add fee 

### ISSUE THREAD

**Issue by Colin-at-511100471793** [helium/gateway-rs#165]
Hi, I tried adding my dragino lps8 as a light hotspot last week, right now it's a dataonly..  when I generate the add gateway hash, it lists the cost as 40$, which is the "full" hotspot amount... even thought it states that mode=light..  so I wasn't thrilled about that but I added enough to my wallet and tried it out anyways.. only to get the "wrong fee amount" error on the add transaction.. 

hmm.. I know light hotspots are somewhat new.. is this supported yet?  I'm on version alpha--21 of the gateway, I'm not sure what my wallet version is, but I think this is a gateway thing since it generates the hash ?? I dunno...

**Comment by madninja** [comment]
unless specified otherwise the CLI will assume you have a full miner, which you don't. Light hotspots are not supported by the chain yet, so you need to add this lps8 as a `--mode=dataonly`

**Comment by IoTThinks** [comment]
@madninja Will this gateway support light hotspot in the plan?

Thanks a lot.

**Comment by madninja** [comment]
> @madninja Will this gateway support light hotspot in the plan?
> 
> Thanks a lot.

no.. you can't convert a non hip19 approved hotspot into a hip19 one.

**Comment by IoTThinks** [comment]
Ok let me find those with hip19 to support light gateway. Any hint on the list?

It seems that most of the Helium gateways are now full hotspot.

Thanks million.

**Comment by Colin-at-511100471793** [comment]
as an fyi, dragino applied for a light hotspot 'license' for another product that will have a more powerful cpu and more ram..

https://github.com/dewi-alliance/hotspot-manufacturers/blob/main/applications/dragino-light-hotspot.md

 maybe I'll make a full diy hotspot out of an old laptop.. maybe I won't bother ;)

**Comment by IoTThinks** [comment]
@Colin-at-511100471793 Still in early state for these Dragino hotspot.

Will wait a while for them.
Thanks a lot.

**Comment by IoTThinks** [comment]
@Colin-at-511100471793 I dont think we can DIY the light hotspot. The gateway must be HIP19 approved.
