### ISSUE TITLE
install helium miner or node as such in OpenWrt 19.07.7 r11306-c4a6851c72 / LuCI openwrt-19.07 branch git-21.189.23240-7b931da

### ISSUE THREAD

**Issue by xtpeloco** [helium/gateway-rs#169]
good

I have a node installation with openwrt and I would need guidance to create a node, as updated as possible, light gateway if it can be, what packages or guide do I have to follow?

Hostname OpenWRT
Model Ubiquiti RouterStation Pro
Architecture Atheros AR7161 rev 2
Firmware Version OpenWrt 19.07.7 r11306-c4a6851c72 / LuCI openwrt-19.07 branch git-21.189.23240-7b931da
Kernel Version 4.14.221
Local Time 2022-01-07 09:47:04

**Comment by madninja** [comment]
While your architecture is different you can follow the same steps as for some of the other "from scratch" platforms in guides given here: https://docs.helium.com/mine-hnt/data-only-hotspots#data-only-hotspot-setup-guides

Specifically, look at the raspi guides
