### ISSUE TITLE
Cannot register Wallet ID

### ISSUE THREAD

**Issue by Kame160** [helium/gateway-rs#171]
Hello,
I would like to configure a RAK7258 in data-only. 
I installed the  helium-gateway-v1.0.0-alpha.21-ramips_24kec.ipk release and configure it until the "wallet" step

[root@RAK7258:~#] helium_gateway add –owner <WALLET_ID> –payer <WALLET_ID>
Im am getting: “Error: Config(stream did not contain valid UTF-8)” and therefor cannot register my wallet in the hotspot.
Tried with diffferents <WALLET_ID>. Those are correct as if I change any character I am getting another decode error (e.g. with 14XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX3o).
Any clue ?
Thank you in advance,
Kame

**Comment by madninja** [comment]
Do you have the helium_gateway service running, before calling that command?

**Comment by Kame160** [comment]
Hello,
Yes I checked it and restarted multiple times - no joy.
Finally I reseted the hotspot, flashed the firmware with the last version and it worked like a charm without reason.
Thanks for answering so quickly though,
Regards,
Kame
