### ISSUE TITLE
gateway re-assert location not working

### ISSUE THREAD

**Issue by marrik96** [helium/gateway-rs#172]
I know this could be an issue with the helium-wallet but wanted to start here just in case it's related to gateway.

I registered and asserted a Dragino LPS8 data-only hotspot several months ago.  I know want to replace with FreedomFi gateway and move this Dragino.  I'm trying the command below with no luck.

.\helium-wallet.exe hotspots assert --gateway DRAGINO-TXN --lat=29.7424588 --lon=-95.3530247 --mode dataonly

I get the following error.

Password: [hidden]
error: request error

Caused by:
    HTTP status client error (429 Too Many Requests) for url (https://api.helium.io/v1/vars)

If this is a wallet issue, I will move question there.  Thanks.

**Comment by madninja** [comment]
This is a wallet issue. The most common source of the 429 error is an outdated helium_wallet executable. Or you are asserting many hotspots?

**Comment by marrik96** [comment]
> This is a wallet issue. The most common source of the 429 error is an outdated helium_wallet executable. Or you are asserting many hotspots?

I will be sure to update wallet exe and try again.  If not, will move question to wallet.  Thanks!

**Comment by marrik96** [comment]
It was the wallet version.  Thank you.
