### ISSUE TITLE
Device cannot join via My GW

### ISSUE THREAD

**Issue by copy123GitHub** [helium/gateway-rs#177]
**Hi,**
**I have used chirpstack in lorawan and am beginner to helium.** 
**I believe the GW works as data-only mode.**

**I tried to use my device in helium lorawan, i installed "helium-gateway-v1.0.0-alpha.21-raspi234.deb" to my raspberry pi.**
**configured as below:**

>>
root@heliumGW:/etc/helium_gateway# cat settings.toml
region = "KR920"

[log]
method = "syslog"
level = "debug"
timestamp = false

[update]
platform = "raspi234"

**I did restart helium gateway and get log**

>>>>>>
root@heliumGW:/etc/helium_gateway# systemctl restart helium_gateway

Jan 22 19:46:23 heliumGW systemd[1]: helium_gateway.service: Main process exited, code=killed, status=15/TERM
Jan 22 19:46:23 heliumGW systemd[1]: helium_gateway.service: Succeeded.
Jan 22 19:46:23 heliumGW helium_gateway[1010]: starting server, key: 14EsFDEEGYzYfwCH4izFNgvyFZowRsdF9BfQseyCuMRn73xDVZj, version: 1.0.0-alpha.21
Jan 22 19:46:23 heliumGW helium_gateway[1010]: starting, module: gateway
Jan 22 19:46:23 heliumGW helium_gateway[1010]: starting, module: dispatcher
Jan 22 19:46:23 heliumGW helium_gateway[1010]: default router, module: dispatcher, uri: http://54.176.88.149:8080/, pubkey: 1124CJ9yJaHq4D6ugyPCDnSBzQik61C1BqD9VMh1vsUmjwt16HNB
Jan 22 19:46:23 heliumGW helium_gateway[1010]: using gateway, module: dispatcher, uri: http://52.49.199.40:8080/, pubkey: 11tk4zzbyfMPYYHYda255ACoqfYFVdrUSoCWrCYfn8BoyuYrERK
Jan 22 19:46:23 heliumGW helium_gateway[1010]: starting, module: updater
Jan 22 19:46:23 heliumGW helium_gateway[1010]: starting, listen: 127.0.0.1:4467, module: api
Jan 22 19:46:23 heliumGW helium_gateway[1010]: connecting to 52.49.199.40:8080
Jan 22 19:46:23 heliumGW helium_gateway[1010]: connected to 52.49.199.40:8080
Jan 22 19:46:23 heliumGW helium_gateway[1010]: binding client connection
Jan 22 19:46:23 heliumGW helium_gateway[1010]: client connection bound
Jan 22 19:46:23 heliumGW helium_gateway[1010]: send frame=Settings { flags: (0x0), enable_push: 0, initial_window_size: 2097152, max_frame_size: 16384 }
Jan 22 19:46:23 heliumGW helium_gateway[1010]: Connection; peer=Client
Jan 22 19:46:23 heliumGW helium_gateway[1010]: send frame=WindowUpdate { stream_id: StreamId(0), size_increment: 5177345 }
Jan 22 19:46:23 heliumGW helium_gateway[1010]: service.ready=true processing request
Jan 22 19:46:23 heliumGW helium_gateway[1010]: send frame=Headers { stream_id: StreamId(1), flags: (0x4: END_HEADERS) }
Jan 22 19:46:23 heliumGW helium_gateway[1010]: send frame=Data { stream_id: StreamId(1) }
Jan 22 19:46:23 heliumGW helium_gateway[1010]: send frame=Data { stream_id: StreamId(1), flags: (0x1: END_STREAM) }
Jan 22 19:46:23 heliumGW helium_gateway[1010]: received frame=Settings { flags: (0x0) }
Jan 22 19:46:23 heliumGW helium_gateway[1010]: send frame=Settings { flags: (0x1: ACK) }
Jan 22 19:46:23 heliumGW helium_gateway[1010]: received frame=Settings { flags: (0x1: ACK) }
Jan 22 19:46:23 heliumGW helium_gateway[1010]: received settings ACK; applying Settings { flags: (0x0), enable_push: 0, initial_window_size: 2097152, max_frame_size: 16384 }
Jan 22 19:46:23 heliumGW helium_gateway[1010]: received frame=WindowUpdate { stream_id: StreamId(1), size_increment: 5 }
Jan 22 19:46:23 heliumGW helium_gateway[1010]: received frame=WindowUpdate { stream_id: StreamId(0), size_increment: 5 }
Jan 22 19:46:23 heliumGW helium_gateway[1010]: received frame=Headers { stream_id: StreamId(1), flags: (0x4: END_HEADERS) }
Jan 22 19:46:23 heliumGW helium_gateway[1010]: received frame=Data { stream_id: StreamId(1) }
Jan 22 19:46:24 heliumGW helium_gateway[1010]: received frame=Data { stream_id: StreamId(1) }
Jan 22 19:46:24 heliumGW helium_gateway[1010]: received frame=Data { stream_id: StreamId(1) }
Jan 22 19:46:24 heliumGW helium_gateway[1010]: received frame=Data { stream_id: StreamId(1) }
Jan 22 19:46:24 heliumGW helium_gateway[1010]: received frame=Data { stream_id: StreamId(1) }
Jan 22 19:46:24 heliumGW helium_gateway[1010]: received frame=Data { stream_id: StreamId(1) }
Jan 22 19:46:24 heliumGW helium_gateway[1010]: received frame=Data { stream_id: StreamId(1) }
Jan 22 19:46:24 heliumGW helium_gateway[1010]: service.ready=true processing request
Jan 22 19:46:24 heliumGW helium_gateway[1010]: send frame=Headers { stream_id: StreamId(3), flags: (0x4: END_HEADERS) }
Jan 22 19:46:24 heliumGW helium_gateway[1010]: received frame=Headers { stream_id: StreamId(3), flags: (0x4: END_HEADERS) }
Jan 22 19:46:24 heliumGW helium_gateway[1010]: starting, oui: 16, uri: http://13.37.13.24:8080/, pubkey: 11afuQSrmk52mgxLu91AdtDXbJ9wmqWBUxC3hvjejoXkxEZfPvY, module: router
Jan 22 19:46:24 heliumGW helium_gateway[1010]: service.ready=true processing request
Jan 22 19:46:24 heliumGW helium_gateway[1010]: send frame=Headers { stream_id: StreamId(5), flags: (0x4: END_HEADERS) }
Jan 22 19:46:24 heliumGW helium_gateway[1010]: received frame=Headers { stream_id: StreamId(5), flags: (0x4: END_HEADERS) }
Jan 22 19:46:24 heliumGW helium_gateway[1010]: starting, oui: 13, uri: http://46.246.38.248:8080/, pubkey: 115ZS5of9wsV3M5sH3mePp9NVnKayUXG7qT2W7Sn4KJLMzd3eMr, module: router
Jan 22 19:46:24 heliumGW helium_gateway[1010]: service.ready=true processing request
Jan 22 19:46:24 heliumGW helium_gateway[1010]: send frame=Headers { stream_id: StreamId(7), flags: (0x4: END_HEADERS) }
Jan 22 19:46:25 heliumGW helium_gateway[1010]: received frame=Headers { stream_id: StreamId(7), flags: (0x4: END_HEADERS) }
Jan 22 19:46:25 heliumGW helium_gateway[1010]: starting, oui: 12, uri: http://54.219.236.122:8080/, pubkey: 112ewJNEUfSg3Jvo276tMjzFC2JzmmZcJJ32CWz2fzYqbyCMMTe1, module: router
Jan 22 19:46:25 heliumGW helium_gateway[1010]: service.ready=true processing request
Jan 22 19:46:25 heliumGW helium_gateway[1010]: send frame=Headers { stream_id: StreamId(9), flags: (0x4: END_HEADERS) }
Jan 22 19:46:25 heliumGW helium_gateway[1010]: received frame=Headers { stream_id: StreamId(9), flags: (0x4: END_HEADERS) }
Jan 22 19:46:25 heliumGW helium_gateway[1010]: starting, oui: 9, uri: http://44.238.156.97:8080/, pubkey: 11w77YQLhgUt8HUJrMtntGGr97RyXmot1ofs5Ct2ELTmbFoYsQa, module: router
Jan 22 19:46:25 heliumGW helium_gateway[1010]: service.ready=true processing request
Jan 22 19:46:25 heliumGW helium_gateway[1010]: send frame=Headers { stream_id: StreamId(11), flags: (0x4: END_HEADERS) }
Jan 22 19:46:25 heliumGW helium_gateway[1010]: received frame=Headers { stream_id: StreamId(11), flags: (0x4: END_HEADERS) }
Jan 22 19:46:25 heliumGW helium_gateway[1010]: starting, oui: 4, uri: http://54.193.165.228:8080/, pubkey: 11263KvqW3GZPAvag5sQYtBJSjb25azSTSwoi5Tza9kboaLRxcsv, module: router
Jan 22 19:46:25 heliumGW helium_gateway[1010]: service.ready=true processing request
Jan 22 19:46:25 heliumGW helium_gateway[1010]: send frame=Headers { stream_id: StreamId(13), flags: (0x4: END_HEADERS) }
Jan 22 19:46:25 heliumGW helium_gateway[1010]: received frame=Headers { stream_id: StreamId(13), flags: (0x4: END_HEADERS) }
Jan 22 19:46:25 heliumGW helium_gateway[1010]: starting, oui: 2, uri: http://54.176.88.149:8080/, pubkey: 1124CJ9yJaHq4D6ugyPCDnSBzQik61C1BqD9VMh1vsUmjwt16HNB, module: router
Jan 22 19:46:25 heliumGW helium_gateway[1010]: service.ready=true processing request
Jan 22 19:46:25 heliumGW helium_gateway[1010]: send frame=Headers { stream_id: StreamId(15), flags: (0x4: END_HEADERS) }
Jan 22 19:46:26 heliumGW helium_gateway[1010]: received frame=Headers { stream_id: StreamId(15), flags: (0x4: END_HEADERS) }
Jan 22 19:46:26 heliumGW helium_gateway[1010]: updated routing to height 1193008, module: dispatcher
Jan 22 19:46:26 heliumGW helium_gateway[1010]: starting, oui: 1, uri: http://52.8.80.146:8080/, pubkey: 112qB3YaH5bZkCnKA5uRH7tBtGNv2Y5B4smv1jsmvGUzgKT71QpE, module: router
Jan 22 19:46:26 heliumGW helium_gateway[1010]: no update found, module: updater
Jan 22 19:46:26 heliumGW helium_gateway[1010]: new packet forwarder client: MacAddress(B8:27:EB:FF:FE:26:6F), 127.0.0.1:38733, module: gateway

**and restart my Device to get the log of helium-gateway at join request  as below:**

>>>>>>
Jan 22 19:49:40 heliumGW helium_gateway[1010]: uplink @3686964924 us, 922.30 MHz, Ok(DataRate(SF12, BW125)), snr: 9.2, rssi: -59, len: 23 from MacAddress(B8:27:EB:FF:FE:26:6F), module: gateway
Jan 22 19:49:40 heliumGW helium_gateway[1010]: connecting to 54.193.165.228:8080
Jan 22 19:49:40 heliumGW helium_gateway[1010]: connecting to 52.8.80.146:8080
Jan 22 19:49:40 heliumGW helium_gateway[1010]: connected to 54.193.165.228:8080
Jan 22 19:49:40 heliumGW helium_gateway[1010]: binding client connection
Jan 22 19:49:40 heliumGW helium_gateway[1010]: client connection bound
Jan 22 19:49:40 heliumGW helium_gateway[1010]: send frame=Settings { flags: (0x0), enable_push: 0, initial_window_size: 2097152, max_frame_size: 16384 }
Jan 22 19:49:40 heliumGW helium_gateway[1010]: Connection; peer=Client
Jan 22 19:49:40 heliumGW helium_gateway[1010]: send frame=WindowUpdate { stream_id: StreamId(0), size_increment: 5177345 }
Jan 22 19:49:40 heliumGW helium_gateway[1010]: service.ready=true processing request
Jan 22 19:49:40 heliumGW helium_gateway[1010]: send frame=Headers { stream_id: StreamId(1), flags: (0x4: END_HEADERS) }
Jan 22 19:49:40 heliumGW helium_gateway[1010]: connected to 52.8.80.146:8080
Jan 22 19:49:40 heliumGW helium_gateway[1010]: binding client connection
Jan 22 19:49:40 heliumGW helium_gateway[1010]: client connection bound
Jan 22 19:49:40 heliumGW helium_gateway[1010]: send frame=Settings { flags: (0x0), enable_push: 0, initial_window_size: 2097152, max_frame_size: 16384 }
Jan 22 19:49:40 heliumGW helium_gateway[1010]: Connection; peer=Client
Jan 22 19:49:40 heliumGW helium_gateway[1010]: send frame=WindowUpdate { stream_id: StreamId(0), size_increment: 5177345 }
Jan 22 19:49:40 heliumGW helium_gateway[1010]: service.ready=true processing request
Jan 22 19:49:40 heliumGW helium_gateway[1010]: send frame=Headers { stream_id: StreamId(1), flags: (0x4: END_HEADERS) }
Jan 22 19:49:40 heliumGW helium_gateway[1010]: received frame=Settings { flags: (0x0) }
Jan 22 19:49:40 heliumGW helium_gateway[1010]: send frame=Settings { flags: (0x1: ACK) }
Jan 22 19:49:40 heliumGW helium_gateway[1010]: received frame=Settings { flags: (0x0) }
Jan 22 19:49:40 heliumGW helium_gateway[1010]: send frame=Settings { flags: (0x1: ACK) }
Jan 22 19:49:40 heliumGW helium_gateway[1010]: received frame=Settings { flags: (0x1: ACK) }
Jan 22 19:49:40 heliumGW helium_gateway[1010]: received settings ACK; applying Settings { flags: (0x0), enable_push: 0, initial_window_size: 2097152, max_frame_size: 16384 }
Jan 22 19:49:40 heliumGW helium_gateway[1010]: received frame=Headers { stream_id: StreamId(1), flags: (0x4: END_HEADERS) }
Jan 22 19:49:40 heliumGW helium_gateway[1010]: received frame=Data { stream_id: StreamId(1) }
Jan 22 19:49:40 heliumGW helium_gateway[1010]: connected state channel, oui: 4, uri: http://54.193.165.228:8080/, pubkey: 11263KvqW3GZPAvag5sQYtBJSjb25azSTSwoi5Tza9kboaLRxcsv, module: router
Jan 22 19:49:40 heliumGW helium_gateway[1010]: received frame=Settings { flags: (0x1: ACK) }
Jan 22 19:49:40 heliumGW helium_gateway[1010]: received settings ACK; applying Settings { flags: (0x0), enable_push: 0, initial_window_size: 2097152, max_frame_size: 16384 }
Jan 22 19:49:40 heliumGW helium_gateway[1010]: received banner (ignored), oui: 4, uri: http://54.193.165.228:8080/, pubkey: 11263KvqW3GZPAvag5sQYtBJSjb25azSTSwoi5Tza9kboaLRxcsv, module: router, sc_id: TAFpNWISOWULNHW-bs3guqrXHPFY5CG8jLRh3oUZpL4
Jan 22 19:49:40 heliumGW helium_gateway[1010]: send frame=Data { stream_id: StreamId(1) }
Jan 22 19:49:40 heliumGW helium_gateway[1010]: received frame=Headers { stream_id: StreamId(1), flags: (0x4: END_HEADERS) }
Jan 22 19:49:40 heliumGW helium_gateway[1010]: received frame=Data { stream_id: StreamId(1) }
Jan 22 19:49:40 heliumGW helium_gateway[1010]: connected state channel, oui: 1, uri: http://52.8.80.146:8080/, pubkey: 112qB3YaH5bZkCnKA5uRH7tBtGNv2Y5B4smv1jsmvGUzgKT71QpE, module: router
Jan 22 19:49:40 heliumGW helium_gateway[1010]: received banner (ignored), oui: 1, uri: http://52.8.80.146:8080/, pubkey: 112qB3YaH5bZkCnKA5uRH7tBtGNv2Y5B4smv1jsmvGUzgKT71QpE, module: router, sc_id: End4jxiZ1WUz3NIp2k8G5ZyXBFejYz5xhd0WNmZIGv8
Jan 22 19:49:40 heliumGW helium_gateway[1010]: send frame=Data { stream_id: StreamId(1) }
Jan 22 19:49:40 heliumGW helium_gateway[1010]: received frame=WindowUpdate { stream_id: StreamId(1), size_increment: 172 }
Jan 22 19:49:40 heliumGW helium_gateway[1010]: received frame=WindowUpdate { stream_id: StreamId(0), size_increment: 172 }
Jan 22 19:49:40 heliumGW helium_gateway[1010]: received frame=WindowUpdate { stream_id: StreamId(1), size_increment: 172 }
Jan 22 19:49:40 heliumGW helium_gateway[1010]: received frame=WindowUpdate { stream_id: StreamId(0), size_increment: 172 }
Jan 22 19:49:40 heliumGW helium_gateway[1010]: received frame=Data { stream_id: StreamId(1) }
Jan 22 19:49:40 heliumGW helium_gateway[1010]: service.ready=true processing request
Jan 22 19:49:40 heliumGW helium_gateway[1010]: send frame=Headers { stream_id: StreamId(17), flags: (0x4: END_HEADERS) }
Jan 22 19:49:40 heliumGW helium_gateway[1010]: send frame=Data { stream_id: StreamId(17) }
Jan 22 19:49:40 heliumGW helium_gateway[1010]: send frame=Data { stream_id: StreamId(17), flags: (0x1: END_STREAM) }
Jan 22 19:49:40 heliumGW helium_gateway[1010]: received frame=Data { stream_id: StreamId(1) }
Jan 22 19:49:41 heliumGW helium_gateway[1010]: received frame=Data { stream_id: StreamId(1) }
Jan 22 19:49:41 heliumGW helium_gateway[1010]: received frame=Data { stream_id: StreamId(1) }
Jan 22 19:49:41 heliumGW helium_gateway[1010]: received frame=WindowUpdate { stream_id: StreamId(17), size_increment: 74 }
Jan 22 19:49:41 heliumGW helium_gateway[1010]: received frame=WindowUpdate { stream_id: StreamId(0), size_increment: 74 }
Jan 22 19:49:41 heliumGW helium_gateway[1010]: received frame=Headers { stream_id: StreamId(17), flags: (0x4: END_HEADERS) }
Jan 22 19:49:41 heliumGW helium_gateway[1010]: received frame=Data { stream_id: StreamId(17) }
Jan 22 19:49:41 heliumGW helium_gateway[1010]: received frame=Headers { stream_id: StreamId(17), flags: (0x5: END_HEADERS | END_STREAM) }
Jan 22 19:49:41 heliumGW helium_gateway[1010]: accepting new state channel, oui: 4, uri: http://54.193.165.228:8080/, pubkey: 11263KvqW3GZPAvag5sQYtBJSjb25azSTSwoi5Tza9kboaLRxcsv, module: router, sc_id: TAFpNWISOWULNHW-bs3guqrXHPFY5CG8jLRh3oUZpL4
Jan 22 19:49:41 heliumGW helium_gateway[1010]: send frame=Data { stream_id: StreamId(11) }
Jan 22 19:49:41 heliumGW helium_gateway[1010]: send frame=Data { stream_id: StreamId(1) }
Jan 22 19:49:41 heliumGW helium_gateway[1010]: received frame=WindowUpdate { stream_id: StreamId(1), size_increment: 200 }
Jan 22 19:49:41 heliumGW helium_gateway[1010]: received frame=WindowUpdate { stream_id: StreamId(0), size_increment: 200 }
Jan 22 19:49:41 heliumGW helium_gateway[1010]: received frame=Data { stream_id: StreamId(1) }
Jan 22 19:49:41 heliumGW helium_gateway[1010]: received frame=Data { stream_id: StreamId(1) }
Jan 22 19:49:41 heliumGW helium_gateway[1010]: received frame=Data { stream_id: StreamId(1) }
Jan 22 19:49:41 heliumGW helium_gateway[1010]: service.ready=true processing request
Jan 22 19:49:41 heliumGW helium_gateway[1010]: send frame=Headers { stream_id: StreamId(19), flags: (0x4: END_HEADERS) }
Jan 22 19:49:41 heliumGW helium_gateway[1010]: send frame=Data { stream_id: StreamId(19) }
Jan 22 19:49:41 heliumGW helium_gateway[1010]: send frame=Data { stream_id: StreamId(19), flags: (0x1: END_STREAM) }
Jan 22 19:49:41 heliumGW helium_gateway[1010]: received frame=WindowUpdate { stream_id: StreamId(11), size_increment: 74 }
Jan 22 19:49:41 heliumGW helium_gateway[1010]: received frame=WindowUpdate { stream_id: StreamId(0), size_increment: 74 }
Jan 22 19:49:41 heliumGW helium_gateway[1010]: received frame=WindowUpdate { stream_id: StreamId(19), size_increment: 74 }
Jan 22 19:49:41 heliumGW helium_gateway[1010]: received frame=WindowUpdate { stream_id: StreamId(0), size_increment: 74 }
Jan 22 19:49:41 heliumGW helium_gateway[1010]: received frame=Headers { stream_id: StreamId(19), flags: (0x4: END_HEADERS) }
Jan 22 19:49:41 heliumGW helium_gateway[1010]: received frame=Data { stream_id: StreamId(19) }
Jan 22 19:49:41 heliumGW helium_gateway[1010]: received frame=Headers { stream_id: StreamId(19), flags: (0x5: END_HEADERS | END_STREAM) }
Jan 22 19:49:41 heliumGW helium_gateway[1010]: accepting new state channel, oui: 1, uri: http://52.8.80.146:8080/, pubkey: 112qB3YaH5bZkCnKA5uRH7tBtGNv2Y5B4smv1jsmvGUzgKT71QpE, module: router, sc_id: 4gwp3GxHi08YIXeWLgPf1_UVtV6rfpO438oEdgchT0Y
Jan 22 19:49:41 heliumGW helium_gateway[1010]: send frame=Data { stream_id: StreamId(15) }
Jan 22 19:49:41 heliumGW helium_gateway[1010]: send frame=Data { stream_id: StreamId(1) }
Jan 22 19:49:41 heliumGW helium_gateway[1010]: received frame=WindowUpdate { stream_id: StreamId(1), size_increment: 200 }
Jan 22 19:49:41 heliumGW helium_gateway[1010]: received frame=WindowUpdate { stream_id: StreamId(0), size_increment: 200 }
Jan 22 19:49:41 heliumGW helium_gateway[1010]: received frame=WindowUpdate { stream_id: StreamId(15), size_increment: 74 }
Jan 22 19:49:41 heliumGW helium_gateway[1010]: received frame=WindowUpdate { stream_id: StreamId(0), size_increment: 74 }

**device join failed and no join packet showed in Helium console ( both console.helium.com and staging-console.helium.wtf )**

![image](https://user-images.githubusercontent.com/29297051/150635661-412640e7-c6ff-4311-b9c0-48185e0185e5.png)

**Comment by madninja** [comment]
As far as I can tell you did not install a lora packet forwarder on your raspi to receive packets from the lora card you must have attached to the raspberry pi. Once you have that setup and configured right (including the same region setup) you can turn of debug mode in helium_gatway and watch for received packets it gets from he packet forwarder. 

If you have any more questions, please join us in discord in the gateay-development channel. There are a lot of people there that have done this before and happy to help.

**Comment by copy123GitHub** [comment]
**Thanks for response.**

**I have used this gateway with chirpstack and additionally add helium_gateway.**
**I believe the packet reached the helium_gateway by this log**

>>
and restart my Device to get the log of helium-gateway at join request as below:

Jan 22 19:49:40 heliumGW helium_gateway[1010]: uplink @3686964924 us, 922.30 MHz, Ok(DataRate(SF12, BW125)), snr: 9.2, rssi: -59, len: 23 from MacAddress(B8:27:EB:FF:FE:26:6F), module: gateway
>>
