### ISSUE TITLE
Helium Data Only Hotspot Issue - helium_gateway, Code: 111

### ISSUE THREAD

**Issue by nathanfield1990** [helium/gateway-rs#178]
Following this tutorial:
https://docs.helium.com/mine-hnt/data-only-guides/balena-data-only-hotspot/

I did not install the gatewayrs and packet forwarder separately as it comes with the newest Balena image, you can see gatewayrs is active below.

So, I flashed SD card, started up device, launched "helium-miner" service, then typed in "helium_gateway key info" which is supposed to output my address and name. Instead I get the below. 

root@f54261eeaa33:/opt/nebra-gatewayrs# helium_gateway key info
Error: Service(Service(tonic::transport::Error(Transport, hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })))))

I also get the same issue when trying to add a wallet.

I saw a message from you that says "Ahh but the context helps a lot @pe1mew! Alpha.19 did not require the helium_gateway service to be running whereas alpha.21 does. This is due to it needing to support crypto chips while the service is running" if this is going on.

If I ls in this folder I get: root@f54261eeaa33:/opt/nebra-gatewayrs# ls
helium-gateway-v1.0.0-alpha.19-raspi01.deb  keys.py  settings.toml  start-gatewayrs.sh 

Which makes me think I am running alpha.19. Also, I am literally doing this today so I would imagine this issue was taken care of already.

For exact information, simply follow the link at the top, I am using the "Deploy with balena" button and following the instructions.

I am stuck at the "test the helium hotspot" section of this tutorial until I get more info.

Any help would be great

This is my device inside the balena environment.
![Capture](https://user-images.githubusercontent.com/52389004/150655254-4dc14534-fd56-449d-bf4e-0ef2fd6004b0.PNG)
!

**Comment by lthiery** [comment]
@nathanfield1990 

If Balena is shipping an old verison, it is likely no longer compatible with what's current. I believe that's why your having the gRPC connection issues.

If you are building on top of Balena, I'm not sure there's much you and I can do to debug this further. I will reach out and see if they can update their integration.

**Comment by mpous** [comment]
@nathanfield1990 i'm currently checking this issue to iterate the version of the data only hotspot! i will keep you updated!

@lthiery thanks :)
