### ISSUE TITLE
No Transmitted nor Downlink

### ISSUE THREAD

**Issue by Kame160** [helium/gateway-rs#179]
Hello,

I set up a RAK7258 as a dataonly hotspot.  It is registered and visible on explorer.helium.com, I use a Dragino LGT92 GPS tracker (registered on console.helium.com) next to it: I only see received data and uplink, no transmited nor dowlink at all.

Can someone guide me - no more debugging idea ...

Thanks
![No Transmitted](https://user-images.githubusercontent.com/6997425/150684662-70908375-03d8-4d6b-9c10-9b0ae394ade6.PNG)
![No Downlink](https://user-images.githubusercontent.com/6997425/150684664-45c8d948-687d-4ad0-bfca-a0a33a38056d.PNG)

**Comment by lthiery** [comment]
@Kame160 

Which LNS has your LGT92 registered?

Do you have logs from gateway-rs?

**Comment by madninja** [comment]
@Kame160 I'm going to close this due to lack of activity. If you still have issues let us know
