### ISSUE TITLE
lora packet does not reach to console.helium.com

### ISSUE THREAD

**Issue by copy123GitHub** [helium/gateway-rs#181]
Hi

in issue #177, I commented that packet log show in logging of helium_gateway,
and packet forward was installed and used with chirpstack lorawan.

but, I cannot reopen this issue. so I made a new issue #181

thanks

============================================

**Thanks for response.**

**I have used this gateway with chirpstack and additionally add helium_gateway.**
**I believe the packet reached the helium_gateway by this log**

**I have modified ip, port ( 127.0,0,1  , 1680 ) in global_conf.json of packet_forwarder**

**As logged :** 

and restart my Device to get the log of helium-gateway at join request as below:

Jan 22 19:49:40 heliumGW helium_gateway[1010]: uplink @3686964924 us, 922.30 MHz, Ok(DataRate(SF12, BW125)), snr: 9.2, rssi: -59, len: 23 from MacAddress(B8:27:EB:FF:FE:26:6F), module: gateway

_Originally posted by @copy123GitHub in https://github.com/helium/gateway-rs/issues/177#issuecomment-1019396453_

**Comment by madninja** [comment]
Did you register the end device that produced that packet on either production or staging console?

**Comment by copy123GitHub** [comment]
Thanks 

Yes, I registered it as below:

![image](https://user-images.githubusercontent.com/29297051/150893056-bf812453-1573-4826-b379-42c4f61a30ab.png)


By the way, Could LoRa Server only for Korea be down?

Thanks

**Comment by IoTThinks** [comment]
For the first joins, you may need to wait a few hours.

**Comment by copy123GitHub** [comment]
Hi,

I changed the region as "US915" from region = "KR920".
It works.
It shows Join Request and Response log in console.helium.com.

I wonder which of "helium gw's ip setting for Korea Lorawan server" or "Korea Lorwan server status" has an issue?
Would you please teach me to get any clue in the log in #177 ? 

Thanks.

**Comment by madninja** [comment]
there's not enough clues in #177. It shows the connected packet forwarder, and I see it getting a state channel from the production router, but then the logs stop. 

You can turn of debug mode and run it again, and leave it running for a while if you still have issues. Make sure you have the **end-device** (not the hotspot) in the production console (which I think you do).

There is no "Korea lorawan server"

**Comment by mrx23dot** [comment]
Is there a way to pre-activate/join my new end-device over API?

It would be log more convenient if the first join worked on the end-device instantly.

**Comment by madninja** [comment]
> Is there a way to pre-activate/join my new end-device over API (instead of RF)?
> 
> It would be log more convenient if the first join worked on the end-device instantly.

I'm not sure what you're asking for feature wise. You need to register your end device in console (either through UI or API). The actual join request is part of the loran standard and not related to "activation". At least as far as I understand your sentence

**Comment by mrx23dot** [comment]
I mean to bypass the 30min delay time it takes to add the new device to the blockchain.
It causes bad user experience.

**Comment by madninja** [comment]
> I mean to bypass the 30min delay time it takes to add the new device to the blockchain.
> It causes bad user experience.

This is quite unrelated to this repo and is related to how a router manages device routing information on chain. When you add a device to console the associated router will add the routing to the chain in a routing_update transaction. Transaction processing on chain takes time since it's not like a normal back-end system that you update with a single request, but a distributed consensus setup that requires 40+ consensus members to agree to the transaction and then all hotspots to notice and incorporate that change. That takes time. 

In addition the router collects multiple device changes (add/removes) before issuing a routing update transaction to avoid creating wild transaction storms. 

Hope that helps. It's definitely not ideal from a user experience perspective but blockchains take some time to do things.
