### ISSUE TITLE
Staging URL vs. Console URL for alpha 21?

### ISSUE THREAD

**Issue by IoTThinks** [helium/gateway-rs#183]
Hi all,
I'm trying to link the Helium Console to my IoT GUI.
However, the uplinks are sometimes uploaded to https://staging-console.helium.wtf and in other days to https://console.helium.com.

Last week, it uploaded to https://console.helium.com and now to https://staging-console.helium.wtf.
Two weeks ago, it uploaded to staging URL.
BTW, the joins will be shown in both URLs!

Are uplinks for alpha 21 supposed to see in staging or console URL?
Is it randomly now or is it being changed by dev team?

Console URL
![image](https://user-images.githubusercontent.com/29994971/151736818-bdf7ac3a-a41f-40ca-83e3-dea5fff530cf.png)

Staging URL
![image](https://user-images.githubusercontent.com/29994971/151736884-470099a9-c9ba-4be5-a2a5-c1703dd29d66.png)

Thanks a lot.

**Comment by madninja** [comment]
That looks like you may have the device(s) registered on both staging and production console. Please make sure  to have a device only registered in one console. Once removed from the other, it may take a while for the router and network to know that this has happened.

**Comment by IoTThinks** [comment]
Ok let me try to remove the devices in Staging URL.

Thanks a lot.

**Comment by IoTThinks** [comment]
I deactivate the device in one of the URLs.
The remaning URL works correctly.

Thanks a lot.
