### ISSUE TITLE
scaling solution add netid into miner config file

### ISSUE THREAD

**Issue by jdgemm** [helium/gateway-rs#190]
- short-term scaling solution to scale use a netid/oui hack, put netid into miner config file (need miner release)

**Comment by dpezely** [comment]
In consideration of packet-purchaser#97 [Update servers to support netid/oui beta](https://github.com/helium/packet-purchaser/issues/97)
which depends upon *this* issue being resolved
and prep for [HIP46: lorawan netid routing](https://github.com/helium/HIP/blob/main/0046-lorawan-netid-routing.md):

Initial plan after exploring the various sets of source code:

- Add `netid` to gateway.proto `routing` as 6 (not into `routing_address`)
- Add netid => oui hashmap as new chain var, `routers`
- Add netid => oui hashmap as gateway-rs config item (with name matching new chain var)
- Have gateway-rs fetch `routers` chain var
- gateway-rs loads `routers` hashmap from local settings.toml
- Local settings.toml overrules chain var (useful for testing after HIP46 passes)

**Comment by madninja** [comment]
thank you for the additional context.. only one question: 

> Local settings.toml overrules chain var (useful for testing after HIP46 passes)

In general we have  been avoiding local settings overriding the chain and only having local settings provide the initial default (like with regions). Having local settings override can cause support/firmware issues when makers don't clear that list or set it inadvertently.  Not against it, just want to understand.

**Comment by dpezely** [comment]
As discussed, no need to break with existing conventions.  Will amend the earlier comment to avoid confusion.

**Comment by jdgemm** [comment]
closing this, to focus on chainvar solution: https://github.com/helium/router/issues/615
