### ISSUE TITLE
Semtech udp parsing error

### ISSUE THREAD

**Issue by skiplyfrance** [helium/gateway-rs#194]
Hi there!
I installed gateway-rs on a Multitech Conduit MTCDT-LEU1-210A with firmware1.7.4.
helium_gateway is up and running, and in the status "online" in the Helium API.
I set the packet forwarder like this:
![image](https://user-images.githubusercontent.com/19359820/154655304-62f12f8c-a541-42bb-8181-77f4d7b53dec.png)
And I get this error:
![image](https://user-images.githubusercontent.com/19359820/154655544-6cfd81df-1849-4cc1-8c81-32952268f8bd.png)
Every 10 seconds (keepalive interval), the array in the message is short, and when a device tries to join, the array increases.
And the devices never reach Helium NS.
Any idea of the cause of this?

**Comment by skiplyfrance** [comment]
Solved.
Need to use https://www.multitech.com/models/94557302LF instead of https://www.multitech.com/models/94557296LF
So that mean you can add this gateway to the list (mLinux is already there, you can add AEP).

**Comment by lthiery** [comment]
Glad you got to the bottom of it! Based on what I'm seeing is that the GWMP version was 1 instead of 2, so perhaps the 94557302LF simply speaks the more recent packet forwarder protocol.
