### ISSUE TITLE
dragino lps8 hacked?

### ISSUE THREAD

**Issue by dvdadie2** [helium/gateway-rs#196]
The LPS8 had been working -> end device activated, uplink activity recorded in the staging console, and finally data transmitted and rewards were showing up helium explorer (usually within a half hour).  Starting a few days ago, something changed, and now -> end device activated, uplink activity recorded in the staging console, but now nothing shows up in helium explorer (ever).

Before, when I would restart the helium gateway, I would see lines like this:

Tue Feb 22 23:25:06 2022 daemon.info helium_gateway[2062]:  INFO starting, oui: 20, uri: http://43.154.117.143:8080/, pubkey: 11Z71QiBvLd8m2LFtgDpVwR86H3mpXsT93wbntF46LUsSxyqxCw, module: router
Tue Feb 22 23:25:06 2022 daemon.info helium_gateway[2062]:  INFO starting, oui: 16, uri: http://13.37.13.24:8080/, pubkey: 11afuQSrmk52mgxLu91AdtDXbJ9wmqWBUxC3hvjejoXkxEZfPvY, module: router
Tue Feb 22 23:25:06 2022 daemon.info helium_gateway[2062]:  INFO starting, oui: 12, uri: http://54.219.236.122:8080/, pubkey: 112ewJNEUfSg3Jvo276tMjzFC2JzmmZcJJ32CWz2fzYqbyCMMTe1, module: router
Tue Feb 22 23:25:07 2022 daemon.info helium_gateway[2062]:  INFO starting, oui: 10, uri: http://54.228.141.195:8080/, pubkey: 11YmZtwTPEuMSFGxze1x9TfDfGezN7vXevLu71iJe9FBbvNRAgk, module: router
Tue Feb 22 23:25:07 2022 daemon.info helium_gateway[2062]:  INFO starting, oui: 9, uri: http://44.238.156.97:8080/, pubkey: 11w77YQLhgUt8HUJrMtntGGr97RyXmot1ofs5Ct2ELTmbFoYsQa, module: router
Tue Feb 22 23:25:07 2022 daemon.info helium_gateway[2062]:  INFO starting, oui: 4, uri: http://54.193.165.228:8080/, pubkey: 11263KvqW3GZPAvag5sQYtBJSjb25azSTSwoi5Tza9kboaLRxcsv, module: router
Tue Feb 22 23:25:07 2022 daemon.info helium_gateway[2062]:  INFO starting, oui: 2, uri: http://54.176.88.149:8080/, pubkey: 1124CJ9yJaHq4D6ugyPCDnSBzQik61C1BqD9VMh1vsUmjwt16HNB, module: router
Tue Feb 22 23:25:07 2022 daemon.info helium_gateway[2062]:  INFO updated routing to height 1238054, module: dispatcher
Tue Feb 22 23:25:07 2022 daemon.info helium_gateway[2062]:  INFO starting, oui: 1, uri: http://52.8.80.146:8080/, pubkey: 112qB3YaH5bZkCnKA5uRH7tBtGNv2Y5B4smv1jsmvGUzgKT71QpE, module: router

The oui's, ip addressess, and pubkeys were persistent (wouldn't change).
Now, over the course of a few minutes, I start to see this:

Tue Feb 22 23:54:39 2022 daemon.info helium_gateway[9241]:  INFO uplink @1774690708 us, 904.90 MHz, Ok(DataRate(SF9, BW125)), snr: 2, rssi: -115, len: 52 from MacAddress(A8:40:41:21:D7:BC:50), module: gateway

Tue Feb 22 23:59:40 2022 daemon.info helium_gateway[4096]:  INFO new packet forwarder client: MacAddress(A8:40:41:21:D7:BC:50), 127.0.0.1:47208, module: gateway

Meanwhile in the system logs, I see this:

Tue Feb 22 23:28:20 2022 authpriv.notice dropbear[5639]: Password auth succeeded for 'root' from 10.0.0.63:52558

Tue Feb 22 23:29:00 2022 cron.info crond[1177]: USER root pid 6651 cmd /etc/init.d/auto_update start

Tue Feb 22 23:29:06 2022 authpriv.info dropbear[6851]: Child connection from 10.0.0.63:52559
Tue Feb 22 23:29:08 2022 authpriv.warn dropbear[6851]: Bad password attempt for 'root' from 10.0.0.63:52559
Tue Feb 22 23:29:08 2022 authpriv.notice dropbear[6851]: Password auth succeeded for 'root' from 10.0.0.63:52559

Tue Feb 22 23:29:50 2022 authpriv.info dropbear[7515]: Child connection from 10.0.0.63:52569
Tue Feb 22 23:30:00 2022 cron.info crond[1177]: USER root pid 7579 cmd /etc/init.d/auto_update start
Tue Feb 22 23:30:00 2022 cron.info crond[1177]: USER root pid 7580 cmd /etc/init.d/DR_enable_rssh.sh start

Tue Feb 22 23:31:16 2022 daemon.info lora_pkt_fwd[2493]: PKT_FWD~ DATA_UNCONF_UP-> {"DevAddr": "0100DA30", "FCtrl": ["ADR": 0, "ADRACKReq": 1, "ACK": 0, "RFU" : "RFU", "FOptsLen": 5], "FCnt": 3361, "FPort": 79, "MIC": "E3703F70"}
Tue Feb 22 23:31:16 2022 daemon.info lora_pkt_fwd[2493]: RXTX~ {"rxpk":[{"tmst":371387412,"time":"2022-02-22T23:31:16.676571Z","chan":6,"rfch":1,"freq":905.100000,"stat":1,"modu":"LORA","datr":"SF9BW125","codr":"4/5","lsnr":-10.0,"rssi":-129,"size":52,"data":"QDDaAAFVIQ3+AOHBAE88ixx9M/BJR0NjlDoZ/gaymPH4w9fq0aHHOf+TAjrtWIxHcD9w4w=="}]}

Tue Feb 22 23:31:16 2022 daemon.info helium_gateway[2062]:  INFO uplink @371387412 us, 905.10 MHz, Ok(DataRate(SF9, BW125)), snr: -10, rssi: -129, len: 52 from MacAddress(A8:40:41:21:D7:BC:50), module: gateway

Tue Feb 22 23:31:39 2022 daemon.info helium_gateway[9241]:  INFO new packet forwarder client: MacAddress(A8:40:41:21:D7:BC:50), 127.0.0.1:47208, module: gateway

Tue Feb 22 23:33:11 2022 daemon.info lora_pkt_fwd[2493]: PKT_FWD~ DATA_UNCONF_UP-> {"DevAddr": "4800080A", "FCtrl": ["ADR": 1, "ADRACKReq": 0, "ACK": 0, "RFU" : "RFU", "FOptsLen": 0], "FCnt": 23, "FPort": 10, "MIC": "128032CD"}
Tue Feb 22 23:33:11 2022 daemon.info lora_pkt_fwd[2493]: RXTX~ {"rxpk":[{"tmst":485993908,"time":"2022-02-22T23:33:11.285744Z","chan":3,"rfch":0,"freq":904.500000,"stat":1,"modu":"LORA","datr":"SF10BW125","codr":"4/5","lsnr":12.2,"rssi":-47,"size":23,"data":"QAoIAEiAFwAKaUZYQxOCuI1Vnc0ygBI="}]}
Tue Feb 22 23:33:11 2022 daemon.info helium_gateway[9241]:  INFO uplink @485993908 us, 904.50 MHz, Ok(DataRate(SF10, BW125)), snr: 12.2, rssi: -47, len: 23 from MacAddress(A8:40:41:21:D7:BC:50), module: gateway

Tue Feb 22 23:33:14 2022 daemon.info lora_pkt_fwd[2493]: PKT_FWD~ DATA_UNCONF_UP-> {"DevAddr": "4800080A", "FCtrl": ["ADR": 1, "ADRACKReq": 0, "ACK": 0, "RFU" : "RFU", "FOptsLen": 0], "FCnt": 24, "FPort": 10, "MIC": "DD11DCC5"}
Tue Feb 22 23:33:14 2022 daemon.info lora_pkt_fwd[2493]: RXTX~ {"rxpk":[{"tmst":489060060,"time":"2022-02-22T23:33:14.348978Z","chan":6,"rfch":1,"freq":905.100000,"stat":1,"modu":"LORA","datr":"SF10BW125","codr":"4/5","lsnr":10.8,"rssi":-66,"size":23,"data":"QAoIAEiAGAAK+ahKM8CL1DEgr8XcEd0="}]}

Tue Feb 22 23:33:14 2022 daemon.info helium_gateway[9241]:  INFO uplink @489060060 us, 905.10 MHz, Ok(DataRate(SF10, BW125)), snr: 10.8, rssi: -66, len: 23 from MacAddress(A8:40:41:21:D7:BC:50), module: gateway
Tue Feb 22 23:33:14 2022 daemon.info lora_pkt_fwd[2493]: INFO~ [up] PUSH_ACK received in 0 ms
Tue Feb 22 23:33:22 2022 daemon.info lora_pkt_fwd[2493]: PKT_FWD~ DATA_UNCONF_UP-> {"DevAddr": "4800080A", "FCtrl": ["ADR": 1, "ADRACKReq": 0, "ACK": 0, "RFU" : "RFU", "FOptsLen": 0], "FCnt": 25, "FPort": 10, "MIC": "246F595C"}
Tue Feb 22 23:33:22 2022 daemon.info lora_pkt_fwd[2493]: RXTX~ {"rxpk":[{"tmst":496900284,"time":"2022-02-22T23:33:22.191459Z","chan":2,"rfch":0,"freq":904.300000,"stat":1,"modu":"LORA","datr":"SF10BW125","codr":"4/5","lsnr":8.2,"rssi":-47,"size":23,"data":"QAoIAEiAGQAKv2fb+uZEEp9EDFxZbyQ="}]}
Tue Feb 22 23:33:22 2022 daemon.info helium_gateway[9241]:  INFO uplink @496900284 us, 904.30 MHz, Ok(DataRate(SF10, BW125)), snr: 8.2, rssi: -47, len: 23 from MacAddress(A8:40:41:21:D7:BC:50), module: gateway

Can someone please tell me if this looks normal?

If I have been hacked is there a way to fix it?
Restore factory settings?

Thanks in advance.

**Comment by madninja** [comment]
I can't tell if you got hacked or not.. When I read this I was assuming that

> Tue Feb 22 23:29:06 2022 authpriv.info dropbear[6851]: Child connection from 10.0.0.63:52559
> Tue Feb 22 23:29:08 2022 authpriv.warn dropbear[6851]: Bad password attempt for 'root' from 10.0.0.63:52559
> Tue Feb 22 23:29:08 2022 authpriv.notice dropbear[6851]: Password auth succeeded for 'root' from 10.0.0.63:52559

meant that this was you logging in to start tailing logs. If this is not the case you may have been compromised, but I can't really help with system security on other people's systems. 

I _do_ know that the mitigations to get past the last chain outage, causes the router to having issues closing state channels. This means your hotspot doesn't get recognized for routing the packets and no data packet rewards are issues until state channels are closed. The fix for this being tested and will get deployed soon.

**Comment by dvdadie2** [comment]
@madninja thanks for taking a look and commenting

**Comment by madninja** [comment]
I'm going to close this since it's not really a gateway-rs issue and more general linux/device security.
