### ISSUE TITLE
Install_update error

### ISSUE THREAD

**Issue by skiplyfrance** [helium/gateway-rs#201]
Hi,

On my Mutlitech Conduit, launching install_update raise following error:

Collected errors:
 * open_outer: Failed to open package '0b3f5dcf44ade7ce57f3f18cb515cb56_releases': Unrecognized archive format
 * pkg_extract_control_file_to_stream: Failed to extract control.tar.gz from package '0b3f5dcf44ade7ce57f3f18cb515cb56_releases'.
 * pkg_init_from_file: Failed to extract control file from 0b3f5dcf44ade7ce57f3f18cb515cb56_releases.

**Comment by lthiery** [comment]
Can you share more logs around this? Which version was originally installed? How did you install it?

**Comment by skiplyfrance** [comment]
I installed version 21 a couple of days ago. I used opkg install and everything ran smootly.
Install_update download the package, but cannot install it.

**Comment by skiplyfrance** [comment]
@madninja do you know how to make the update from 21?

**Comment by madninja** [comment]
please provide the actual command you ran to get to this error?

**Comment by skiplyfrance** [comment]
Sorry, it was a mistake, I have the same error as I had from the begining.

Do you know how I can make the update?

**Comment by madninja** [comment]
> Sorry, it was a mistake, I have the same error as I had from the begining.
> 
> Do you know how I can make the update?

no because I have no idea how you installed it to begin with. A normal package install should work just fine. Maybe provide the actual conduit model, which package gateway-rs you downloaded and the _actual_ command you used to try to install it.

**Comment by skiplyfrance** [comment]
./install_update https://api.github.com/repos/helium/gateway-rs/releases

**Comment by madninja** [comment]
> I installed version 21 a couple of days ago. I used opkg install and everything ran smootly.
> 
> To update I tried: ./install_update https://api.github.com/repos/helium/gateway-rs/releases

and why do you think that install_update command would work at all?

**Comment by skiplyfrance** [comment]
> and why do you think that install_update command would work at all? It's not documented anywhere that that is how you install updates, right

Right. I had an error when auto update was activated (and a peak of data consumption). So I stopped it and try to understand the problem while trying manually. 

Ok this was wrong.

**Comment by skiplyfrance** [comment]
So now, I'm doing:
`opkg install helium-gateway-v1.0.0-alpha.23-mtcdt.ipk
`

And I get:

```
Upgrading helium_gateway from 1.0.0-alpha.21 to 1.0.0-alpha.23 on root.
Installing helium_gateway (1.0.0) on root.
usage: update-rc.d [-n] [-f] [-r <root>] <basename> remove
       update-rc.d [-n] [-r <root>] [-s] <basename> defaults [NN | sNN kNN]
       update-rc.d [-n] [-r <root>] [-s] <basename> start|stop NN runlvl [runlvl] [...] .
                -n: not really
                -f: force
                -v: verbose
                -r: alternate root path (default is /)
                -s: invoke start methods if appropriate to current runlevel
To remove package debris, try `opkg remove helium_gateway`.
To re-attempt the install, try `opkg install helium_gateway`.
Collected errors:
 * pkg_run_script: package "helium_gateway" prerm script returned status 1.
 * prerm_upgrade_old_pkg: prerm script for package "helium_gateway" failed
 * opkg_solver_install: Cannot install package helium_gateway.
```

**Comment by skiplyfrance** [comment]
Ok, when I'm doing:
`/usr/sbin/update-rc.d -f -v helium_gateway remove
`
I got:
`Removing any system startup links for helium_gateway ...`

But same error after.

**Comment by skiplyfrance** [comment]
`/usr/sbin/update-rc.d helium_gateway -f -v remove`

Gives:
```
usage: update-rc.d [-n] [-f] [-r <root>] <basename> remove
       update-rc.d [-n] [-r <root>] [-s] <basename> defaults [NN | sNN kNN]
       update-rc.d [-n] [-r <root>] [-s] <basename> start|stop NN runlvl [runlvl] [...] .
                -n: not really
                -f: force
                -v: verbose
                -r: alternate root path (default is /)
                -s: invoke start methods if appropriate to current runlevel

```

**Comment by madninja** [comment]
Try figuring out how to force remove a package using opkg.

**Comment by madninja** [comment]
Thanks for trying the instructions to figure out that the prerm script for mtcdt is broken. #209 fixes this. You will need to force remove the package on your gateway and install newer versions until this lands in a next tagged version (likely alpha.24)

**Comment by skiplyfrance** [comment]
Ok I will try this tomorrow.

I don't know if you are interested by the info, but I solved another problem. Gateway-rs was not starting on boot.

I had to do it with crontab on @reboot, with user "admin" (and not root, à speciality of Multitech).

**Comment by skiplyfrance** [comment]
Done. Had to use opkg remove.

Now I have #210

**Comment by madninja** [comment]
Note that you should not be running services with crontab like you said. The package installer installs the service with init.d which should start on boot

**Comment by skiplyfrance** [comment]
> The package installer installs the service with init.d which should start on boot

It doesn't

**Comment by madninja** [comment]
> > The package installer installs the service with init.d which should start on boot
> 
> It doesn't

It should given that the [postinst step](https://github.com/helium/gateway-rs/blob/main/package/mtcdt/control/postinst)  tries to establish the links in init.d. Can you see what happens when you run 

```
/usr/sbin/update-rc.d helium_gateway defaults
```
by hand while ssh into the gateway?
