### ISSUE TITLE
 1.0.0-alpha.22 info error

### ISSUE THREAD

**Issue by dvdadie2** [helium/gateway-rs#202]
when this command is issued:  helium_gateway info

this is returned:

Error: Service(Service(tonic::transport::Error(Transport, hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 146, kind: ConnectionRefused, message: "Connection refused" })))))

does anyone know how to fix this from the ssh command line?
i found some commands in the code - "start_service", "enable", "disable","reload" but those don't appear to be useful when used after "helium_gateway".

**Comment by lthiery** [comment]
You need to run `helium_gateway start_service` so that the service begins. When the service is running, 
 you can run `helium_gateway info`.

**Comment by dvdadie2** [comment]
@lthiery thank you.  i really wish that would have worked, but it didn't.  

instead of starting the service, this is returned:
error: Found argument 'start_service' which wasn't expected, or isn't valid in this context

some background - i am using the dragino lps8 and recently upgraded to firmware version lgw-5.4.1644990565.  i believe that during that upgrade the helium_gateway version updated from alpha.21 (which worked) to alpha.22 (not currently working).  my suspicion is that something is wrong with the dragino file(s) and / or the dragino GUI.

please note that i am not looking for dragino help - i am just looking for gateway-rs help.  
that is why i am trying to bypass the dragino GUI and control the unit from putty / ssh.

i tried to downgrade the helium_gateway version from alpha.22 to alpha.21 but it wouldn't let me.
i also tried to re-install alpha.22 with this command:

opkg install /tmp/helium-gateway-v1.0.0-alpha.22-dragino.ipk

which returned:

Package helium_gateway (1.0.0-alpha.22) installed in root is up to date.

nothing noticeably changed.

thanks for your time.

**Comment by drberthol** [comment]
same with lig16 since few hours....

**Comment by lthiery** [comment]
I was wrong about "start_service". It's just `helium_gateway server`. Also, you can access the help menu by using `--help` to see valid commands and explanations of how specific commands work.

eg:
```
helium_gateway --help
helium_gateway server --help
```

**Comment by lthiery** [comment]
You can ignore those JSON parsing errors but I'll reach out to Dragino about that anyway.

`INFO new packet forwarder client: A8:40:41:21:D7:BC:41:50, 127.0.0.1:45093, module: gateway` is not out of place. A GWMP client is only considered "connected" once it sends a `PULL_DATA` and it's received by the Host. What you see above that frame is `PUSH_DATA` status frame which was sent before the `PULL_DATA` frame which creations the "connection". The PULL_DATA frames are usually sent every N seconds, so it's entirely possible and not really worrisome.

This basically looks good to me. If you open another terminal window, you can interact with the server instance.

**Comment by xiaoye-x** [comment]
I notice those JSON parsing errors, which seem the sensor node uplink format error instead of the gateway parsing issue.  could let me know what your sensor node is?

**Comment by dragino** [comment]
> 

The info you sent is log from gateway-rs. Can you also show the log for LPS8 packet_forwarder, the most properly reason is the gateway-rs parse the info from packet_frowarder wrongly. Below is what we can see from packet_forwarder of LPS8:
Looks ok. 

PKTUP~ [server] JSON: {"stat":{"time":"2022-03-02 08:41:28 UTC","rxnb":5,"rxok":2,"rxfw":2,"ackr":0.0,"dwnb":0,"txnb":0,"pfrm":"SX1308","mail":"dragino-1e9674@dragino.com","desc":"Dragino LoRaWAN Gateway"}}
Wed Mar  2 08:41:28 2022 daemon.info fwd[14617]: PKTUP~ [server2] JSON: {"stat":{"time":"2022-03-02 08:41:28 UTC","rxnb":5,"rxok":2,"rxfw":2,"ackr":0.0,"dwnb":0,"txnb":0,"pfrm":"SX1308","mail":"dragino-**1e9674@dragino.com","desc":"Dragino LoRaWAN Gateway"}}**

**Comment by lthiery** [comment]
@dragino This is not what is received over UDP. 

The error message from dvdadie presents the entire datagram:
```
[
        2, 181, 81, 0, 168, 64, 65, 33, 215, 188, 65, 80, 123, 34, 115, 116, 97, 116, 34, 58, 123,
        34, 116, 105, 109, 101, 34, 58, 34, 50, 48, 50, 50, 45, 48, 50, 45, 50, 56, 32, 49, 57, 58,
        51, 56, 58, 52, 54, 32, 85, 84, 67, 34, 44, 34, 108, 97, 116, 105, 34, 58, 52, 56, 46, 56,
        53, 57, 57, 55, 44, 34, 108, 111, 110, 103, 34, 58, 45, 49, 50, 50, 46, 54, 50, 55, 56, 51,
        44, 34, 97, 108, 116, 105, 34, 58, 51, 48, 48, 44, 34, 114, 120, 110, 98, 34, 58, 48, 44,
        34, 114, 120, 111, 107, 34, 58, 48, 44, 34, 114, 120, 102, 119, 34, 58, 48, 44, 34, 97, 99,
        107, 114, 34, 58, 48, 46, 48, 44, 34, 100, 119, 110, 98, 34, 58, 48, 44, 34, 116, 120, 110,
        98, 34, 58, 48, 44, 34, 112, 102, 114, 109, 34, 58, 34, 83, 88, 49, 51, 48, 56, 34, 44, 34,
        109, 97, 105, 108, 34, 58, 34, 100, 114, 97, 103, 105, 110, 111, 45, 50, 49, 100, 55, 98,
        99, 64, 100, 114, 97, 103, 105, 110, 111, 46, 99, 111, 109, 34, 44, 34, 100, 101, 115, 99,
        125,
    ]
    ```

We can parse this by hand using [the spec](https://github.com/Lora-net/packet_forwarder/blob/master/PROTOCOL.TXT):
2 is the GWMP protocol identifier
181, 81 is the random token
0 is the PUSH_DATA identifier
168, 64, 65, 33, 215, 188, 65, 80 is the MAC

and 123 starts the JSON string:
```
        123, 34, 115, 116, 97, 116, 34, 58, 123,
        34, 116, 105, 109, 101, 34, 58, 34, 50, 48, 50, 50, 45, 48, 50, 45, 50, 56, 32, 49, 57, 58,
        51, 56, 58, 52, 54, 32, 85, 84, 67, 34, 44, 34, 108, 97, 116, 105, 34, 58, 52, 56, 46, 56,
        53, 57, 57, 55, 44, 34, 108, 111, 110, 103, 34, 58, 45, 49, 50, 50, 46, 54, 50, 55, 56, 51,
        44, 34, 97, 108, 116, 105, 34, 58, 51, 48, 48, 44, 34, 114, 120, 110, 98, 34, 58, 48, 44,
        34, 114, 120, 111, 107, 34, 58, 48, 44, 34, 114, 120, 102, 119, 34, 58, 48, 44, 34, 97, 99,
        107, 114, 34, 58, 48, 46, 48, 44, 34, 100, 119, 110, 98, 34, 58, 48, 44, 34, 116, 120, 110,
        98, 34, 58, 48, 44, 34, 112, 102, 114, 109, 34, 58, 34, 83, 88, 49, 51, 48, 56, 34, 44, 34,
        109, 97, 105, 108, 34, 58, 34, 100, 114, 97, 103, 105, 110, 111, 45, 50, 49, 100, 55, 98,
        99, 64, 100, 114, 97, 103, 105, 110, 111, 46, 99, 111, 109, 34, 44, 34, 100, 101, 115, 99,
        125
```

In Python, you can convert this to a string:

```python
>>> a = [        123, 34, 115, 116, 97, 116, 34, 58, 123,
...         34, 116, 105, 109, 101, 34, 58, 34, 50, 48, 50, 50, 45, 48, 50, 45, 50, 56, 32, 49, 57, 58,
...         51, 56, 58, 52, 54, 32, 85, 84, 67, 34, 44, 34, 108, 97, 116, 105, 34, 58, 52, 56, 46, 56,
...         53, 57, 57, 55, 44, 34, 108, 111, 110, 103, 34, 58, 45, 49, 50, 50, 46, 54, 50, 55, 56, 51,
...         44, 34, 97, 108, 116, 105, 34, 58, 51, 48, 48, 44, 34, 114, 120, 110, 98, 34, 58, 48, 44,
...         34, 114, 120, 111, 107, 34, 58, 48, 44, 34, 114, 120, 102, 119, 34, 58, 48, 44, 34, 97, 99,
...         107, 114, 34, 58, 48, 46, 48, 44, 34, 100, 119, 110, 98, 34, 58, 48, 44, 34, 116, 120, 110,
...         98, 34, 58, 48, 44, 34, 112, 102, 114, 109, 34, 58, 34, 83, 88, 49, 51, 48, 56, 34, 44, 34,
...         109, 97, 105, 108, 34, 58, 34, 100, 114, 97, 103, 105, 110, 111, 45, 50, 49, 100, 55, 98,
...         99, 64, 100, 114, 97, 103, 105, 110, 111, 46, 99, 111, 109, 34, 44, 34, 100, 101, 115, 99,
...         125]
>>> string = ""
>>> for i in a:
...     string+=chr(i)
... 
>>> string
'{"stat":{"time":"2022-02-28 19:38:46 UTC","lati":48.85997,"long":-122.62783,"alti":300,"rxnb":0,"rxok":0,"rxfw":0,"ackr":0.0,"dwnb":0,"txnb":0,"pfrm":"SX1308","mail":"dragino-21d7bc@dragino.com","desc}'
```

You can see, why actually see the `}` which closes the Python object. Is your serializer behaving properly?

**Comment by madninja** [comment]
Note that this release https://github.com/helium/gateway-rs/releases/tag/v1.0.0-alpha.23 should fix the issue

**Comment by drberthol** [comment]
thanks. It's working now. Only to press download and install and that's it.

Marc Berthelot



Le jeu. 3 mars 2022 à 08:26, Marc Nijdam ***@***.***> a
écrit :
