### ISSUE TITLE
Issue Pulling The Status On My Dragino LPS8 915

### ISSUE THREAD

**Issue by dcgtechnologies** [helium/gateway-rs#203]
Hello....I am trying to get my DATA Only gateway registered on the network and after I run the command "helium_gateway key info". I get the error below:

Error: Service(Service(tonic::transport::Error(Transport, hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 146, kind: ConnectionRefused, message: "Connection refused" })))))

I am including my logs below:

Mon Feb 28 10:22:00 2022 user.notice iot_keep_alive: Internet Access OK: via eth1
Mon Feb 28 10:22:00 2022 user.notice iot_keep_alive: use WAN or WiFi for internet access now
Mon Feb 28 10:22:15 2022 user.notice iot_keep_alive: Internet Access OK: via eth1
Mon Feb 28 10:22:15 2022 user.notice iot_keep_alive: use WAN or WiFi for internet access now
Mon Feb 28 10:22:20 2022 daemon.err uhttpd[4050]: wc: /tmp/logfile.log: No such file or directory
Mon Feb 28 10:22:20 2022 daemon.err uhttpd[4050]: sh: 2000000: unknown operand
Mon Feb 28 10:22:23 2022 daemon.err uhttpd[4050]: wc: /tmp/logfile.log: No such file or directory
Mon Feb 28 10:22:23 2022 daemon.err uhttpd[4050]: sh: 2000000: unknown operand
Mon Feb 28 10:22:23 2022 daemon.err uhttpd[4050]: killall: logread: no process killed
Mon Feb 28 10:22:26 2022 daemon.info fwd[20924]:
Mon Feb 28 10:22:26 2022 daemon.info fwd[20924]: ################[PKT_SERV] no report of this service ###############
Mon Feb 28 10:22:26 2022 daemon.info fwd[20924]: PKTUP~ [server2] JSON: {"stat":{"time":"2022-02-28 16:22:26 UTC","rxnb":0,"rxok":0,"rxfw":0,"ackr":0.0,"dwnb":0,"txnb":0,"pfrm":"SX1308","mail":"dragino-1f7e68@dragino.com","desc":"Dragino LoRaWAN Gateway"}}
Mon Feb 28 10:22:26 2022 daemon.info fwd[20924]: PKTUP~ [server] JSON: {"stat":{"time":"2022-02-28 16:22:26 UTC","rxnb":0,"rxok":0,"rxfw":0,"ackr":0.0,"dwnb":0,"txnb":0,"pfrm":"SX1308","mail":"dragino-1f7e68@dragino.com","desc":"Dragino LoRaWAN Gateway"}}
Mon Feb 28 10:22:30 2022 user.notice iot_keep_alive: Internet Access OK: via eth1
Mon Feb 28 10:22:30 2022 user.notice iot_keep_alive: use WAN or WiFi for internet access now

What am I missing here? Thank you.

**Comment by madninja** [comment]
the heliujm_gateway service actually needs to be _running_ before you can talk to it. How was helium-gateway installed?

**Comment by dcgtechnologies** [comment]
> the heliujm_gateway service actually needs to be _running_ before you can talk to it. How was helium-gateway installed?

I have installed it and I did start the Helium Gateway Service, but it is taking forever to start up. I installed the latest version of the Helium Dragino alpha.22.ipk.

**Comment by drberthol** [comment]
for me everythings was working until 2:00 am ( western time -7 ).  I tried all the solutions from here from different firmware et gateway-rs and it's still the same.  The problem could be with the connection with Helium to give new animal name ?

**Comment by megabyte2010** [comment]
Same here with lps8 868. Gui says:

gateway-rs status | No Gateway-rs Connected
-- | --
 
  | gateway-rs version | helium_gateway 1.0.0-alpha.22
 
  | Hostpot key | NULL!
 
  | Hostpot animal name | NULL!

**Comment by dcgtechnologies** [comment]
I start the Helium service by initiating the following start command. It as been going on for almost 24 hours now and all I get is the following screen capture. I do no know how long this is supposed to go on for. Any idea what I am missing here? Thank you.



![Capture](https://user-images.githubusercontent.com/100606500/156220654-7a849684-2974-43b2-a0b3-3be4e2af3fd7.JPG)

**Comment by dcgtechnologies** [comment]
> gateway-rs status

**Comment by dcgtechnologies** [comment]
> the heliujm_gateway service actually needs to be _running_ before you can talk to it. How was helium-gateway installed?

I just installed using these commands:

Dowload

wget -O helium-gateway-v1.0.0-alpha.22-dragino.ipk https://github.com/helium/gateway-rs/releases/download/v1.0.0-alpha.22/helium-gateway-v1.0.0-alpha.22-dragino.ipk

Installation

opkg install /tmp/helium-gateway-v1.0.0-alpha.22-dragino.ipk

I can not get the status.......I run the command and I get the results above in my previous posts. Thanks.

**Comment by madninja** [comment]
sorry then why do you close this?

**Comment by dcgtechnologies** [comment]
> sorry then why did you close this issue?

I never closed it. I did not even know it was closed. Someone else might have?

**Comment by lthiery** [comment]
> > sorry then why did you close this issue?
> 
> I never closed it unless I was not paying attention and did it by accident. I did not even know it was closed. Can I reopen it?
Your account closed the issue for sure:
![image](https://user-images.githubusercontent.com/1606640/156479413-fba26abe-517a-4c13-bbb0-e043cc1644a3.png)

**Comment by dcgtechnologies** [comment]
> > > sorry then why did you close this issue?
> > 
> > 
> > I never closed it unless I was not paying attention and did it by accident. I did not even know it was closed. Can I reopen it?
> > Your account closed the issue for sure:
> > ![image](https://user-images.githubusercontent.com/1606640/156479413-fba26abe-517a-4c13-bbb0-e043cc1644a3.png)

Yes I saw it before. So I see there is a bug in Alpha 22 so I am downgrading to Alpha 21.

**Comment by madninja** [comment]
Note that this release https://github.com/helium/gateway-rs/releases/tag/v1.0.0-alpha.23 should fix the issue

**Comment by dcgtechnologies** [comment]
> Note that this release https://github.com/helium/gateway-rs/releases/tag/v1.0.0-alpha.23 should fix the issue

Thank I downloaded it and tried it out and I get the below error:

![image](https://user-images.githubusercontent.com/100606500/156614124-b7919a9e-42c2-467b-819f-7ef82437bc2d.png)

Do you know how I can fix this? Image Metadata not found invalid image type. Thank you.

**Comment by dcgtechnologies** [comment]
Now this issue is resolved. All of this because of bad firmware, but thank you for your help.

**Comment by madninja** [comment]
Yeah looks like you were confused between a gateway-rs release and a dragoon firmware release? This repo is really not responsible for or able to help with dragino firmware support. 

I’m glad you got it working. Was it just a dragino firmware update?

**Comment by madninja** [comment]
I’m glad it’s working for you. The alpha software releases will contain bugs and I’m sorry you had issues
