### ISSUE TITLE
Dragino LPS8 EU868

### ISSUE THREAD

**Issue by Nickbelane2021** [helium/gateway-rs#205]
I have update gateway Dragino LPS8 Eu868 to alpha 22 and now cannot load Key and animal name.

  | gateway-rs status | No Gateway-rs Connected
 
  | gateway-rs version | helium_gateway 1.0.0-alpha.22
 
  | Hostpot key | NULL!
 
  | Hostpot animal name | NULL!

I try to reinstall an old firmware but not resolve the problem.
Thanks for reply.
Nick

**Comment by madninja** [comment]
How did you update the firmware?

**Comment by Nickbelane2021** [comment]
> 

I donwnload the firmware here: https://www.dragino.com/downloads/index.php?dir=LoRa_Gateway/LPS8/Firmware/Release/  then i upload it using dragino system menu and finally install. I also try discard settings ...

**Comment by Nickbelane2021** [comment]
>

**Comment by Nickbelane2021** [comment]
Same error for me, i also replace my old gateway bin file, but it does not work.

root@dragino-1f8bdc:/tmp# helium_gateway key info
Error: Service(Service(tonic::transport::Error(Transport, hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 146, kind: ConnectionRefused, message: "Connection refused" })))))

**Comment by madninja** [comment]
This means helium_gateway is not running. If you installed a fragile firmware with the alpha.22 on it perhaps you should contact dragino? It would seem their firmware is not working right. 

Otherwise please join us in discord in the #gateway-development channel so we can figure out what is going on. I need access to a dragino that is experiencing the issue to see what is causing it

**Comment by madninja** [comment]
Note that this release https://github.com/helium/gateway-rs/releases/tag/v1.0.0-alpha.23 should fix the issue

**Comment by madninja** [comment]
> i have been having similar issues but i finally got the lps8 to recognize my old animal name... my dragino firmware is version is 5.4.1640315898. i just downloaded alpha 23. i manually installed alpha 23 from the ssh command line. in the dragino software, under lorawan menu, under helium iot menu, near upload gateway-rs key, i selected my old file. it didn't work. then i used winscp to copy the gateway_key.bin file to the /etc/helium_gateway folder on the lps8 and overwrote the file. then i went back to the dragino software, uploaded the same file - and it worked.

Well done, and thank you so much for reporting your workaround!

**Comment by IoTThinks** [comment]
> i have been having similar issues but i finally got the lps8 to recognize my old animal name... my dragino firmware is version is 5.4.1640315898. i just downloaded alpha 23. i manually installed alpha 23 from the ssh command line. in the dragino software, under lorawan menu, under helium iot menu, near upload gateway-rs key, i selected my old file. it didn't work. then i used winscp to copy the gateway_key.bin file to the /etc/helium_gateway folder on the lps8 and overwrote the file. then i went back to the dragino software, uploaded the same file - and it worked.
> 
> UPDATE: i upgraded the dragino firmware to 5.4.1644990565. after everything was loaded: i still had to do the workaround noted above to get my old animal name back.

You saved my days.
I need to reboot after your steps to get my old animal back.

So I have a few ghost aminals which are accidentally born after upgrading Dragino firmware then gateway-rs.
