### ISSUE TITLE
Gateway-rs 1.0.0. Alpha 23

### ISSUE THREAD

**Issue by davidsvoice** [helium/gateway-rs#208]
Hi,
I just received gateway-rs 1.0.0 alpha 23 for my dragino lps8.
Now, in the lorawan section, the gateway is connected again 
(it wasn't in alpha 22), but the hotspot key is empty, and the animal name is wrong
(automatically created new). I tried to restore my original gateway_key.bin, but nothing changed.
I am not willing to onboard and pay fees again with this new created animal name.
What should I do to restore my active hotspot ?
Thanks for help,
davidsvoice

![Screen](https://user-images.githubusercontent.com/100861595/156605449-b5d479eb-44e3-480f-a29c-68b29b8db181.jpg)

**Comment by madninja** [comment]
It sounds like you are not putting gateway_key.bin in the right place

**Comment by davidsvoice** [comment]
Hi, thx for help. 
So what should be the right place ? I found the key via WinSCP in the "var" section.
The Dragino firmware had a new release just some weeks ago and worked fine so far.
I considered to reset factory settings, but not sure if it would solve my problem.

**Comment by madninja** [comment]
@davidsvoice that sounds like a dragon issue. Try the workaround mentioned in: https://github.com/helium/gateway-rs/issues/205#issuecomment-1058619465
