### ISSUE TITLE
Offer releases for more platforms

### ISSUE THREAD

**Issue by philltran** [helium/gateway-rs#21]
What would it take to offer releases for more platforms? There are packaged releases for helium-gateway-v0.1.1-alpha.14-klkgw.ipk and helium-gateway-v0.1.1-alpha.14-ramips_24kec.ipk while there are four platforms supported. 

| Platform       | Target                         | Products                                                 |
| -------------- | ------------------------------ | -------------------------------------------------------- |
| [ramips_24kec] | mipsel-unknown-linux-musl      | :white_check_mark: [RAK833] EVB Kit                      |
|                |                                | :white_check_mark: [RAK7258] (WisGate Edge Lite)         |
|                |                                | :grey_question: [RAK7249] (WisGate Edge Max)             |
|                |                                | :grey_question: [RAK7240] (WisGate Edge Prime)           |
| klkgw          | armv7-unknown-linux-musleabih  | :white_check_mark: Kerlink [Wirnet iFemtoCell Evolution] |
| dragino        | mips-unknown-linux-musl        | :white_check_mark: Dragino [LPS8]                        |
|                |                                | :grey_question: Dragino [DLOS8]                          |
| mtcdt          | armv5te-unknown-linux-musleabi | :white_check_mark: Multitech Conduit [MTCDT] (mLinux)    |

**Comment by PaulVMo** [comment]
I believe the next time there is a tagged release, all of the platforms included in the table will automatically be built. There just hasn't been a release since some of them were added.

**Comment by madninja** [comment]
That is correct.. we're working on getting routing updates (from "gateway service" miners) and router packet delivery over grpc working with all the related crypto that goes with it..

**Comment by madninja** [comment]
@philltran v1.0.0-alpha.4 was tagged and shows all available targets in the release list now. I'm going to close this.
