### ISSUE TITLE
dbus and jsonrpc interface with miner?

### ISSUE THREAD

**Issue by shawaj** [helium/gateway-rs#212]
On "full" miner we have ability to talk to miner container over dbus or jsonrpc - is this planned for gateway-rs as well?

In particular, for onboarding a gateway over bluetooth via the phone apps

**Comment by lthiery** [comment]
I believe the local HTTP server is there as a replacement

https://github.com/helium/gateway-rs/blob/main/src/api/server.rs

**Comment by shawaj** [comment]
@lthiery is there any docs on how to interact with this from another container in order to construct an add gateway transaction for example? looks like this is exposed on port 4467?

is there no plans to have a like-for-like replacement for the dbus based gateway-config setup that exists currently so that when full miners move to gateway-rs the gateway-config side does not need to be rewritten?

**Comment by madninja** [comment]
> @lthiery is there any docs on how to interact with this from another container in order to construct an add gateway transaction for example? looks like this is exposed on port 4467?
> 
> is there no plans to have a like-for-like replacement for the dbus based gateway-config setup that exists currently so that when full miners move to gateway-rs the gateway-config side does not need to be rewritten?

There are no plans to replace the dbus interface. You can access the running service using the [local service](https://github.com/helium/proto/blob/master/src/service/local.proto). 

We'll be adjusting the erlang gateway-config to use grpc to communicate with gateway-rs in stead of over dbus.

**Comment by shawaj** [comment]
Thanks for clarification @madninja 👌
