### ISSUE TITLE
helium_gateway key info - possible regression - used to work when server not running, now does not?

### ISSUE THREAD

**Issue by shawaj** [helium/gateway-rs#213]
The command 
```
/usr/bin/helium_gateway -c /etc/helium_gateway key info
```
Used to work fine when the gateway service was not running.

However, since alpha21 this has stopped working, and running this command gives:
```
ERRO service error Unable to connect to local server. Check that `helium_gateway` is running.
```

Running the server first with `helium_gateway server` fixes this, but this means that a key for a DIY / data-only unit can only be generated once the server is running - which seems like

Is this a regression? Or has some other change made this necessary?

**Comment by shawaj** [comment]
I guess it was this change in key.rs that made the change:

https://github.com/helium/gateway-rs/commit/70bfab4f98768d4356a34d05edc66c667776f9ea

was this needed in order to support ECC usage?

I wonder if it is possible to have it so that if in the settings.toml you have:

```
keypair = "/var/data/gateway_key.bin"
```
Or some other file based (non ECC) setup that it can read the keypair without the server running?

**Comment by madninja** [comment]
I'd rather not do this. It adds special case code with questionable benefit? Why would you want this?

**Comment by madninja** [comment]
I'm assuming you're ok with this approach. I'd rather not have special code for a not so special case
