### ISSUE TITLE
can mainnet / testnet be declared on a non-ECC based key?

### ISSUE THREAD

**Issue by shawaj** [helium/gateway-rs#216]
For ECC usage it is possible to add a mainnet / testnet query string:
```
keypair = "ecc://i2c-1:96?slot=0&network=mainnet"
```

is this possible on a file based keypair? For example:
```
keypair = "/etc/helium_gateway/gateway_key.bin?network=mainnet"
```

**Comment by lthiery** [comment]
Yes - the ECC key can be interpreted for either net

**Comment by shawaj** [comment]
@lthiery what I meant was - can a file based keypair (non ECC) be used on testnet / mainnet too? like in my second example?

**Comment by lthiery** [comment]
I believe the file based keys encode which net they are determined for, so a priori, no.

**Comment by madninja** [comment]
This is correct.. an ECC key can be interpreted in either network, a file based key can not
