### ISSUE TITLE
Problem with dragino no data mining

### ISSUE THREAD

**Issue by ginopowa** [helium/gateway-rs#221]
The issue: dragino is correct imposted but no data mining and packet is unconfirmed e not visible on helium explorer 

LOGREAD:
Thu Mar 17 09:38:36 2022 daemon.info fwd[3179]: ################[PKT_SERV] no report of this service ###############
Thu Mar 17 09:38:36 2022 daemon.info fwd[3179]: PKTUP~ [server] JSON: {"stat":{"time":"2022-03-17 08:38:36 UTC","rxnb":0,"rxok":0,"rxfw":0,"ackr":100.0,"dwnb":0,"txnb":0,"pfrm":"SX1308","mail":"dragino-20b84c@dragino.com","desc":"Dragino LoRaWAN Gateway"}}
Thu Mar 17 09:38:36 2022 daemon.info fwd[3179]: INFO~ [server-up] PUSH_ACK received in 4 ms
Thu Mar 17 09:38:36 2022 daemon.info fwd[3179]: PKTUP~ [server2] JSON: {"stat":{"time":"2022-03-17 08:38:36 UTC","rxnb":0,"rxok":0,"rxfw":0,"ackr":98.1,"dwnb":0,"txnb":0,"pfrm":"SX1308","mail":"dragino-20b84c@dragino.com","desc":"Dragino LoRaWAN Gateway"}}
Thu Mar 17 09:38:36 2022 daemon.info fwd[3179]: INFO~ [server2-up] PUSH_ACK received in 49 ms
Thu Mar 17 09:38:36 2022 daemon.info fwd[3179]: INFO~ [server2-down] PULL_ACK received in 51 ms
Thu Mar 17 09:38:38 2022 daemon.info fwd[3179]: INFO~ [server-down] PULL_ACK received in 0 ms
Thu Mar 17 09:38:41 2022 daemon.info fwd[3179]: INFO~ [server2-down] PULL_ACK received in 52 ms
Thu Mar 17 09:38:43 2022 daemon.info fwd[3179]: INFO~ [server-down] PULL_ACK received in 0 ms
Thu Mar 17 09:38:43 2022 user.notice iot_keep_alive: Internet Access OK: via wlan0-2
Thu Mar 17 09:38:43 2022 user.notice iot_keep_alive: use WAN or WiFi for internet access now
Thu Mar 17 09:38:44 2022 daemon.err uhttpd[1235]: wc: /tmp/logfile.log: No such file or directory
Thu Mar 17 09:38:44 2022 daemon.err uhttpd[1235]: sh: 2000000: unknown operand
Thu Mar 17 09:38:47 2022 daemon.info fwd[3179]: INFO~ [server2-down] PULL_ACK received in 51 ms
Thu Mar 17 09:38:47 2022 daemon.err uhttpd[1235]: wc: /tmp/logfile.log: No such file or directory
Thu Mar 17 09:38:47 2022 daemon.err uhttpd[1235]: sh: 2000000: unknown operand
Thu Mar 17 09:38:47 2022 daemon.err uhttpd[1235]: killall: logread: no process killed
Thu Mar 17 09:38:48 2022 daemon.info fwd[3179]: INFO~ [server-down] PULL_ACK received in 0 ms
Thu Mar 17 09:38:52 2022 daemon.info fwd[3179]: INFO~ [server2-down] PULL_ACK received in 51 ms
Thu Mar 17 09:38:53 2022 daemon.info fwd[3179]: INFO~ [server-down] PULL_ACK received in 0 ms

**Comment by IoTThinks** [comment]
Any LoRaWAN nodes are sending packets?

**Comment by ginopowa** [comment]
> Any LoRaWAN nodes are sending packets?
Yes, but they are unconfirmed

**Comment by madninja** [comment]
> Any LoRaWAN nodes are sending packets?
> Yes, but they are unconfirmed

your logs are not showing any `helium_gateway` entries

**Comment by ginopowa** [comment]
> your logs are not showing any `helium_gateway` entries
Thu Mar 17 15:05:15 2022 daemon.info helium_gateway[26091]:  INFO new packet forwarder client: A8:40:41:20:B8:4C:41:50, 127.0.0.1:45362, module: gateway
Thu Mar 17 15:05:15 2022 daemon.info fwd[25980]: INFO~ [server-down] PULL_ACK received in 0 ms
Thu Mar 17 15:05:15 2022 daemon.info fwd[25980]: INFO~ [server2] Starting semtech_push_down thread.
Thu Mar 17 15:05:15 2022 daemon.info fwd[25980]: INFO~ [server2] Starting semtech_push_up thread.
Thu Mar 17 15:05:15 2022 daemon.info fwd[25980]: INFO~ [server2-down] PULL_ACK received in 52 ms
Thu Mar 17 15:05:20 2022 daemon.info fwd[25980]: INFO~ [server-down] PULL_ACK received in 0 ms
Thu Mar 17 15:05:20 2022 daemon.info fwd[25980]: INFO~ [server2-down] PULL_ACK received in 51 ms
Thu Mar 17 15:05:21 2022 user.notice iot_keep_alive: Internet Access OK: via wlan0-2
Thu Mar 17 15:05:21 2022 user.notice iot_keep_alive: use WAN or WiFi for internet access now


> > Any LoRaWAN nodes are sending packets?
> > Yes, but they are unconfirmed
> 
> your logs are not showing any `helium_gateway` entries
Thu Mar 17 15:05:15 2022 daemon.info helium_gateway[26091]:  INFO new packet forwarder client: A8:40:41:20:B8:4C:41:50, 127.0.0.1:45362, module: gateway
Thu Mar 17 15:05:15 2022 daemon.info fwd[25980]: INFO~ [server-down] PULL_ACK received in 0 ms
Thu Mar 17 15:05:15 2022 daemon.info fwd[25980]: INFO~ [server2] Starting semtech_push_down thread.
Thu Mar 17 15:05:15 2022 daemon.info fwd[25980]: INFO~ [server2] Starting semtech_push_up thread.
Thu Mar 17 15:05:15 2022 daemon.info fwd[25980]: INFO~ [server2-down] PULL_ACK received in 52 ms
Thu Mar 17 15:05:20 2022 daemon.info fwd[25980]: INFO~ [server-down] PULL_ACK received in 0 ms
Thu Mar 17 15:05:20 2022 daemon.info fwd[25980]: INFO~ [server2-down] PULL_ACK received in 51 ms
Thu Mar 17 15:05:21 2022 user.notice iot_keep_alive: Internet Access OK: via wlan0-2
Thu Mar 17 15:05:21 2022 user.notice iot_keep_alive: use WAN or WiFi for internet access now

**Comment by madninja** [comment]
So I see one line there where the packet forwarder connects to gateway-rs but no packets are actually received at all from the packet forwarder. It looks like it is not receiving any packets from the underlying forwarder.

**Comment by ginopowa** [comment]
> So I see one line there where the packet forwarder connects to gateway-rs but no packets are actually received at all from the packet forwarder. It looks like it is not receiving any packets from the underlying forwarder
I correctly followed the guide on how to set it up, what should I do now, where to interact?

**Comment by madninja** [comment]
please check if you need a newer dragino firmware

**Comment by madninja** [comment]
We're not the dragino support folks. You'll have to check with them if that's the latest version or ask in the #gateway-development channel on discord, please

**Comment by ginopowa** [comment]
> We're not the dragino support folks. You'll have to check with them if that's the latest version or ask in the #gateway-development channel on discord, please
Fri Mar 18 20:14:50 2022 daemon.info helium_gateway[10432]:  INFO starting, listen: 127.0.0.1:1680, module: gateway
Fri Mar 18 20:14:50 2022 daemon.info helium_gateway[10432]:  INFO starting, region: EU868, module: dispatcher
Fri Mar 18 20:14:50 2022 daemon.info helium_gateway[10432]:  INFO default router, uri: http://54.176.88.149:8080/, pubkey: 1124CJ9yJaHq4D6ugyPCDnSBzQik61C1BqD9VMh1vsUmjwt16HNB, module: dispatcher
Fri Mar 18 20:14:50 2022 daemon.info helium_gateway[10432]:  INFO using gateway, uri: http://3.132.190.192:8080/, pubkey: 115PmCR6fpFihdjw626JXYdUEdzwjh66yoWzWkMvB9CRGEx1U6G, module: dispatcher
Fri Mar 18 20:14:50 2022 daemon.info helium_gateway[10432]:  INFO starting, module: updater
Fri Mar 18 20:14:50 2022 daemon.info helium_gateway[10432]:  INFO starting, listen: 127.0.0.1:4467, module: api
Fri Mar 18 20:14:51 2022 daemon.info helium_gateway[10432]:  INFO checking gateway, block_age: 215, pubkey: 115PmCR6fpFihdjw626JXYdUEdzwjh66yoWzWkMvB9CRGEx1U6G, module: dispatcher
Fri Mar 18 20:14:51 2022 daemon.info helium_gateway[10432]:  INFO updated region to EU868 at height 1271711, module: dispatcher
Fri Mar 18 20:14:51 2022 daemon.info fwd[10733]: INFO~ [server-down] PULL_ACK received in 60 ms
Fri Mar 18 20:14:51 2022 daemon.info helium_gateway[10432]:  INFO new packet forwarder client: A8:40:41:20:B8:4C:41:50, 127.0.0.1:58164, module: gateway
Fri Mar 18 20:14:51 2022 daemon.info helium_gateway[10432]:  INFO starting, oui: 21, uri: http://18.232.30.0:8080/, pubkey: 11So3oaJ8pGdvYFNQV15HZtwUZCDcmHsUH6nTFJD4CVCAqMiskP, module: router
Fri Mar 18 20:14:52 2022 daemon.info helium_gateway[10432]:  INFO starting, oui: 20, uri: http://43.154.117.143:8080/, pubkey: 11Z71QiBvLd8m2LFtgDpVwR86H3mpXsT93wbntF46LUsSxyqxCw, module: router
Fri Mar 18 20:14:52 2022 daemon.info helium_gateway[10432]:  INFO starting, oui: 19, uri: http://44.234.246.239:8080/, pubkey: 11HvwA1pKjzhDF9BvDDwopeNLrb3it6sNVXrtkq2DAdakVWvKSD, module: router
Fri Mar 18 20:14:52 2022 daemon.info helium_gateway[10432]:  INFO starting, oui: 16, uri: http://13.37.13.24:8080/, pubkey: 11afuQSrmk52mgxLu91AdtDXbJ9wmqWBUxC3hvjejoXkxEZfPvY, module: router
Fri Mar 18 20:14:52 2022 daemon.info helium_gateway[10432]:  INFO starting, oui: 15, uri: http://66.23.231.34:8080/, pubkey: 117FMcZy77Ehz6gbTtSdSEs38vF784NLkxmWXUPcA2Ze3QxwJhG, module: router
Fri Mar 18 20:14:52 2022 daemon.info helium_gateway[10432]:  INFO starting, oui: 12, uri: http://54.219.236.122:8080/, pubkey: 112ewJNEUfSg3Jvo276tMjzFC2JzmmZcJJ32CWz2fzYqbyCMMTe1, module: router
Fri Mar 18 20:14:52 2022 daemon.info helium_gateway[10432]:  INFO starting, oui: 10, uri: http://54.228.141.195:8080/, pubkey: 11YmZtwTPEuMSFGxze1x9TfDfGezN7vXevLu71iJe9FBbvNRAgk, module: router
Fri Mar 18 20:14:52 2022 daemon.info helium_gateway[10432]:  INFO starting, oui: 9, uri: http://44.238.156.97:8080/, pubkey: 11w77YQLhgUt8HUJrMtntGGr97RyXmot1ofs5Ct2ELTmbFoYsQa, module: router
Fri Mar 18 20:14:53 2022 daemon.info helium_gateway[10432]:  INFO starting, oui: 4, uri: http://54.193.165.228:8080/, pubkey: 11263KvqW3GZPAvag5sQYtBJSjb25azSTSwoi5Tza9kboaLRxcsv, module: router
Fri Mar 18 20:14:53 2022 daemon.info fwd[10733]: INFO~ [server2-down] PULL_ACK received in 48 ms
Fri Mar 18 20:14:53 2022 daemon.info helium_gateway[10432]:  INFO starting, oui: 2, uri: http://54.176.88.149:8080/, pubkey: 1124CJ9yJaHq4D6ugyPCDnSBzQik61C1BqD9VMh1vsUmjwt16HNB, module: router
Fri Mar 18 20:14:53 2022 daemon.info helium_gateway[10432]:  INFO updated routing to height 1271711, module: dispatcher
Fri Mar 18 20:14:53 2022 daemon.info helium_gateway[10432]:  INFO starting, oui: 1, uri: http://52.8.80.146:8080/, pubkey: 112qB3YaH5bZkCnKA5uRH7tBtGNv2Y5B4smv1jsmvGUzgKT71QpE, module: router
Fri Mar 18 20:14:55 2022 daemon.info helium_gateway[10432]:  INFO no update found, module: updater
Fri Mar 18 20:14:56 2022 daemon.info fwd[10733]: INFO~ [server-down] PULL_ACK received in 0 ms
Fri Mar 18 20:14:58 2022 daemon.info fwd[10733]: INFO~ [server2-down] PULL_ACK received in 48 ms
Fri Mar 18 20:15:00 2022 cron.info crond[1171]: USER root pid 10543 cmd /etc/init.d/DR_enable_rssh.sh start
Fri Mar 18 20:15:01 2022 daemon.info fwd[10733]: INFO~ [server-down] PULL_ACK received in 0 ms
Fri Mar 18 20:15:03 2022 daemon.info fwd[10733]: INFO~ [server2-down] PULL_ACK received in 49 ms
Fri Mar 18 20:15:03 2022 user.notice iot_keep_alive: Internet Access OK: via eth1
Fri Mar 18 20:15:03 2022 user.notice iot_keep_alive: use WAN or WiFi for internet access now

**Comment by madninja** [comment]
@ginopowa and what are you actually asking? THere's nothing in those logs to indicate any problems

**Comment by ginopowa** [comment]
> @ginopowa and what are you actually asking? THere's nothing in those logs to indicate any problems

the voice Fri Mar 18 20:15:03 2022 daemon.info fwd[10733]: INFO~ [server2-down] PULL_ACK received in 49 ms is normal ??

**Comment by madninja** [comment]
> > @ginopowa and what are you actually asking? THere's nothing in those logs to indicate any problems
> 
> the voice Fri Mar 18 20:15:03 2022 daemon.info fwd[10733]: INFO~ [server2-down] PULL_ACK received in 49 ms is normal ??

I believe this is standard lora packet forwarding logs

**Comment by ginopowa** [comment]
> I believe this is standard lora packet forwarding logs
is the gateway then communicating with the helium network on a regular basis?

**Comment by madninja** [comment]
> I believe this is standard lora packet forwarding logs
> is the gateway then communicating with the helium network on a regular basis?

1. I can't tell from the logs.. You need a device that is registered in console sending data to actually see packets flow. From the logs that gateway is connected to the helium network, but there is not enough information to see if you have packets flowing at all. 
2. How is this related to the actual bug that was filed here

**Comment by madninja** [comment]
If you're on testnet this may be a known issue right now. 

Otherwise I'm not sure what is going on with your setup.

**Comment by ginopowa** [comment]
> If you're on testnet this may be a known issue right now.
> 
> Otherwise I'm not sure what is going on with your setup.



What do you mean testnet? the firmware is updated to the latest version, while the LoRaWan network is currently set to the default address 127.0.0.1, I also checked the config.toml being EU868 and I set the custom band but it still doesn't goMany packets are not confirmed by the traffic gateway

**Comment by madninja** [comment]
I as omit confirming that you were in main net. 

When you say many packets are not confirmed is that _no_ packets are confirmed? Or some?

**Comment by ginopowa** [comment]
> I was confirming that you were on mainnet.
> 
> When you say many packets are not confirmed is that _no_ packets are confirmed? Or some?


03/25-02:47:54 | Data Unconfirmed Up | LoRa | 868.5 | SF12 BW125 | 25017 | Dev Addr: 0100DA30, Size: 52
-- | -- | -- | -- | -- | -- | --
  | 03/25-02:47:54 | Data Unconfirmed Up | LoRa | 868.5 | SF12 BW125 | 25017 | Dev Addr: 0100DA30, Size: 52
  | 03/25-01:45:10 |   | LoRa | 868.1 | SF12 BW125 | 6 |  
  | 03/25-01:28:01 | Data Unconfirmed Up | LoRa | 868.5 | SF12 BW125 | 64731 | Dev Addr: 0100DA30, Size: 52
  | 03/25-01:28:01 | Data Unconfirmed Up | LoRa | 868.5 | SF12 BW125 | 64731 | Dev Addr: 0100DA30, Size: 52
  | 03/25-01:18:45 | Data Unconfirmed Up | LoRa | 867.9 | SF12 BW125 | 54579 | Dev Addr: 0100DA30, Size: 52
  | 03/25-01:18:41 | Data Unconfirmed Up | LoRa | 867.9 | SF12 BW125 | 41969 | Dev Addr: 0100DA30, Size: 52
  | 03/25-00:51:06 | Data Confirmed Up | LoRa | 867.7 | SF12 BW125 | 1 | Dev Addr: 0768D4B7, Size: 14
  | 03/25-00:50:51 | Join Request | LoRa | 868.1 | SF12 BW125 | 0 | DevEui: 8CF957200001BF71,AppEUI: 70B3D57EF000004E
  | 03/25-00:49:29 | Data Unconfirmed Up | LoRa | 867.7 | SF12 BW125 | 6255 | Dev Addr: 0100DA30, Size: 52
  | 03/24-22:25:14 | Data Unconfirmed Up | LoRa | 867.9 | SF12 BW125 | 40649 | Dev Addr: 0100DA30, Size: 52
  | 03/24-22:23:14 | Data Unconfirmed Up | LoRa | 867.7 | SF12 BW125 | 46272 | Dev Addr: 0100DA30, Size: 52
  | 03/24-21:41:56 | Data Unconfirmed Up | LoRa | 868.5 | SF12 BW125 | 49982 | Dev Addr: 0100DA30, Size: 52
  | 03/24-21:41:56 | Data Unconfirmed Up | LoRa | 868.5 | SF12 BW125 | 49982 | Dev Addr: 0100DA30, Size: 52
  | 03/24-21:30:37 | Data Unconfirmed Up | LoRa | 867.3 | SF12 BW125 | 25247 | Dev Addr: 0100DA30, Size: 52
  | 03/24-21:30:37 | Data Unconfirmed Up | LoRa | 867.3 | SF12 BW125 | 25247 | Dev Addr: 0100DA30, Size: 52
  | 03/24-20:55:21 | Data Unconfirmed Up | LoRa | 868.5 | SF12 BW125 | 21411 | Dev Addr: 0100DA30, Size: 52
  | 03/24-20:55:21 | Data Unconfirmed Up | LoRa | 868.5 | SF12 BW125 | 21411 | Dev Addr: 0100DA30, Size: 52
  | 03/24-20:30:51 | Data Unconfirmed Up | LoRa | 867.9 | SF12 BW125 | 34680 | Dev Addr: 0100DA30, Size: 52
  | 03/24-20:12:10 | Data Unconfirmed Up | LoRa | 868.1 | SF12 BW125 | 738 | Dev Addr: 0100DA30, Size: 52
  | 03/24-19:21:16 | Data Unconfirmed Up | LoRa | 868.1 | SF12 BW125 | 46872 | Dev Addr: 0100DA30, Size: 52
  | 03/24-18:51:56 | Data Unconfirmed Up | LoRa | 867.3 | SF12 BW125 | 31302 | Dev Addr: 0100DA30, Size: 52
  | 03/24-18:51:56 | Data Unconfirmed Up | LoRa | 867.3 | SF12 BW125 | 31302 | Dev Addr: 0100DA30, Size: 52
  | 03/24-17:20:32 | Data Unconfirmed Up | LoRa | 867.9 | SF12 BW125 | 36634 | Dev Addr: 0100DA30, Size: 52

Couldn't the problem be the 3dbi LoRa antenna?

**Comment by IoTThinks** [comment]
Uplinks or downlinks can be confirmed or unconfirmed.

It is perfectly normal to have unconfirmed uplinks.
So the server doesn't need to send acknowledgement packet for each uplinks.

Generally, most of uplinks are unconfirmed to save bandwidth unless important packets.

> > I was confirming that you were on mainnet.
> 
> > 
> 
> > When you say many packets are not confirmed is that _no_ packets are confirmed? Or some?
> 
> 
> 
> 
> 
> 03/25-02:47:54 | Data Unconfirmed Up | LoRa | 868.5 | SF12 BW125 | 25017 | Dev Addr: 0100DA30, Size: 52
> 
> -- | -- | -- | -- | -- | -- | --
> 
>   | 03/25-02:47:54 | Data Unconfirmed Up | LoRa | 868.5 | SF12 BW125 | 25017 | Dev Addr: 0100DA30, Size: 52
> 
>   | 03/25-01:45:10 |   | LoRa | 868.1 | SF12 BW125 | 6 |  
> 
>   | 03/25-01:28:01 | Data Unconfirmed Up | LoRa | 868.5 | SF12 BW125 | 64731 | Dev Addr: 0100DA30, Size: 52
> 
>   | 03/25-01:28:01 | Data Unconfirmed Up | LoRa | 868.5 | SF12 BW125 | 64731 | Dev Addr: 0100DA30, Size: 52
> 
>   | 03/25-01:18:45 | Data Unconfirmed Up | LoRa | 867.9 | SF12 BW125 | 54579 | Dev Addr: 0100DA30, Size: 52
> 
>   | 03/25-01:18:41 | Data Unconfirmed Up | LoRa | 867.9 | SF12 BW125 | 41969 | Dev Addr: 0100DA30, Size: 52
> 
>   | 03/25-00:51:06 | Data Confirmed Up | LoRa | 867.7 | SF12 BW125 | 1 | Dev Addr: 0768D4B7, Size: 14
> 
>   | 03/25-00:50:51 | Join Request | LoRa | 868.1 | SF12 BW125 | 0 | DevEui: 8CF957200001BF71,AppEUI: 70B3D57EF000004E
> 
>   | 03/25-00:49:29 | Data Unconfirmed Up | LoRa | 867.7 | SF12 BW125 | 6255 | Dev Addr: 0100DA30, Size: 52
> 
>   | 03/24-22:25:14 | Data Unconfirmed Up | LoRa | 867.9 | SF12 BW125 | 40649 | Dev Addr: 0100DA30, Size: 52
> 
>   | 03/24-22:23:14 | Data Unconfirmed Up | LoRa | 867.7 | SF12 BW125 | 46272 | Dev Addr: 0100DA30, Size: 52
> 
>   | 03/24-21:41:56 | Data Unconfirmed Up | LoRa | 868.5 | SF12 BW125 | 49982 | Dev Addr: 0100DA30, Size: 52
> 
>   | 03/24-21:41:56 | Data Unconfirmed Up | LoRa | 868.5 | SF12 BW125 | 49982 | Dev Addr: 0100DA30, Size: 52
> 
>   | 03/24-21:30:37 | Data Unconfirmed Up | LoRa | 867.3 | SF12 BW125 | 25247 | Dev Addr: 0100DA30, Size: 52
> 
>   | 03/24-21:30:37 | Data Unconfirmed Up | LoRa | 867.3 | SF12 BW125 | 25247 | Dev Addr: 0100DA30, Size: 52
> 
>   | 03/24-20:55:21 | Data Unconfirmed Up | LoRa | 868.5 | SF12 BW125 | 21411 | Dev Addr: 0100DA30, Size: 52
> 
>   | 03/24-20:55:21 | Data Unconfirmed Up | LoRa | 868.5 | SF12 BW125 | 21411 | Dev Addr: 0100DA30, Size: 52
> 
>   | 03/24-20:30:51 | Data Unconfirmed Up | LoRa | 867.9 | SF12 BW125 | 34680 | Dev Addr: 0100DA30, Size: 52
> 
>   | 03/24-20:12:10 | Data Unconfirmed Up | LoRa | 868.1 | SF12 BW125 | 738 | Dev Addr: 0100DA30, Size: 52
> 
>   | 03/24-19:21:16 | Data Unconfirmed Up | LoRa | 868.1 | SF12 BW125 | 46872 | Dev Addr: 0100DA30, Size: 52
> 
>   | 03/24-18:51:56 | Data Unconfirmed Up | LoRa | 867.3 | SF12 BW125 | 31302 | Dev Addr: 0100DA30, Size: 52
> 
>   | 03/24-18:51:56 | Data Unconfirmed Up | LoRa | 867.3 | SF12 BW125 | 31302 | Dev Addr: 0100DA30, Size: 52
> 
>   | 03/24-17:20:32 | Data Unconfirmed Up | LoRa | 867.9 | SF12 BW125 | 36634 | Dev Addr: 0100DA30, Size: 52
> 
> 
> 
> Couldn't the problem be the 3dbi LoRa antenna?

**Comment by ginopowa** [comment]
> Uplinks or downlinks can be confirmed or unconfirmed.
> 
> It is perfectly normal to have unconfirmed uplinks. So the server doesn't need to send acknowledgement packet for each uplinks.
> 
> Generally, most of uplinks are unconfirmed to save bandwidth unless important packets.
> 
> This is the behavior of LoRaWAN.

Static ip is fondamental or no?

**Comment by IoTThinks** [comment]
No need static ip for data-only mining.
I updated to alpha 23. Still working OK.
Of course, I have a LoRaWAN node sending the LoRaWAN packet.
For the first ever join, need to wail for a few hours. Later joins are instant.

![image](https://user-images.githubusercontent.com/29994971/160266837-8ebcceb0-bed6-41f4-9f40-c89bb04b2a1c.png)

![image](https://user-images.githubusercontent.com/29994971/160266857-fab4f75b-0bc6-4bc3-9e9e-487b6ad1f68a.png)

![image](https://user-images.githubusercontent.com/29994971/160266890-b810ad8a-41cd-4acf-9c91-a4ca34bb3606.png)
