### ISSUE TITLE
Only lock the ECC when needed

### ISSUE THREAD

**Issue by mullerch** [helium/gateway-rs#235]
When using an ECC as a keypair provider, the access to the ECC device (e.g. through the i2c driver) is locked at the init and not released until the application is closed (and the system free its ressources).

As this application is a daemon, it should not lock the ECC over its whole lifecycle as it will prevent other applications to use it.

This is currently a dependency constraint, see [helium-crypto-rs#22](https://github.com/helium/helium-crypto-rs/issues/22) for details.

**Comment by shawaj** [comment]
This would be very useful for all authenticating with Google cloud iot etc

**Comment by madninja** [comment]
I'd happily take a PR here, but right now this is not a priority and somewhat fraught with issues at the rate a hotspot is using the ECC
