### ISSUE TITLE
Dragino LPS-8 WARN gateway region stream error: Service(Rpc(Status { code: Unknown, source: None })), module: dispatcher

### ISSUE THREAD

**Issue by ik7gxr** [helium/gateway-rs#244]
Gprep Helium gateway show many errors, any suggestion?

INFO starting, listen: 127.0.0.1:1680, module: gateway
Sun Jan  1 00:00:24 2012 daemon.info helium_gateway[1594]:  INFO starting, region: EU868, module: dispatcher
Sun Jan  1 00:00:24 2012 daemon.info helium_gateway[1594]:  INFO default router, uri: http://54.176.88.149:8080/, pubkey: 1124CJ9yJaHq4D6ugyPCDnSBzQik61C1BqD9VMh1vsUmjwt16HNB, module: dispatcher
Wed Apr 20 07:50:04 2022 daemon.info helium_gateway[1594]:  INFO using gateway, uri: http://3.38.70.101:8080/, pubkey: 11yJXQPG9deHqvw2ac6VWtNP7gZj8X3t3Qb3Gqm9j729p4AsdaA, module: dispatcher
Wed Apr 20 07:50:05 2022 daemon.info helium_gateway[1594]:  INFO starting, module: updater
Wed Apr 20 07:50:05 2022 daemon.info helium_gateway[1594]:  INFO starting, listen: 127.0.0.1:4467, module: api
Wed Apr 20 07:50:06 2022 daemon.info helium_gateway[1594]:  INFO new packet forwarder client: A8:40:41:1F:DD:EC:41:50, 127.0.0.1:48501, module: gateway
Wed Apr 20 07:50:07 2022 daemon.info helium_gateway[1594]:  INFO uplink @11131860 us, 868.50 MHz, Ok(DataRate(SF12, BW125)), snr: 3, rssi: -114, len: 23 from A8:40:41:1F:DD:EC:41:50, module: gateway
Wed Apr 20 07:50:07 2022 daemon.info helium_gateway[1594]:  WARN ignoring push_data: Decode(LoraWan(InvalidPacketType(7))), module: gateway
Wed Apr 20 07:50:07 2022 daemon.info helium_gateway[1594]:  WARN ignoring push_data: Decode(LoraWan(InvalidPacketSize(JoinRequest, 9))), module: gateway
Wed Apr 20 07:50:07 2022 daemon.info helium_gateway[1594]:  INFO using gateway, uri: http://52.49.199.40:8080/, pubkey: 11tk4zzbyfMPYYHYda255ACoqfYFVdrUSoCWrCYfn8BoyuYrERK, module: dispatcher
Wed Apr 20 07:50:09 2022 daemon.info helium_gateway[1594]:  WARN gateway region stream error: Service(Rpc(Status { code: Unknown, source: None })), module: dispatcher
Wed Apr 20 07:50:09 2022 daemon.info helium_gateway[1594]:  INFO selecting new gateway in 12s, module: dispatcher
Wed Apr 20 07:50:16 2022 daemon.info helium_gateway[1594]:  WARN ignoring push_data: Decode(LoraWan(InvalidPacketSize(JoinRequest, 9))), module: gateway
Wed Apr 20 07:50:17 2022 daemon.info helium_gateway[1594]:  INFO no update found, module: updater
Wed Apr 20 07:50:22 2022 daemon.info helium_gateway[1594]:  INFO using gateway, uri: http://35.84.173.125:8080/, pubkey: 11pUovhssQdXzrfcYMTUrNNTQossgny8WqhfdbprrAVFyHcmvAN, module: dispatcher
Wed Apr 20 07:50:23 2022 daemon.info helium_gateway[1594]:  WARN ignoring push_data: Decode(LoraWan(InvalidPacketSize(JoinRequest, 9))), module: gateway
Wed Apr 20 07:50:31 2022 daemon.info helium_gateway[1594]:  WARN ignoring push_data: Decode(LoraWan(InvalidPacketSize(JoinRequest, 9))), module: gateway
Wed Apr 20 07:50:36 2022 daemon.info helium_gateway[1594]:  INFO uplink @45123243 us, 868.30 MHz, Ok(DataRate(SF7, BW125)), snr: -7.5, rssi: -128, len: 23 from A8:40:41:1F:DD:EC:41:50, module: gateway
Wed Apr 20 07:50:36 2022 daemon.info helium_gateway[1594]:  INFO using gateway, uri: http://52.49.199.40:8080/, pubkey: 11tk4zzbyfMPYYHYda255ACoqfYFVdrUSoCWrCYfn8BoyuYrERK, module: dispatcher
Wed Apr 20 07:50:36 2022 daemon.info helium_gateway[1594]:  WARN gateway region stream error: Service(Rpc(Status { code: Unknown, source: None })), module: dispatcher
Wed Apr 20 07:50:36 2022 daemon.info helium_gateway[1594]:  INFO selecting new gateway in 17s, module: dispatcher
Wed Apr 20 07:50:36 2022 daemon.info helium_gateway[1594]:  WARN ignoring push_data: Decode(LoraWan(InvalidPacketSize(JoinRequest, 9))), module: gateway
Wed Apr 20 07:50:54 2022 daemon.info helium_gateway[1594]:  INFO using gateway, uri: http://3.132.190.192:8080/, pubkey: 115PmCR6fpFihdjw626JXYdUEdzwjh66yoWzWkMvB9CRGEx1U6G, module: dispatcher
Wed Apr 20 07:50:54 2022 daemon.info helium_gateway[1594]:  WARN gateway region stream error: Service(Rpc(Status { code: Unknown, source: None })), module: dispatcher
Wed Apr 20 07:50:54 2022 daemon.info helium_gateway[1594]:  INFO selecting new gateway in 38s, module: dispatcher
Wed Apr 20 07:51:08 2022 daemon.info helium_gateway[1594]:  WARN ignoring push_data: Decode(LoraWan(InvalidPacketSize(JoinRequest, 9))), module: gateway
Wed Apr 20 07:51:11 2022 daemon.info helium_gateway[1594]:  INFO uplink @80055379 us, 868.30 MHz, Ok(DataRate(SF7, BW125)), snr: -5.8, rssi: -124, len: 23 from A8:40:41:1F:DD:EC:41:50, module: gateway
Wed Apr 20 07:51:11 2022 daemon.info helium_gateway[1594]:  INFO using gateway, uri: http://52.49.199.40:8080/, pubkey: 11tk4zzbyfMPYYHYda255ACoqfYFVdrUSoCWrCYfn8BoyuYrERK, module: dispatcher
Wed Apr 20 07:51:11 2022 daemon.info helium_gateway[1594]:  WARN gateway region stream error: Service(Rpc(Status { code: Unknown, source: None })), module: dispatcher
Wed Apr 20 07:51:11 2022 daemon.info helium_gateway[1594]:  INFO selecting new gateway in 68s, module: dispatcher
Wed Apr 20 07:51:12 2022 daemon.info helium_gateway[1594]:  WARN ignoring push_data: Decode(LoraWan(InvalidPacketSize(JoinRequest, 9))), module: gateway
Wed Apr 20 07:51:14 2022 daemon.info helium_gateway[1594]:  WARN ignoring push_data: Decode(LoraWan(InvalidPacketSize(JoinRequest, 9))), module: gateway
Wed Apr 20 07:51:18 2022 daemon.info helium_gateway[1594]:  INFO uplink @87307971 us, 868.30 MHz, Ok(DataRate(SF7, BW125)), snr: -2.8, rssi: -122, len: 23 from A8:40:41:1F:DD:EC:41:50, module: gateway
Wed Apr 20 07:51:18 2022 daemon.info helium_gateway[1594]:  INFO using gateway, uri: http://3.38.70.101:8080/, pubkey: 11yJXQPG9deHqvw2ac6VWtNP7gZj8X3t3Qb3Gqm9j729p4AsdaA, module: dispatcher
Wed Apr 20 07:51:18 2022 daemon.info helium_gateway[1594]:  WARN gateway region stream error: Service(Rpc(Status { code: Unknown, source: None })), module: dispatcher
Wed Apr 20 07:51:18 2022 daemon.info helium_gateway[1594]:  INFO selecting new gateway in 188s, module: dispatcher
Wed Apr 20 07:51:24 2022 daemon.info helium_gateway[1594]:  INFO uplink @93125780 us, 868.50 MHz, Ok(DataRate(SF12, BW125)), snr: -5.2, rssi: -126, len: 23 from A8:40:41:1F:DD:EC:41:50, module: gateway
Wed Apr 20 07:51:24 2022 daemon.info helium_gateway[1594]:  INFO using gateway, uri: http://54.251.77.229:8080/, pubkey: 11Gx2yPEmBGUrbHUiUWQs9vV7JDHQLZSddQs6e3WB2uvqSMUDBW, module: dispatcher
Wed Apr 20 07:51:24 2022 daemon.info helium_gateway[1594]:  WARN gateway region stream error: Service(Rpc(Status { code: Unknown, source: None })), module: dispatcher
Wed Apr 20 07:51:24 2022 daemon.info helium_gateway[1594]:  INFO selecting new gateway in 396s, module: dispatcher
Wed Apr 20 07:51:26 2022 daemon.info helium_gateway[1594]:  INFO uplink @95536476 us, 868.30 MHz, Ok(DataRate(SF12, BW125)), snr: -13.8, rssi: -135, len: 23 from A8:40:41:1F:DD:EC:41:50, module: gateway
Wed Apr 20 07:51:26 2022 daemon.info helium_gateway[1594]:  INFO using gateway, uri: http://52.49.199.40:8080/, pubkey: 11tk4zzbyfMPYYHYda255ACoqfYFVdrUSoCWrCYfn8BoyuYrERK, module: dispatcher
Wed Apr 20 07:51:26 2022 daemon.info helium_gateway[1594]:  WARN gateway region stream error: Service(Rpc(Status { code: Unknown, source: None })), module: dispatcher
Wed Apr 20 07:51:26 2022 daemon.info helium_gateway[1594]:  INFO selecting new gateway in 588s, module: dispatcher
Wed Apr 20 07:51:28 2022 daemon.info helium_gateway[1594]:  INFO uplink @97335932 us, 868.10 MHz, Ok(DataRate(SF12, BW125)), snr: -13.5, rssi: -135, len: 23 from A8:40:41:1F:DD:EC:41:50, module: gateway
Wed Apr 20 07:51:28 2022 daemon.info helium_gateway[1594]:  INFO using gateway, uri: http://3.132.190.192:8080/, pubkey: 115PmCR6fpFihdjw626JXYdUEdzwjh66yoWzWkMvB9CRGEx1U6G, module: dispatcher
Wed Apr 20 07:51:28 2022 daemon.info helium_gateway[1594]:  WARN gateway region stream error: Service(Rpc(Status { code: Unknown, source: None })), module: dispatcher
Wed Apr 20 07:51:28 2022 daemon.info helium_gateway[1594]:  INFO selecting new gateway in 1228s, module: dispatcher
Wed Apr 20 07:51:38 2022 daemon.info helium_gateway[1594]:  INFO uplink @107185323 us, 868.30 MHz, Ok(DataRate(SF7, BW125)), snr: -7.2, rssi: -127, len: 23 from A8:40:41:1F:DD:EC:41:50, module: gateway
Wed Apr 20 07:51:38 2022 daemon.info helium_gateway[1594]:  INFO using gateway, uri: http://35.84.173.125:8080/, pubkey: 11pUovhssQdXzrfcYMTUrNNTQossgny8WqhfdbprrAVFyHcmvAN, module: dispatcher
Wed Apr 20 07:51:44 2022 daemon.info helium_gateway[1594]:  INFO uplink @113039324 us, 868.50 MHz, Ok(DataRate(SF12, BW125)), snr: -10.2, rssi: -130, len: 23 from A8:40:41:1F:DD:EC:41:50, module: gateway
Wed Apr 20 07:51:44 2022 daemon.info helium_gateway[1594]:  INFO using gateway, uri: http://35.84.173.125:8080/, pubkey: 11pUovhssQdXzrfcYMTUrNNTQossgny8WqhfdbprrAVFyHcmvAN, module: dispatcher
Wed Apr 20 07:51:46 2022 daemon.info helium_gateway[1594]:  INFO uplink @115373732 us, 868.10 MHz, Ok(DataRate(SF12, BW125)), snr: -17, rssi: -138, len: 23 from A8:40:41:1F:DD:EC:41:50, module: gateway
Wed Apr 20 07:51:46 2022 daemon.info helium_gateway[1594]:  INFO using gateway, uri: http://3.132.190.192:8080/, pubkey: 115PmCR6fpFihdjw626JXYdUEdzwjh66yoWzWkMvB9CRGEx1U6G, module: dispatcher
Wed Apr 20 07:51:46 2022 daemon.info helium_gateway[1594]:  WARN gateway region stream error: Service(Rpc(Status { code: Unknown, source: None })), module: dispatcher
Wed Apr 20 07:51:46 2022 daemon.info helium_gateway[1594]:  INFO selecting new gateway in 1800s, module: dispatcher
Wed Apr 20 07:51:48 2022 daemon.info helium_gateway[1594]:  WARN ignoring push_data: Decode(LoraWan(InvalidPacketSize(JoinRequest, 9))), module: gateway
Wed Apr 20 07:51:55 2022 daemon.info helium_gateway[1594]:  WARN ignoring push_data: Decode(LoraWan(InvalidPacketSize(JoinRequest, 9))), module: gateway
Wed Apr 20 07:51:57 2022 daemon.info helium_gateway[1594]:  INFO uplink @126743780 us, 868.50 MHz, Ok(DataRate(SF12, BW125)), snr: -12.5, rssi: -134, len: 23 from A8:40:41:1F:DD:EC:41:50, module: gateway
Wed Apr 20 07:51:57 2022 daemon.info helium_gateway[1594]:  INFO using gateway, uri: http://52.49.199.40:8080/, pubkey: 11tk4zzbyfMPYYHYda255ACoqfYFVdrUSoCWrCYfn8BoyuYrERK, module: dispatcher
Wed Apr 20 07:51:57 2022 daemon.info helium_gateway[1594]:  WARN gateway region stream error: Service(Rpc(Status { code: Unknown, source: None })), module: dispatcher
Wed Apr 20 07:51:57 2022 daemon.info helium_gateway[1594]:  INFO selecting new gateway in 1800s, module: dispatcher
Wed Apr 20 07:52:06 2022 daemon.info helium_gateway[1594]:  INFO uplink @135727100 us, 868.30 MHz, Ok(DataRate(SF12, BW125)), snr: -16, rssi: -136, len: 23 from A8:40:41:1F:DD:EC:41:50, module: gateway
Wed Apr 20 07:52:06 2022 daemon.info helium_gateway[1594]:  INFO using gateway, uri: http://3.38.70.101:8080/, pubkey: 11yJXQPG9deHqvw2ac6VWtNP7gZj8X3t3Qb3Gqm9j729p4AsdaA, module: dispatcher
Wed Apr 20 07:52:07 2022 daemon.info helium_gateway[1594]:  WARN gateway region stream error: Service(Rpc(Status { code: Unknown, source: None })), module: dispatcher
Wed Apr 20 07:52:07 2022 daemon.info helium_gateway[1594]:  INFO selecting new gateway in 1800s, module: dispatcher
Wed Apr 20 07:52:13 2022 daemon.info helium_gateway[1594]:  INFO uplink @142313164 us, 868.10 MHz, Ok(DataRate(SF12, BW125)), snr: 2.8, rssi: -115, len: 23 from A8:40:41:1F:DD:EC:41:50, module: gateway
Wed Apr 20 07:52:13 2022 daemon.info helium_gateway[1594]:  INFO using gateway, uri: http://52.49.199.40:8080/, pubkey: 11tk4zzbyfMPYYHYda255ACoqfYFVdrUSoCWrCYfn8BoyuYrERK, module: dispatcher
Wed Apr 20 07:52:15 2022 daemon.info helium_gateway[1594]:  INFO checking gateway, block_age: 377, pubkey: 11tk4zzbyfMPYYHYda255ACoqfYFVdrUSoCWrCYfn8BoyuYrERK, module: dispatcher
Wed Apr 20 07:52:15 2022 daemon.info helium_gateway[1594]:  WARN gateway region stream error: Service(Rpc(Status { code: Unknown, source: None })), module: dispatcher
Wed Apr 20 07:52:15 2022 daemon.info helium_gateway[1594]:  INFO selecting new gateway in 7s, module: dispatcher

**Comment by madninja** [comment]
That looks like a either a bad version of the dragino firmware _or_ the device(s) that are trying to join are doing so with very odd non lora join packets
