### ISSUE TITLE
My Data-only Hotspot is not connecting to the router

### ISSUE THREAD

**Issue by yaser7us** [helium/gateway-rs#251]
My Data-only hostspot is not connecting to the router.
This issue has been there since the last 8 days. The logs output as below:

May 18 13:52:45 raspberrypi helium_gateway[520]: seed gateway, module: dispatcher, uri: http://18.228.158.83:8080/, pubkey: 11WUPL9y8pUfQg8wYvyJWbqEjnN7AzVGVWwHD8hmFFsXdaE3yh6
May 18 13:52:56 raspberrypi helium_gateway[520]: gateway stream setup error: Service(Rpc(Status { code: Unavailable, message: "error trying to connect: deadline has elapsed", source: Some(tonic::transport::Error(Transport, hyper::Error(Connect, Custom { kind: TimedOut, error: Elapsed(()) }))) })) , module: dispatcher, uri: http://67.211.211.27:8080/, pubkey: 14pYgPdgB8pkLc86VfspCPzqmcqcbzoaDe9WkUTFMhTfjm5P6Bh
May 18 13:52:56 raspberrypi helium_gateway[520]: selecting new gateway in 30s, module: dispatcher
May 18 13:53:26 raspberrypi helium_gateway[520]: seed gateway, module: dispatcher, uri: http://52.30.1.39:8080/, pubkey: 112qiiykzk7kTrnxNwnzf2EUsG9qoFPHG4Mau5hNsok8dLGf8ufB
May 18 13:53:26 raspberrypi helium_gateway[520]: using gateway, module: dispatcher, uri: http://64.20.47.153:8080/, pubkey: 114EA7byPyKTM6eu2wUVzLEzQU6zakhPLaDfE1Y1eh4jgKzD6c2
May 18 13:53:26 raspberrypi helium_gateway[520]: checking gateway, module: dispatcher, block_age: 178, pubkey: 114EA7byPyKTM6eu2wUVzLEzQU6zakhPLaDfE1Y1eh4jgKzD6c2
May 18 13:53:26 raspberrypi helium_gateway[520]: gateway region stream error: CryptoError(Signature(signature::Error { source: None })), module: dispatcher
May 18 13:53:26 raspberrypi helium_gateway[520]: selecting new gateway in 7s, module: dispatcher
May 18 13:53:33 raspberrypi helium_gateway[520]: seed gateway, module: dispatcher, uri: http://3.38.70.101:8080/, pubkey: 11yJXQPG9deHqvw2ac6VWtNP7gZj8X3t3Qb3Gqm9j729p4AsdaA
May 18 13:53:34 raspberrypi helium_gateway[520]: using gateway, module: dispatcher, uri: http://65.108.194.231:8080/, pubkey: 11hfsCtRuv1h5kAGWUnoqNkzEJRHVEozy3b42TZpP32C93SHNRw
May 18 13:53:34 raspberrypi helium_gateway[520]: checking gateway, module: dispatcher, block_age: 113, pubkey: 11hfsCtRuv1h5kAGWUnoqNkzEJRHVEozy3b42TZpP32C93SHNRw
May 18 13:53:34 raspberrypi helium_gateway[520]: gateway region stream error: CryptoError(Signature(signature::Error { source: None })), module: dispatcher
May 18 13:53:34 raspberrypi helium_gateway[520]: selecting new gateway in 11s, module: dispatcher
May 18 13:53:45 raspberrypi helium_gateway[520]: uplink @109257388 us, 868.30 MHz, Ok(DataRate(SF12, BW125)), snr: 11, rssi: -17, len: 23 from DC:A6:32:29:68:24:FF:FF, module: gateway
May 18 13:53:45 raspberrypi helium_gateway[520]: seed gateway, module: dispatcher, uri: http://3.122.38.248:8080/, pubkey: 1123BGjiBwxdTHHjEuvF5mTQpHWwy9KP1JbgS8N4UKUa3Q2ya1W6
May 18 13:53:46 raspberrypi helium_gateway[520]: using gateway, module: dispatcher, uri: http://205.209.96.5:8080/, pubkey: 11TAZindz9HqrPEKp6QtEgL6PeuPnXqc5HyM7WHub6v8YpYWLLm
May 18 13:53:46 raspberrypi helium_gateway[520]: checking gateway, module: dispatcher, block_age: 125, pubkey: 11TAZindz9HqrPEKp6QtEgL6PeuPnXqc5HyM7WHub6v8YpYWLLm
May 18 13:53:46 raspberrypi helium_gateway[520]: gateway region stream error: CryptoError(Signature(signature::Error { source: None })), module: dispatcher
May 18 13:53:46 raspberrypi helium_gateway[520]: selecting new gateway in 12s, module: dispatcher
May 18 13:53:59 raspberrypi helium_gateway[520]: seed gateway, module: dispatcher, uri: http://18.228.115.118:8080/, pubkey: 11BL23u2PbpTjuCyHQ6n35xD5a1QyhyuepCJYrqLVgD3fFewkJ2
May 18 13:54:00 raspberrypi helium_gateway[520]: using gateway, module: dispatcher, uri: http://35.175.1.154:8080/, pubkey: 112c2L76rvjfTA4zkDHg3NHtA2BxX4SubymvutafD5BcLFZtb951
May 18 13:54:00 raspberrypi helium_gateway[520]: checking gateway, module: dispatcher, block_age: 139, pubkey: 112c2L76rvjfTA4zkDHg3NHtA2BxX4SubymvutafD5BcLFZtb951
May 18 13:54:00 raspberrypi helium_gateway[520]: gateway region stream error: CryptoError(Signature(signature::Error { source: None })), module: dispatcher
May 18 13:54:00 raspberrypi helium_gateway[520]: selecting new gateway in 10s, module: dispatcher
May 18 13:54:10 raspberrypi helium_gateway[520]: seed gateway, module: dispatcher, uri: http://3.24.161.210:8080/, pubkey: 112Go1gHKBNBjSJztRD1x9m4H9krFiawrU444VC6PbEiwmWvFAUu
May 18 13:54:11 raspberrypi helium_gateway[520]: using gateway, module: dispatcher, uri: http://66.45.234.22:8080/, pubkey: 112BwJiARprsoMGHM1k9v2tapuaunzPxhtUXQLswjyWkczUCza4X
May 18 13:54:11 raspberrypi helium_gateway[520]: gateway region stream error: CryptoError(Signature(signature::Error { source: None })), module: dispatcher
May 18 13:54:11 raspberrypi helium_gateway[520]: selecting new gateway in 24s, module: dispatcher
May 18 13:54:35 raspberrypi helium_gateway[520]: seed gateway, module: dispatcher, uri: http://18.228.158.83:8080/, pubkey: 11WUPL9y8pUfQg8wYvyJWbqEjnN7AzVGVWwHD8hmFFsXdaE3yh6
May 18 13:54:37 raspberrypi helium_gateway[520]: using gateway, module: dispatcher, uri: http://67.211.214.35:8080/, pubkey: 112HsLQ69GRX8KBNbHk918JZa3yeA7W9mYpGyR5VDaiYmNhtyo3U
May 18 13:54:37 raspberrypi helium_gateway[520]: gateway region stream error: CryptoError(Signature(signature::Error { source: None })), module: dispatcher
May 18 13:54:37 raspberrypi helium_gateway[520]: selecting new gateway in 36s, module: dispatcher
May 18 13:55:13 raspberrypi helium_gateway[520]: seed gateway, module: dispatcher, uri: http://44.229.159.157:8080/, pubkey: 11aZEJnSduAXG8r3r9vzw3QD5k1KWXUJSVc2SxmwxPBuNmMW6UY
May 18 13:55:13 raspberrypi helium_gateway[520]: using gateway, module: dispatcher, uri: http://64.20.47.201:8080/, pubkey: 11224J78ikUhywGMNoBpeT39EBobSua7wA2iQ2nBVL95b8UPPx8S
May 18 13:55:14 raspberrypi helium_gateway[520]: checking gateway, module: dispatcher, block_age: 130, pubkey: 11224J78ikUhywGMNoBpeT39EBobSua7wA2iQ2nBVL95b8UPPx8S
May 18 13:55:14 raspberrypi helium_gateway[520]: gateway region stream error: CryptoError(Signature(signature::Error { source: None })), module: dispatcher
May 18 13:55:14 raspberrypi helium_gateway[520]: selecting new gateway in 8s, module: dispatcher
May 18 13:55:22 raspberrypi helium_gateway[520]: seed gateway, module: dispatcher, uri: http://52.30.1.39:8080/, pubkey: 112qiiykzk7kTrnxNwnzf2EUsG9qoFPHG4Mau5hNsok8dLGf8ufB
May 18 13:55:23 raspberrypi helium_gateway[520]: using gateway, module: dispatcher, uri: http://18.222.123.239:8080/, pubkey: 11ndMHvJbXAA632W6Hr2eH7BBXzvoSfCQZBRWh39AssMXmAg56b
May 18 13:55:23 raspberrypi helium_gateway[520]: checking gateway, module: dispatcher, block_age: 140, pubkey: 11ndMHvJbXAA632W6Hr2eH7BBXzvoSfCQZBRWh39AssMXmAg56b
May 18 13:55:23 raspberrypi helium_gateway[520]: starting, oui: 28, uri: http://185.115.181.13:8080/, pubkey: 112F126Kaz36Awr9mCJ6NahVNcXmRtJ7Jrscf365eNmqPh4GhtzF, module: router
May 18 13:55:23 raspberrypi helium_gateway[520]: starting, oui: 27, uri: http://209.159.147.162:8080/, pubkey: 11HSuFufeg1dZiKs7TEfgt7KazrBhsTvqCXEJaE9tD4hj76WuXU, module: router
May 18 13:55:24 raspberrypi helium_gateway[520]: starting, oui: 25, uri: http://142.132.251.228:8080/, pubkey: 112kkCXnZmPCo1UonJLWRin29nS4Qcwn2J6J3ZcBLgTnWTqmRisx, module: router
May 18 13:55:24 raspberrypi helium_gateway[520]: starting, oui: 24, uri: http://52.215.172.41:8080/, pubkey: 112uGkZS27qEmDmaV97knnNiVUzPW8qCsuBN16STia2MwUra4BbV, module: router
May 18 13:55:24 raspberrypi helium_gateway[520]: starting, oui: 23, uri: http://54.94.95.1:8080/, pubkey: 11yPFswfF7jZrEbAGJvabuXobsRktjJXRYyb9wwXYtVk11kCuko, module: router
May 18 13:55:24 raspberrypi helium_gateway[520]: starting, oui: 21, uri: http://18.232.30.0:8080/, pubkey: 11So3oaJ8pGdvYFNQV15HZtwUZCDcmHsUH6nTFJD4CVCAqMiskP, module: router
May 18 13:55:24 raspberrypi helium_gateway[520]: starting, oui: 20, uri: http://43.154.117.143:8080/, pubkey: 11Z71QiBvLd8m2LFtgDpVwR86H3mpXsT93wbntF46LUsSxyqxCw, module: router
May 18 13:55:24 raspberrypi helium_gateway[520]: starting, oui: 19, uri: http://44.234.246.239:8080/, pubkey: 11HvwA1pKjzhDF9BvDDwopeNLrb3it6sNVXrtkq2DAdakVWvKSD, module: router
May 18 13:55:24 raspberrypi helium_gateway[520]: starting, oui: 16, uri: http://13.37.13.24:8080/, pubkey: 11afuQSrmk52mgxLu91AdtDXbJ9wmqWBUxC3hvjejoXkxEZfPvY, module: router
May 18 13:55:24 raspberrypi helium_gateway[520]: starting, oui: 15, uri: http://66.23.231.34:8080/, pubkey: 117FMcZy77Ehz6gbTtSdSEs38vF784NLkxmWXUPcA2Ze3QxwJhG, module: router
May 18 13:55:24 raspberrypi helium_gateway[520]: starting, oui: 12, uri: http://54.219.236.122:8080/, pubkey: 112ewJNEUfSg3Jvo276tMjzFC2JzmmZcJJ32CWz2fzYqbyCMMTe1, module: router
May 18 13:55:25 raspberrypi helium_gateway[520]: starting, oui: 10, uri: http://54.228.141.195:8080/, pubkey: 11YmZtwTPEuMSFGxze1x9TfDfGezN7vXevLu71iJe9FBbvNRAgk, module: router
May 18 13:55:25 raspberrypi helium_gateway[520]: starting, oui: 9, uri: http://44.238.156.97:8080/, pubkey: 11w77YQLhgUt8HUJrMtntGGr97RyXmot1ofs5Ct2ELTmbFoYsQa, module: router
May 18 13:55:25 raspberrypi helium_gateway[520]: starting, oui: 6, uri: http://185.34.141.81:8080/, pubkey: 11awcuSbVURPkXX3FbKC7KF6bgEPRZqqPzv1FTEYABMLttUr13E, module: router
May 18 13:55:25 raspberrypi helium_gateway[520]: starting, oui: 4, uri: http://54.193.165.228:8080/, pubkey: 11263KvqW3GZPAvag5sQYtBJSjb25azSTSwoi5Tza9kboaLRxcsv, module: router
May 18 13:55:25 raspberrypi helium_gateway[520]: starting, oui: 2, uri: http://54.176.88.149:8080/, pubkey: 1124CJ9yJaHq4D6ugyPCDnSBzQik61C1BqD9VMh1vsUmjwt16HNB, module: router
May 18 13:55:25 raspberrypi helium_gateway[520]: updated routing to height 1360107, module: dispatcher
May 18 13:55:25 raspberrypi helium_gateway[520]: gateway region stream error: CryptoError(Signature(signature::Error { source: None })), module: dispatcher
May 18 13:55:25 raspberrypi helium_gateway[520]: selecting new gateway in 12s, module: dispatcher
May 18 13:55:25 raspberrypi helium_gateway[520]: starting, oui: 1, uri: http://52.8.80.146:8080/, pubkey: 112qB3YaH5bZkCnKA5uRH7tBtGNv2Y5B4smv1jsmvGUzgKT71QpE, module: router
May 18 13:55:25 raspberrypi helium_gateway[520]: gateway changed, shutting down, oui: 1, uri: http://52.8.80.146:8080/, pubkey: 112qB3YaH5bZkCnKA5uRH7tBtGNv2Y5B4smv1jsmvGUzgKT71QpE, module: router
May 18 13:55:25 raspberrypi helium_gateway[520]: gateway changed, shutting down, oui: 28, uri: http://185.115.181.13:8080/, pubkey: 112F126Kaz36Awr9mCJ6NahVNcXmRtJ7Jrscf365eNmqPh4GhtzF, module: router
May 18 13:55:25 raspberrypi helium_gateway[520]: gateway changed, shutting down, oui: 12, uri: http://54.219.236.122:8080/, pubkey: 112ewJNEUfSg3Jvo276tMjzFC2JzmmZcJJ32CWz2fzYqbyCMMTe1, module: router
May 18 13:55:25 raspberrypi helium_gateway[520]: gateway changed, shutting down, oui: 21, uri: http://18.232.30.0:8080/, pubkey: 11So3oaJ8pGdvYFNQV15HZtwUZCDcmHsUH6nTFJD4CVCAqMiskP, module: router
May 18 13:55:25 raspberrypi helium_gateway[520]: gateway changed, shutting down, oui: 23, uri: http://54.94.95.1:8080/, pubkey: 11yPFswfF7jZrEbAGJvabuXobsRktjJXRYyb9wwXYtVk11kCuko, module: router
May 18 13:55:25 raspberrypi helium_gateway[520]: gateway changed, shutting down, oui: 15, uri: http://66.23.231.34:8080/, pubkey: 117FMcZy77Ehz6gbTtSdSEs38vF784NLkxmWXUPcA2Ze3QxwJhG, module: router
May 18 13:55:25 raspberrypi helium_gateway[520]: gateway changed, shutting down, oui: 27, uri: http://209.159.147.162:8080/, pubkey: 11HSuFufeg1dZiKs7TEfgt7KazrBhsTvqCXEJaE9tD4hj76WuXU, module: router
May 18 13:55:25 raspberrypi helium_gateway[520]: gateway changed, shutting down, oui: 9, uri: http://44.238.156.97:8080/, pubkey: 11w77YQLhgUt8HUJrMtntGGr97RyXmot1ofs5Ct2ELTmbFoYsQa, module: router
May 18 13:55:25 raspberrypi helium_gateway[520]: gateway changed, shutting down, oui: 24, uri: http://52.215.172.41:8080/, pubkey: 112uGkZS27qEmDmaV97knnNiVUzPW8qCsuBN16STia2MwUra4BbV, module: router
May 18 13:55:25 raspberrypi helium_gateway[520]: gateway changed, shutting down, oui: 20, uri: http://43.154.117.143:8080/, pubkey: 11Z71QiBvLd8m2LFtgDpVwR86H3mpXsT93wbntF46LUsSxyqxCw, module: router
May 18 13:55:25 raspberrypi helium_gateway[520]: gateway changed, shutting down, oui: 19, uri: http://44.234.246.239:8080/, pubkey: 11HvwA1pKjzhDF9BvDDwopeNLrb3it6sNVXrtkq2DAdakVWvKSD, module: router
May 18 13:55:25 raspberrypi helium_gateway[520]: gateway changed, shutting down, oui: 16, uri: http://13.37.13.24:8080/, pubkey: 11afuQSrmk52mgxLu91AdtDXbJ9wmqWBUxC3hvjejoXkxEZfPvY, module: router
May 18 13:55:25 raspberrypi helium_gateway[520]: gateway changed, shutting down, oui: 6, uri: http://185.34.141.81:8080/, pubkey: 11awcuSbVURPkXX3FbKC7KF6bgEPRZqqPzv1FTEYABMLttUr13E, module: router
May 18 13:55:25 raspberrypi helium_gateway[520]: gateway changed, shutting down, oui: 10, uri: http://54.228.141.195:8080/, pubkey: 11YmZtwTPEuMSFGxze1x9TfDfGezN7vXevLu71iJe9FBbvNRAgk, module: router
May 18 13:55:25 raspberrypi helium_gateway[520]: gateway changed, shutting down, oui: 4, uri: http://54.193.165.228:8080/, pubkey: 11263KvqW3GZPAvag5sQYtBJSjb25azSTSwoi5Tza9kboaLRxcsv, module: router
May 18 13:55:25 raspberrypi helium_gateway[520]: gateway changed, shutting down, oui: 2, uri: http://54.176.88.149:8080/, pubkey: 1124CJ9yJaHq4D6ugyPCDnSBzQik61C1BqD9VMh1vsUmjwt16HNB, module: router
May 18 13:55:25 raspberrypi helium_gateway[520]: gateway changed, shutting down, oui: 25, uri: http://142.132.251.228:8080/, pubkey: 112kkCXnZmPCo1UonJLWRin29nS4Qcwn2J6J3ZcBLgTnWTqmRisx, module: router
May 18 13:55:38 raspberrypi helium_gateway[520]: seed gateway, module: dispatcher, uri: http://3.131.232.233:8080/, pubkey: 112hyDbnmq41LwyNynmSkcjoH414oEdANHiYduFygbLbJWBoLjsZ
May 18 13:55:39 raspberrypi helium_gateway[520]: using gateway, module: dispatcher, uri: http://216.158.239.163:8080/, pubkey: 112u31SPjxENtJFNWz8zvCj9BYCzMBG6zYQtYvjigy141xQuJmsU
May 18 13:55:40 raspberrypi helium_gateway[520]: checking gateway, module: dispatcher, block_age: 87, pubkey: 112u31SPjxENtJFNWz8zvCj9BYCzMBG6zYQtYvjigy141xQuJmsU
May 18 13:55:40 raspberrypi helium_gateway[520]: gateway region stream error: CryptoError(Signature(signature::Error { source: None })), module: dispatcher
May 18 13:55:40 raspberrypi helium_gateway[520]: selecting new gateway in 7s, module: dispatcher
May 18 13:55:47 raspberrypi helium_gateway[520]: seed gateway, module: dispatcher, uri: http://35.82.239.134:8080/, pubkey: 112LdZBP1vtz3gdhVPRuQYGx1fLuBP5nqFWcE4L1dYXdNiMJRdF6
May 18 13:55:48 raspberrypi helium_gateway[520]: using gateway, module: dispatcher, uri: http://64.44.100.120:8080/, pubkey: 14nBo8b1MBMyUF3ibJxJyToBVaNvNFKmBXKn6SunfQQpisYhvR5
May 18 13:55:48 raspberrypi helium_gateway[520]: gateway region stream error: CryptoError(Signature(signature::Error { source: Some(Verification equation was not satisfied) })), module: dispatcher
May 18 13:55:48 raspberrypi helium_gateway[520]: selecting new gateway in 16s, module: dispatcher

**Comment by yaser7us** [comment]
By the way, I already updated the frimware to alpha24 but that didn't change anything.

**Comment by madninja** [comment]
This was fixed in alpha.25.
