### ISSUE TITLE
Decouple Router Client from Validator Sync

### ISSUE THREAD

**Issue by lthiery** [helium/gateway-rs#253]
To be robust against delayed validators, helium_gateway considers block age when connecting to validators. When the block is very old, we assume the validator must be lagging, and we jump to another validator. However, when a chain stall occurs, we hop around validators with exponential back off.

Unfortunately, this appears to disable router_client entirely. However, we should be able to continue passing packets until the router denies us from the state channel entirely. In other words, having a "stale block" from validators should not immediately disable router_client.

**Comment by madninja** [comment]
Fixed in alpha.27
