### ISSUE TITLE
Gateway resets region even when specified

### ISSUE THREAD

**Issue by bsodmike** [helium/gateway-rs#264]
Hi,

I noticed that even though I have the region specified in my settings.toml, when the gateway service is restarted it will fetch its "region" based on its location. 

```
root@RAK7268C:/etc/helium_gateway# helium_gateway info
{
  "fw": "ramips_24kec-1.0.0-alpha.27",
  "region": "AS923_1",
```

Settings toml
```
root@RAK7268C:/etc/helium_gateway# cat settings.toml
listen = "0.0.0.0:1680"
region = "EU868"

[log]
method = "stdio"
level = "info"
timestamp = false

[update]
platform = "ramips_24kec"
```

You can see how it overrides this here:

```
Sat Jun 18 08:24:12 2022 daemon.info helium_gateway[22936]:  INFO starting, module: updater
Sat Jun 18 08:24:12 2022 daemon.info helium_gateway[22936]:  INFO starting, listen: 127.0.0.1:4467, module: api
Sat Jun 18 08:24:12 2022 daemon.info helium_gateway[22936]:  INFO new packet forwarder client: AC:1F:09:FF:FE:06:14:FA, 127.0.0.1:59021, module: g
ateway
Sat Jun 18 08:24:13 2022 daemon.info helium_gateway[22936]:  INFO using gateway, uri: http://205.209.96.147:8080/, pubkey: 11qcKRFmJuPEnxcgWoP7Yvk
zKr1dCrp1M9MCBjaCQGmgexKtcCZ, module: dispatcher
Sat Jun 18 08:24:15 2022 daemon.info helium_gateway[22936]:  INFO checking gateway, block_age: 574, pubkey: 11qcKRFmJuPEnxcgWoP7YvkzKr1dCrp1M9MCBj
aCQGmgexKtcCZ, module: dispatcher
Sat Jun 18 08:24:15 2022 kern.info quectel-CM[21119]: requestRegistrationState2 MCC: 413, MNC: 8, PS: Detached, DataCap: UNKNOW
Sat Jun 18 08:24:15 2022 kern.info quectel-CM[21119]: Dail Failed 3
Sat Jun 18 08:24:15 2022 daemon.info helium_gateway[22936]:  INFO updated region to AS923_1 at height 1402113, module: dispatcher
```

**Comment by IoTThinks** [comment]
By right, the region in location_assert should override the region in setting.toml

https://github.com/helium/gateway-rs/releases
[Release v1.0.0-alpha.22](https://github.com/helium/gateway-rs/releases/tag/v1.0.0-alpha.22)
Adds chain-based region following Previously the region specified in default.toml or settings.toml would set the region used in packets sent to routers. This is now considered the default region if no region is set on chain (i.e. no location is asserted). When a location is asserted, the region change will be automatically detected and applied to future packets being offered to routers

**Comment by bsodmike** [comment]
@IoTThinks I'm running some testing with hardware in a different zone and just want to test connectivity over a different frequency band. If you check my PR I've left this enabled by default.

**Comment by madninja** [comment]
Im

> @IoTThinks I'm running some testing with hardware in a different zone and just want to test connectivity over a different frequency band. If you check my PR I've left this enabled by default.

Then why not assert it in the region you want it in?

**Comment by jmarcelino** [comment]
> @IoTThinks I'm running some testing with hardware in a different zone and just want to test connectivity over a different frequency band. If you check my PR I've left this enabled by default.

Blockchain should be the source of truth for the region, there have been problems in the past caused by vendors and users overriding these settings leading to much confusion. 

If you need a different location for testing simply reassert at a different location

**Comment by IoTThinks** [comment]
> @IoTThinks I'm running some testing with hardware in a different zone and just want to test connectivity over a different frequency band. If you check my PR I've left this enabled by default.

I understand your need.
However, I believe once we assert the location, the region of the location will override all toml settings.
That is what the Readme says.

Wonder if we can remove the assert location so the region in toml setting works?

**Comment by madninja** [comment]
> @bsodmike I understand your need. However, I believe once we assert the location, the region of the location will override all toml settings. That is what the Readme says.
> 
> Wonder if we can remove the assert location so the region in toml setting works?

You can’t “remove” assert locations as they are on chain. The region in settings is only used temporarily while no assert location is active or hasn’t been received yet. Also see above as to why..

**Comment by madninja** [comment]
> @bsodmike I understand your need. However, I believe once we assert the location, the region of the location will override all toml settings. That is what the Readme says.
> 
> Wonder if we can remove the assert location so the region in toml setting works?

You can’t “remove” assert locations as they are on chain. The region in settings is only used temporarily while no assert location is active or hasn’t been received yet. Also see above as to why..

**Comment by bsodmike** [comment]
Got it thanks. Yes, I understand the normal process for hotspot assertions is via the mobile app, this uses the GPS data and prevents “spoofing” the location by adding this to the chain. That makes sense, thanks! :)
