### ISSUE TITLE
 Permission error installing on a mtcdt

### ISSUE THREAD

**Issue by neosmokecrypt** [helium/gateway-rs#268]
Hello I'm not a linux Guru, but if i install the ipk on a multitech conduit i get this error:

admin@mtcdt:/tmp$ sudo opkg install helium-gateway-v1.0.0-alpha.28-mtcdt.ipk
Installing helium_gateway (1.0.0) on root
/bin/sh: /tmp/opkg-Tf9NdB/helium_gateway-FjGIBC/preinst: Permission denied
To remove package debris, try `opkg remove helium_gateway`.
To re-attempt the install, try `opkg install helium_gateway`.
Collected errors:
 * pkg_run_script: package "helium_gateway" preinst script returned status 126.
 * preinst_configure: Aborting installation of helium_gateway.

I tried to install it with su -i and without sudo

admin@mtcdt:/tmp$ opkg install helium-gateway-v1.0.0-alpha.28-mtcdt.ipk
Installing helium_gateway (1.0.0) on root
/bin/sh: /tmp/opkg-n79fw3/helium_gateway-6AFJS1/preinst: Permission denied
To remove package debris, try `opkg remove helium_gateway`.
To re-attempt the install, try `opkg install helium_gateway`.
Collected errors:
 * pkg_run_script: package "helium_gateway" preinst script returned status 126.
 * preinst_configure: Aborting installation of helium_gateway.
 * opkg_conf_write_status_files: Can't open status file ///var/lib/opkg/status: Permission denied.

Can someone help?

Tnx!

**Comment by madninja** [comment]
did you manage to get this resolved? Most of the target builds here are made for and supported best effort by the community. The best place to ask for support for your target is on discord in gateway-development if you still need it. 

If you've managed to solve it, please leave a note here for future reference!
