### ISSUE TITLE
Newly added LoRa end-devices cannot join until gateway power-cycled

### ISSUE THREAD

**Issue by Codepoint1** [helium/gateway-rs#275]
**Describe the bug**
Appears that gateways are not receiving Console XOR update information allowing new LoRa end-devices to join.  Simply power-cycling the gateway fixes the issue.

**To Reproduce**
Add new device via Console, wait until "pending" status is removed.  Test end-device to find that it cannot join on any gateways even after > 1 day (24 hours).  Power cycle gateway to work-around and device then joins and operates properly within several minutes.   Codepoint has duplicated the behavior in both California and Washington locations.

**Expected behavior**
Devices should be able to join shortly after "pending" status is removed in the console and XOR data is published to gateways.

**Device Info (please complete the following information):**
 - Production VIP Console
 - c0d66199-c149-4633-abaa-fbc5a8602ed5
 - D88B4C3403B000A7 / D88B4C3403B00000
 - Depends on device mode, but after join minimum 1 uplink is always sent.
 - US915 SB2
 - Duplicated 7/25 via Pet Eggshell Bison.  Behavior first reported 7/21 on Stable Vinyl Chicken.  Both are Bobcat-300 miners.  Pet Eggshell Bison is running  firmware "ota_version": "1.0.3.2"

**Additional context**
This is readily duplicated on our end...not sure if it's a Bobcat miner specific issue or a XOR distribution issue or a Codepoint-console specific issue.  Stable Vinyl Chicken is in a dense-coverage area and it seems that other gateways also did not accept joins over long periods of time.  Please reach out if you need any help setting up a duplication scenario, and apologies if this is in the wrong project-bucket.

**Screenshots**

**Comment by macpie** [comment]
This seems like a gateway rs issue transferring

**Comment by madninja** [comment]
Can @andymck take a look? The gateway code is quite simple here so it’s somewhere between the server handler and the client

**Comment by Codepoint1** [comment]
Repro 7/26 @ 8:35am, left this device on >14 hours...no join.  Power-cycled gateway (Bobcat-300) and device reported joining in console within 3 minutes.

Console Device ID:  140fb708-451b-4a62-8f35-7b968788054c
DevEUI:  D88B4C3403B00084
APP EUI: D88B4C3403B00000

**Comment by Codepoint1** [comment]
So, had a theory that this a codepoint VIP-console specific issue, but not sure this test shows that to be the case.

Fired up a regular console instance @ console.helium.com and added a new device:

Console Device ID: e518e6fd-4157-40d8-b0ec-9b5892e923fa
DevEUI: D88B4C3403B00086
AppEui: D88B4C3403B00000

Waited for device to not be pending, and same behavior...doesn't join, until gateway is power cycled + 2 minutes.  Hope this helps.

**Comment by Codepoint1** [comment]
Traveled out of the area with a device that had not yet joined.  It joined immediately when powered on oblong-brunette-pike (also a Bobcat-300).

Device Console id: b0adb522-c535-4739-b3e3-99264bc2d3f8
DevEUI: D88B4C3403B00095

**Comment by madninja** [comment]
Fixed with #280

**Comment by jdgemm** [comment]
@Codepoint1 a new hotspot firmware (2022.08.02.0) was released yesterday along with a fix to this issue. Once your hotspot firmware is updated, please check to see if it resolves your issue.

**Comment by Codepoint1** [comment]
> @Codepoint1 a new hotspot firmware (2022.08.02.0) was released yesterday along with a fix to this issue. Once your hotspot firmware is updated, please check to see if it resolves your issue.

Yep...looks fixed 8/4 3:08 UST on adding a brand new device.   Thank you all for your efforts!

**Comment by Codepoint1** [comment]
This similar behavior is back.  Added several new devices on 8/11, waited over 40 minutes after console pending xor icon removed and no connectivity on my local gateway (but occasional join requests observed on out of range gateways).  Power cycled my gateway and devices joined within several minutes.  Pet Eggshell Bison firmware still same 1.0.3.3

Device A:
Console Device ID: 	1cb5bc17-147e-4bac-8502-b5927163548b
DevEUI: B4607750900001BC

Device B:
Console Device ID:  aeebefe5-0904-4c5e-ae99-89d4c2694d82
B460775080000A70

**Comment by Codepoint1** [comment]
> @Codepoint1 are you still seeing this?

No, haven't been able to duplicate it, nor reported at the other locations.  Seems like it was a spurious issue.  Closing issue.

**Comment by Codepoint1** [comment]
This same behavior has started occurring again at several locations, requiring a gateway power-cycle to allow recently added devices to join.  We are attempting to solicit the firmware versions of the gateways, but do not have physical access to them and out of-office conflicts, etc.

**Scenario #1**:  On Tuesday 9/4 added 4 new devices to Codepoint Console, after pending status was removed (~10 minutes) device could not join or show any console activity.  Reset Gateway, waited 10 minutes...devices still would not join.  Reset Gateway a 2nd time and all devices joined within 1 minute.

Gateway:  Rough Olive Pangolin Bobcat-300 (fw version unknown, but potentially was 1.0.3.4)
Device DevEUI:  B4607750800009E0, B460775080000AF0, B4607750900002A1, B4607750900009D4
Device ID:  4146b5e7-7e90-4886-9a03-24fb7c957c61, 4a1d0861-4f9a-4c67-a020-eae01ec082e4, d8d61fc1-062c-4336-ae60-a35e7a69fda1, 3297882e-aabf-4be2-a171-c87fbed0f9eb

**Scenario #2**:  Customer using FreedomFi Gateway had added device, and it would not join for >12 hours.  Customer has adjacent RAK gateways nearby.  Customer power-cycled FreedomFi gateway and device joined within several minutes.

Gateway:  swift brunette swallow  FreedomFi  (fw version unknown)
Device DevEUI: ?
Device ID:

**Scenario #3**:  Customer in Portland area also reporting issues adding new devices on 9/8.  Possibly using newly deployed gateway.  Will update with details as possible....

**Comment by Codepoint1** [comment]
Update 9/13 -> 9/14:  Was able to reproduce issues in local Washington State environment with pet-eggshell-bison, which is the sole local Helium gateway.  All other gateways are distant and usually cannot achieve reliable bidirectional communication with devices.

**Gateway/Device Info:** --  pet-eggshell-bison  Bobcat-300, "ota_version": "1.0.3.6".  Gateway log dumps available before/after power cycle.  
Device DevEUI: D88B4C3403B00155
Console Device ID: 8bc48d05-8b6c-47b5-b1ae-2abf7750d712


**Scenario:**  
-Added a new device 9/13 in the evening.
-Console removed XOR "pending" tag ~ 10 minutes later.
-Rapidly observed join requests on outlying gateways, such as bumpy-taffy-loris and witty-latte-cougar, however even after 3 hours no join requests were received by local pet-eggshell-bison.
-Left device overnight.
-9/14 In the morning the device had managed to join via bumpy-taffy-loris, **however device uplinks were received by the local pet-eggshell-bison!!**
-Reset device, to force rejoin.  Device again went into pattern of only attempting joins on outlying gateways for ~ 60 minutes.
-SOFT-REBOOTED pet-eggshell-bison
-Device was immediately able to Join and send uplinks through local gateway as expected.

**Comments:** Appears there is the same classic power-cycle behavior as originally reported and fixed prior.  However, in the current-state, the new symptom of joining on a remote gateway but sending uplinks on the local-gateway without being able to join via that gateway is new. 

In addition, this is anecdotal, however failed to reproduce this issue last week locally when we had  customer reports #1/#2/#3....however my local gateway pet-eggshell-bison had recently been hard power cycled (within 2 hours).  In this case, all testing was done with the gateway being up for ~6 days.

Please contact if the bobcat-log dumps are useful for debugging.  

Screen shot showing Join on bumpy-taffy-loris, but uplink on pet-eggshell-bison:
![image](https://user-images.githubusercontent.com/101138403/190207977-3a7528fb-f4f2-45f4-bbe6-adcb12c2dcbb.png)

**Comment by lytzV** [comment]
Hi, joining through gateway A and uplink through gateway B is normal. A device session is not attached to a gateway but to the LNS, so whichever gateway that delivers the message first will be used for the transmission.

**Comment by Codepoint1** [comment]
> Hi, joining through gateway A and uplink through gateway B is normal. A device session is not attached to a gateway but to the LNS, so whichever gateway that delivers the message first will be used for the transmission.

Sounds good, thanks.  Wasn't 100% clear on the XOR filter use (join-only vs all uplinks) in the gateway, since XOR mechanism is unique to Helium.  Assuming XOR filter is only used for Join Request then.

**Comment by Codepoint1** [comment]
Unable to duplicate, this morning.  There may be a dependency on gateway up-time based on my own results since last week.  Will continue trying to reproduce at least twice a day in local environment here.

**Comment by Codepoint1** [comment]
Another repro, that initiated/observed live on a call with Victor @ Nova around 9am PST 9/21.

**Gateway/Device Info:** -- pet-eggshell-bison Bobcat-300, "ota_version": "1.0.3.7". Gateway log dumps attached.
Device DevEUI: D88B4C3403B0015C
Console Device ID: 9457e046-8920-43d4-bec4-e5f404ebd448

**Scenario:**
-Device info was added to the console around 8:50 am
-Device itself was taken out of factory-hibernate/reset state which initiates its standard Join Schedule (join attempt interval increases over time).
-@~9:15 While on call, the pending/status was observed removed in the console
-@9:21 a join attempt on outlying gateway basic-ceramic-lion was observed.  
-@9:24 1st bobcat log pulled
-Everything left static to observe.  7 additional Join Attempts were observed on basic-ceramic-lion over this time.
-@11:11 Gateway soft-booted, 2nd log (post-reboot) pulled.
-@11:33 Subsequent Join Attempt on local pet-eggshell-bison gateway, however device did not receive join.
-@12:03 Next (2nd) Join attempt on local pet-egg-shell-bison gateway, again device did not receive response.
-@12:34 Next (3rd) Join attempt on local pet-eggshell-bison gateway successful, device then uplinks as normal.
-@12:38 3rd bobcat log pulled.

[pet-eggshell-bison bobcat logs 9_21_2022 repro.zip](https://github.com/helium/gateway-rs/files/9620092/pet-eggshell-bison.bobcat.logs.9_21_2022.repro.zip)

---------
In between this report and the prior duplication ~7 days ago, there had been another local repro at my location on 9/20, however in that case I also reset the device to force the join-schedule on the device force an early join.  In the case today, the device was left static to continue on its deteriorating join interval schedule and not change any parameters on the firmware network stack.  

---------
Likely not relevant, Sometime ~Fri/Sat 9/17 Bobcat appears to have pushed 1.03.6->1.0.3.7 which resulted in a orange indicator light / hung pet-eggshell-bison with this relevant log error message:  2022-09-18 03:51:20.842 1 [warning] <0.1754.0>@miner_ebus:handle_message:{116,13} Error requesting status from embedded gateway api: #{error_type => timeout}
Anyway, not expecting this is related, but originally thought this was a repro, but it turned out all functionality was down until power-cycle restored it.  Mentioning here for completeness.

**Comment by lytzV** [comment]
I looked through the log (btw only needed the "Victor Live post -reboot 1338 success join.log" because the other 2 logs are contained there) and was tracking down packets based on your console event log.

We know that pet-eggshell-bison received the following 

1. join request on Sep 21, 2022 11:33:39.776 AM
2. join request on Sep 21, 2022 12:34:12.204 PM
3. then uplink on Sep 21, 2022 12:34:46.000 PM

If you search for the following in the file

1. 2022-09-21 18:33:39.633
2. 2022-09-21 19:34:12.052
3. 2022-09-21 19:34:45.850

You will see the log for these 3 packets, and we see that they all got sent without an error.

Now, let's look at 2 join requests picked up by another hotspot on 

1. Sep 21, 2022 11:03:19.089 AM [before reboot]
2. Sep 21, 2022 12:03:56.166 PM [after reboot]

If you search for the following in the file
1. 2022-09-21 18:03:19.203
2. 2022-09-21 19:03:56.272

You will see the log for these 2 packets, and we see that the error is "multi_buy_max_packet", which means that pet-eggshell-bison heard those packets but they were rejected because other hotspots delivered them first already. 

I would recommend [enabling multi-packet](https://docs.helium.com/use-the-network/console/multi-packets/) (set it a 3, let's say) and see if that gives pet-eggshell-bison a chance to compete with other hotspots that have a faster delivery.

Let me know if that solves the issue. Thanx!

**Comment by Codepoint1** [comment]
At this point believe the issues being experienced and documented near pet-eggshell-bison are unrelated to xor-join filter bug (the original behavior this bug was opened on and now fixed), nor the transient issue that knocked out service for the 3x customers sets around 9/7.  Had a test-situation today to try multi-packet buy for pet-eggshell-bison, but the device join issue with default 1x packet buy has seemingly recurring “dropped local join” behavior detailed below.  Otherwise this is difficult to troubleshoot, many variables between potential internet responsiveness @ this specific location, specific device RF performance/environment, device firmware, bobcat firmware, helium network.  That being said I work with these devices all day and often see a certain pattern when this issue does arise that is consistent over the last month.  In most prior cases, soft-cycling the gateway seems to resolve the immediate functional issues and resets to a baseline, but the results from today show that not to be the case.

9/27 scenario:
Local pet-eggshell-bison v1.0.3.7 has been up 6 days and has a total of 15 multi_buy_max_packet errors in the log file (5 of which are shown below).  The log starts at 0 UTC on 9-27, so only includes today’s activity.

Working with B4607750800008FF CT1000 tracking tag (instead of a sensor-device).  This device has been in the console for many months (i.e. it’s not new) and got into a case where during a standard join schedule the first attempt was 
3:01:03 on active-chiffon-copperhead,  (corresponding multi_buy_max_packet in log)
3:02:15 on basic-ceramic-lion, (corresponding multi_buy_max_packet in log)
3:03:30 on basic-ceramic-lion, (corresponding multi_buy_max_packet in log)
3:04:48 on basic-ceramic-lion, (corresponding multi_buy_max_packet in log)
3:07:08 on pet-eggshell-bison, “dropped local join” ??
3:09:27 on basic-ceramic-lion, (corresponding multi_buy_max_packet in log)
3:11:48 on pet-eggshell-bison, device accepted and started uplinks ->>>>>>>>>>>>>>
//several successful join cycles / device usage elapse
4:01:59 on elegant-vanilla-dragonfly, (corresponding multi_buy_max_packet in log)
4:03:18 on pet-eggshell-bison, device accepted and started uplinks ->>>>>>>>>>>>>>
//back to successful join / device usage
4:23:08 on basic-ceramic-lion, (corresponding multi_buy_max_packet in log)
4:24:22 on bumpy-taffy-loris, (corresponding multi_buy_max_packet in log)
4:25:35 on pet-eggshell-bison, “dropped local join” ??
4:26:52 on bumpy-taffy-loris, (corresponding multi_buy_max_packet in log)
4:29:08 on pet-eggshell-bison device accepted and started uplinks ->>>>>>>>>>>>>>
//back to successful join / device usage
4:38:20 on bumpy-taffy-loris  //no longer checking log, but assume all have corresponding multiy-buy-max_packet
**3x multi-packet buy enable**
4:39:34 on pet-eggshell-bison & bumpy-taffy-loris, device accepted and started uplinks ->>>>>>>>>>>>>>
//back to successful join / device usage (mixed 1x or 2x hotspot join’s), 3 complete join cycles successful
**3x multi-packet buy disabled**
4:56:26 on pet-eggshell-bison, “**dropped local join**” ??
4:57:39 on pet-eggshell-bison, device accepted and started uplinks ->>>>>>>>>>>>>>
**//several successful join cycles / device usage elapse**
6:07:49 on bumpy-taffy-loris
6:09:07 on pet-eggshell-bison, device accepted and started uplinks ->>>>>>>>>>>>>>
**//many successful join cycles / device usage elapse**
6:31:46 on bumpy-taffy-loris
6:33:02 on pet-eggshell-bison, “**dropped local join**” ??
6:34:22 on pet-eggshell-bison, device accepted and started uplinks ->>>>>>>>>>>>>>
**~6:38 RESET (soft-boot) Bobcat Gateway, pet-eggshell-bison.**
6:40:49 sunny-cloud-otter (log shows strange timing for multi_buy_max_packet??  1:42:18 UTC)
6:42:02 on pet-eggshell-bison, device accepted and started uplinks ->>>>>>>>>>>>>>
6:53:24 on bumpy-taffy-loris, (log shows  correct timing 1:53:24 for multi_buy_max_packet)
6:54:35 on pet-eggshell-bison, device accepted and started uplinks ->>>>>>>>>>>>>>
**// several successful join / device usage**
7:13:22 on bumpy-taffy-loris
7:14:42 on pet-eggshell-bison, “**dropped local join**” ??
7:17:57 on pet-eggshell-bison, device accepted and started uplinks ->>>>>>>>>>>>>>
**//back to successful join / device usage**
7:26:19 on bumpy-taffy-loris
7:27:36 on pet-eggshell-bison, device accepted and started uplinks ->>>>>>>>>>>>>>
Pulled log (10) file.
**~7:31 RESET (hard-power off) Bobcat Gateway, pet-eggshell-bison**
7:35:04 on pet-eggshell-bison, device accepted and started uplinks ->>>>>>>>>>>>>>
8:42:14 on pet-eggshell-bison, device accepted and started uplinks ->>>>>>>>>>>>>>
8:45:03 on bumpy-taffy-loris
8:46:20 on pet-eggshell-bison, device accepted and started uplinks ->>>>>>>>>>>>>>
8:49:26 on pet-eggshell-bison, “**dropped local join**” ??
8:50:44 on bumpy-taffy-loris
8:51:59 on pet-eggshell-bison, device accepted and started uplinks ->>>>>>>>>>>>>>
9:16:22 on pet-eggshell-bison, device accepted and started uplinks ->>>>>>>>>>>>>>
Pulled Log (11) file).

Seen this “dropped local join” from pet-eggshell bison several times over the last several weeks (since 9/7), where the next attempt sometime goes through, or the device continues trying to join on remote-gateways.

Also, the bobcat logs are littered with “[ gateway-rs ] ignoring rx1 downlink error: Ack(InvalidTransmitPower(Some(28))), module: gateway”  errors for some time.  Is this an item to look at potentially?  This error message is present on both successful and unsuccessful local joins.
[Bobcat Logs 9_27_2022.zip](https://github.com/helium/gateway-rs/files/9661465/Bobcat.Logs.9_27_2022.zip)

**Comment by madninja** [comment]
The updated main branch in this repo should hopefully make this a lot more reliable since the packet router connection is recycled regularly and can/will be optimized for regional access latency. 

The `Ack(InvalidTransmitPower(Some(28)))` is not likely a critical error, it's just the packet forwarder stating it adjusted the transmit power. I don't know what region you're in but it appears the packeforwarder on device may not be configured for the region your hotspot is asserted in. 

Either way, I'm going to close this for now. If you need more support, please join the discord server in the #gateway-development channel so community members can help
