### ISSUE TITLE
Provide a changelog

### ISSUE THREAD

**Issue by mullerch** [helium/gateway-rs#282]
There has been no changelog since [Release v1.0.0-alpha.27](https://github.com/helium/gateway-rs/releases/tag/v1.0.0-alpha.27).

A changelog is very important to both integrators and users. If the changelog location has changed, its locations should be indicated somewhere in the README (or anywhere else on the project). If it's still on Github, I suggest completing previous releases with their changes and provide it on future releases.

**Comment by madninja** [comment]
We should do better at putting up release information. During alpha it's fast and furious and we often don't 
We'll try to do better at this going forward for sure.. Thanks for reporting
