### ISSUE TITLE
Multiple Hotspot list with bogus RSSI/SNR shown for Uplink

### ISSUE THREAD

**Issue by Codepoint1** [helium/gateway-rs#286]
**Describe the bug**
Occasionally the console is showing a large list of hotspots when a device uplink is sent.  The RSSI and SNR's are all identical which should not be possible, so clearly some sort of bug or data-error.  Also, shouldn't only one gateway be shown for the completed uplink?

**To Reproduce**
Occurs randomly, device/console info below.   Most uplinks are single-gateway as expected.

**Device Info (please complete the following information):**
 - Production VIP Console
 - Console Device ID: 7dc322ed-b74a-4f9b-ae31-a609dee2deff
 - Device dev eui / app eui:  B460775090000591 / B460775000000090
 - How often is device sending data:  Every 3 hours, plus whenever sensor triggered.
 - Region:  US915SB2
 - Hotspots (names) used to transfer data:  Varies, Stable Vinyl Chicken is closest gateway (see issue#287 regarding this gateway)

**Additional context**
We are not using any Packet Configurations or other special settings.  Profile ADR/CF List are enabled with Rx Delay of 1.

**Screenshots**
![image](https://user-images.githubusercontent.com/101138403/183223184-631d4e46-de6c-4d13-a7fd-7df4ef20ea2d.png)

**Comment by madninja** [comment]
This is a question for console or router. not this repo.
