### ISSUE TITLE
failed_reason': '{invalid,validation_failed}'

### ISSUE THREAD

**Issue by heliumsk1** [helium/gateway-rs#291]
helium-wallet -f xxxx.key hotspots add  xxxxxxxxxx

**Comment by heliumsk1** [comment]
failed_reason': '{invalid,validation_failed}'

**Comment by heliumsk1** [comment]
https://api.helium.io/v1/pending_transactions/sDLxO6Qa1uL884qZuk7D8BXwAfOeqrXDiBdeez5nYJU

**Comment by heliumsk1** [comment]
I can't add it at all

**Comment by heliumsk1** [comment]
docker exec miner /opt/miner/lib/miner-0.1.0/priv/gateway_rs/helium_gateway -c /opt/miner/lib/miner-0.1.0/priv/gateway_rs add --owner 13ZhYS5SHZM62dU1iHrWQGPvynULJVnEChBF6463A9CpPPiXKFW --payer 14iC6N1HkqUjH7WEChHVQhPqJ1hbWBKpZXZVeHHykCA7tNDYF2C --mode light

**Comment by madninja** [comment]
> docker exec miner /opt/miner/lib/miner-0.1.0/priv/gateway_rs/helium_gateway -c /opt/miner/lib/miner-0.1.0/priv/gateway_rs add --owner 13ZhYS5SHZM62dU1iHrWQGPvynULJVnEChBF6463A9CpPPiXKFW --payer 14iC6N1HkqUjH7WEChHVQhPqJ1hbWBKpZXZVeHHykCA7tNDYF2C --mode light

you can only add as full or dataonly.. there is no "light" support on chain
