### ISSUE TITLE
show "version `GLIBC_2.29' not found" after Release v1.0.0-alpha.29

### ISSUE THREAD

**Issue by andrewintw** [helium/gateway-rs#298]
I am using Debian GNU/Linux 10 (buster). When I install helium-gateway-v1.0.0-alpha.27-raspi_64.deb and helium-gateway-v1.0.0-alpha.28-raspi_64.deb. It works well. But after helium-gateway-v1.0.0-alpha.29-raspi_64.deb, it shows 

```
helium_gateway: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by helium_gateway)
```

Even if I rollback to v1.0.0-alpha.27, it will update to 1.0.0~alpha.31 automatically and show the same error message.

I don't know why you upgrade the dependency clib version, that is a big change and not a good choice for an embedded system.

**Comment by madninja** [comment]
It's part of a build system upgrade, not intentional. There's no good way to roll that back afaict, but if you know a way I'd love to know

**Comment by andrewintw** [comment]
> It's part of a build system upgrade, not intentional. There's no good way to roll that back afaict, but if you know a way I'd love to know

In general, Helium should maintain a fixed libc version if there are no specific reason. The original design idea is that device to update automatically, but automatic update should not force the device to upgrade the whole system. This is unreasonable for embedded systems.

The best solution is to roll back the old build environment, or use static-linking to generate the executable. Otherwise, any device will not be able to run helium_gateway after updated via Helium server.

**Comment by madninja** [comment]
> > It's part of a build system upgrade, not intentional. There's no good way to roll that back afaict, but if you know a way I'd love to know
> 
> In general, Helium should maintain a fixed libc version if there are no specific reason. Once libc is upgraded, it usually means a system-wide upgrade. I can imagine that Helium release .deb for different platforms so that those platforms can be updated automatically. But automatic update should not force the device to upgrade the whole system. This is unreasonable for embedded systems.
> 
> The best solution is to roll back the old build environment, or use static-linking to generate the executable. Otherwise, any device will not be able to run helium_gateway after updated via Helium server.
> 
> If Helium still wants to keep the new build system and use the same build process, then I think all platform maintainers will be forced to stop using automatic upgrades and build binaries from source. They also need to design their own upgrade procedure.


I understand all the arguments.. If we don't want to hold back toolchain upgrades which really help with performance and stability, what are our options? I'm looking for help, not reasons to go to the past

**Comment by andrewintw** [comment]
> > > It's part of a build system upgrade, not intentional. There's no good way to roll that back afaict, but if you know a way I'd love to know
> > 
> > 
> > In general, Helium should maintain a fixed libc version if there are no specific reason. Once libc is upgraded, it usually means a system-wide upgrade. I can imagine that Helium release .deb for different platforms so that those platforms can be updated automatically. But automatic update should not force the device to upgrade the whole system. This is unreasonable for embedded systems.
> > The best solution is to roll back the old build environment, or use static-linking to generate the executable. Otherwise, any device will not be able to run helium_gateway after updated via Helium server.
> > If Helium still wants to keep the new build system and use the same build process, then I think all platform maintainers will be forced to stop using automatic upgrades and build binaries from source. They also need to design their own upgrade procedure.
> 
> I understand all the arguments.. If we don't want to hold back toolchain upgrades which really help with performance and stability, what are our options? I'm looking for help, not reasons to go to the past

I already said that using static linking is an option at the moment. Maybe you can provide a binary for both ways of linking. Or let the platform provider handle the upgrade by themself.

**Comment by madninja** [comment]
> > > > It's part of a build system upgrade, not intentional. There's no good way to roll that back afaict, but if you know a way I'd love to know
> > > 
> > > 
> > > In general, Helium should maintain a fixed libc version if there are no specific reason. Once libc is upgraded, it usually means a system-wide upgrade. I can imagine that Helium release .deb for different platforms so that those platforms can be updated automatically. But automatic update should not force the device to upgrade the whole system. This is unreasonable for embedded systems.
> > > The best solution is to roll back the old build environment, or use static-linking to generate the executable. Otherwise, any device will not be able to run helium_gateway after updated via Helium server.
> > > If Helium still wants to keep the new build system and use the same build process, then I think all platform maintainers will be forced to stop using automatic upgrades and build binaries from source. They also need to design their own upgrade procedure.
> > 
> > 
> > I understand all the arguments.. If we don't want to hold back toolchain upgrades which really help with performance and stability, what are our options? I'm looking for help, not reasons to go to the past
> 
> I already said that using static linking is an option at the moment. Maybe you can provide a binary for both ways of linking. Or let the platform provider handle the upgrade by themself.

who is the platform provider in your case?

**Comment by JiapengLi** [comment]
I believe all debian 10 buster based OS would have the same problem. 
Debian 11 bullseye upgrade the glibc for all arches (in this case it is aarch64), 
so dynamic compiled binary on Debian 11 will not run on Debian 10.

**Comment by andrewintw** [comment]
> > > > > It's part of a build system upgrade, not intentional. There's no good way to roll that back afaict, but if you know a way I'd love to know
> > > > 
> > > > 
> > > > In general, Helium should maintain a fixed libc version if there are no specific reason. Once libc is upgraded, it usually means a system-wide upgrade. I can imagine that Helium release .deb for different platforms so that those platforms can be updated automatically. But automatic update should not force the device to upgrade the whole system. This is unreasonable for embedded systems.
> > > > The best solution is to roll back the old build environment, or use static-linking to generate the executable. Otherwise, any device will not be able to run helium_gateway after updated via Helium server.
> > > > If Helium still wants to keep the new build system and use the same build process, then I think all platform maintainers will be forced to stop using automatic upgrades and build binaries from source. They also need to design their own upgrade procedure.
> > > 
> > > 
> > > I understand all the arguments.. If we don't want to hold back toolchain upgrades which really help with performance and stability, what are our options? I'm looking for help, not reasons to go to the past
> > 
> > 
> > I already said that using static linking is an option at the moment. Maybe you can provide a binary for both ways of linking. Or let the platform provider handle the upgrade by themself.
> 
> who is the platform provider in your case?

A platform provider is a manufacturer or maker that uses the same hardware as raspi_64, caldigit, tektelic, freedomfi, etc. in the README.me table.

**Comment by andrewintw** [comment]
> I believe all debian 10 buster based OS would have the same problem. Debian 11 bullseye upgrade the glibc for all arches (in this case it is aarch64), so dynamic compiled binary on Debian 11 will not run on Debian 10.

When we developing fullhostpot, we have been using Debian 10 buster, and we use the same SDK for lighthotspot. Everything worked fine until gateway-v1.0.0-alpha.29.

Updating glibc is a big change for any embedded system. Maybe we've passed some hardware audit before, and some software has been in use for a while. Updating glibc means that there is a lot of software that needs to be recompiled and tested.

**Comment by madninja** [comment]
I understand.. want to provide a PR that makes the raspi Debian builds a musl target instead of a dynamic target? The binary size will get bigger but I think it may remove the glibc dependencies

**Comment by madninja** [comment]
@andrewintw With the simplification on the main branch of no packaged releases for this repo, and target triplet based builds, I hope it's clearer that a maker _could_ pick up a binary build from here but the build is really just there to ensure it works on a given target triplet without trying to be the definitive binary release for any given complete platform. A maker should probably build their own binary and roll it into their own upgrade packaging (which is going to be needed anyway). 

Foundation approval for a given piece of hardware is based on[ gateway-mfr-rs](https://github.com/helium/gateway-mfr-rs) which _does_ require the public repo to produce a binary for validation that can run on the target hardware. This may mean that repository will need fixes to make sure the built and released gateway_mfr binary works on your target

Does that make sense?

**Comment by madninja** [comment]
With #363 the `-gnu` builds are all musl builds now so hopefully that helps with static builds
