### ISSUE TITLE
RAK7258 error

### ISSUE THREAD

**Issue by argonfatl** [helium/gateway-rs#30]
Not sure why but i have that 
way[1531]:  INFO routing error: Service(Rpc(Status { code: Unknown, message: "h2 protocol error: protocol error: received frame when stream half-closed" })), module: router
Wed Apr  7 08:26:32 2021 daemon.info helium_gateway[1531]:  INFO selected gateway, uri: http://18.216.219.228:8080/, public_key: 112AY1cJ9quokGVZL8uVQ9Jih1cHsji2VVoKApf2fVPBseHcRsg, module: router
Wed Apr  7 08:26:33 2021 daemon.info helium_gateway[1531]:  INFO updated routing to height 793801, module: router

**Comment by lthiery** [comment]
@argonfatl thanks for the report! We're trying to resolve it as it appears to affect downlinks (JoinAccepts included)

**Comment by argonfatl** [comment]
Fri Apr  9 12:40:37 2021 daemon.info helium_gateway[1531]:  WARN router returned invalid height 795354 while at 795354, module: router
Fri Apr  9 12:40:37 2021 daemon.info helium_gateway[1531]:  INFO updated routing to height 795354, module: router
Fri Apr  9 12:44:40 2021 daemon.info helium_gateway[1531]:  INFO no update found, module: updater
Fri Apr  9 12:54:40 2021 daemon.info helium_gateway[1531]:  INFO no update found, module: updater
Fri Apr  9 13:04:40 2021 daemon.info helium_gateway[1531]:  INFO no update found, module: updater

**Comment by lthiery** [comment]
@argonfatl I believe this issue was resolved with yesterday's Router release, so I think I'll close this issue.

The logs you are showing aren't particular concerning? The warning is perhaps a little overzealous?

**Comment by lthiery** [comment]
For extra context, here was the bug fix
https://github.com/helium/router/pull/277

**Comment by argonfatl** [comment]
after Rak firmware update, everything looks like  works good
