### ISSUE TITLE
Hotspot should periodically reconnect to HPR

### ISSUE THREAD

**Issue by macpie** [helium/gateway-rs#324]

**Comment by michaeldjeffrey** [comment]
I'm hoping it's just this easy https://github.com/helium/gateway-rs/pull/289/commits/6f0c29db7aeb610017af11c6881ac6755162330d.
Should come up in a madninja review.

This change also came with rebasing on main of gateway-rs to absorb some recent changes, and getting up to speed with `macpie/session_key_filter` proto branch.

**Comment by madninja** [comment]
Implemented with https://github.com/helium/gateway-rs/pull/345
