### ISSUE TITLE
Dragino LG01-S - Cannot install package helium_gateway

### ISSUE THREAD

**Issue by imaniroman** [helium/gateway-rs#33]
Hello Everyone!

I have a Dragino LG01-S that does nothing and collects dust. While I wait for proper gateways to arrive, I thought I'd mess around with this gateway.

Any idea on how I could fix this?

"root@dragino-192e20:/tmp# opkg install helium-gateway-v1.0.0-alpha.6-dragino.ipk
Unknown package 'helium_gateway'.
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for helium_gateway found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package helium_gateway." 
 
 Thanks!

**Comment by madninja** [comment]
Can you check if it actually started running?

**Comment by imaniroman** [comment]
I tried ps and top. I do not see anything helium_gateway or anything helium related running.

**Comment by madninja** [comment]
Ok, can you confirm that you followed the instructions on: https://docs.helium.com/mine-hnt/light-hotspots/guides/dragino/ ?

Specifically there's a line in there about installing the `ca-bundle` package for this to work. The newer Dragino firmware has this already installed but if you are on an older firmware build you have to install this package manually for the helium-gateway ipk to install

**Comment by imaniroman** [comment]
Oops, I didn't read that line!

Now I am having issues with the `ca-bundle` install. I did use `opkg update` before trying to install `ca-bundle` .

I thought I should try `opkg install ca-certificates` as this line is commonly mentioned in other forums/docs. This installed fine... 

Thanks for everything!

![Ca-bundle error](https://user-images.githubusercontent.com/41558467/114737249-6a99cc80-9d79-11eb-9173-70ea44b85808.PNG)

**Comment by madninja** [comment]
If you could join discord there are Dragino folks ready to help out. Specifically at message: 

https://discord.com/channels/404106811252408320/784462269072277576/826780546184249375

which mentions to try: 

``wget https://www.dragino.com/downloads/downloads/LoRa_Gateway/LIG16/Firmware/Packages/ca-bundle_20210119-1_all.ipk
opkg install ca-bundle_20210119-1_all.ipk 
```

If that doesn't work your firmware may just be way out of date and you will have to follow Dragino firmware update instructions first

**Comment by imaniroman** [comment]
Thanks for sharing @madninja !

Found another Dragino gateway at home, LG01-N. Seems like this gateway is newer (prettier GUI) and still supported with firmware updates. Had now issues getting the LG01-N online. 

LG01-S is old and no longer maintained by dragino. I'll just focus on the LG01-S from now on.

Thanks again!
