### ISSUE TITLE
no recent packaged ipk release

### ISSUE THREAD

**Issue by fvasquez** [helium/gateway-rs#333]
The last packaged gateway-rs release is v1.0.0-alpha.31 from August 17, 2022.

LoRa gateway manufacturers who run OpenWRT on their devices rely on these ipk package releases to deploy and update gateway-rs.

**Comment by madninja** [comment]
> The last packaged gateway-rs release is v1.0.0-alpha.31 from August 17, 2022.
> 
> LoRa gateway manufacturers who run OpenWRT on their devices rely on these ipk package releases to deploy and update gateway-rs.

A new release is coming shortly..
