### ISSUE TITLE
Rak7289 support for Alpha33

### ISSUE THREAD

**Issue by Tommmy-D** [helium/gateway-rs#343]
We've been using the previous version alpha31 successfully on a RAK7289 for the past few months.  The helium_gateway instance now refuses to start after self-updating to alpha33.  Are there any other users of the same hardware that can provide some guidance?  Alternatively, can self-updating be turned off, so that a rollback to alpha31 could be kept in place until a fix is found?

**Comment by madninja** [comment]
The main thing that changed in alpha.33 _was_ the removal of the self updater. 

Could you provide some logs as to why it's failing to start?

**Comment by Tommmy-D** [comment]
a manual reinstall of alpha.33 has apparently fixed the problem.  thanks for the quick reply
