### ISSUE TITLE
Raspberry Pi / Docker Support

### ISSUE THREAD

**Issue by ryanteck** [helium/gateway-rs#35]
Hia,

So I've been doing some basic work to get started with Gateway RS on our RPi based gateways.

Now I know that @shawaj did do a PR to package it as Debian packages at https://github.com/helium/gateway-rs/pull/17

However the PR is quite old, and I'm not now sure if it'd be better to instead target an alpine base which would be more compact. 

What's kind of the route you'd want to go for these? 

As alternatively looking into it, there's not neccesarily a need for a pre-compiled package as the docker container can compile the software in a build step and then copy it into the image that is deployed.

Then would you provide the container like the current miner, or would it be better for us to manage it?

**Comment by madninja** [comment]
> However the PR is quite old, and I'm not now sure if it'd be better to instead target an alpine base which would be more compact.

I believe that these are two different strategies, both equally valid:

1. Users who have a side table of some sorts and want to run helium-gateway  on standard raspbian 
2. Users like yourselves who want a docker based alternative

I think we could enable both as part of the build?

**Comment by ryanteck** [comment]
Essentially the Deb route would work fine for us deploying to docker if there's the standard raspbian route taking place at the same time. 

We can then just build the docker container with a cut down debian base, and install the Deb into that without issue.

**Comment by ryanteck** [comment]
Yeah I think that sounds good, overriding the settings file to disable checking wouldn't be an issue.  I would presume that the systemd files would just get ignored by docker and we just set an entrypoint to either the software or a script that starts the software so yeah that all sounds good.

Let me know when a Deb is ready to try out and I'll put together our container and test it out.
