### ISSUE TITLE
The setting.toml file is really not aligned with current code version

### ISSUE THREAD

**Issue by disk91** [helium/gateway-rs#380]
When tryin to use the current madninja/hpr branch, the setting.toml is nt compatibe with the current branch version
- update block is missing
- packet_router does not exists
- potnetially some otehr

**Comment by madninja** [comment]
> When tryin to use the current madninja/hpr branch, the setting.toml is nt compatibe with the current branch version
> 
> * update block is missing
> * packet_router does not exists
> * potnetially some otehr

* gateway-rs no longer supported the self-updater and releases only compiled application binaries. 
* packet_router does not exist because it's under `[router]` in settings.toml. https://github.com/helium/gateway-rs/blob/main/config/settings.toml#L46-L51

Do you actually see it not working?

**Comment by disk91** [comment]
Yes, sorry for this, that was a problem in my build, I was still using the previous version with the new setting file.

Now it's working, but I did note another change than can impact people migrating, -c was getting a directory and now, it seems that you need to pass the setting.toml file directly.

The previous approach with a default.toml file overrided by the settings.toml file was really usefull when manging mulitple gateway-rs in a single serve to be used with classicla loRaWn gateways. It would be great to keep this previous behavior

**Comment by madninja** [comment]
> Yes, sorry for this, that was a problem in my build, I was still using the previous version with the new setting file.
> 
> Now it's working, but I did note another change than can impact people migrating, -c was getting a directory and now, it seems that you need to pass the setting.toml file directly.
> 
> The previous approach with a default.toml file overrided by the settings.toml file was really usefull when manging mulitple gateway-rs in a single serve to be used with classicla loRaWn gateways. It would be great to keep this previous behavior

Having the file file setup was only useful because the previous release mode included packaged releases which meant it required a baseline settings followed by override. Since this repo no longer ships packaged releases, the dual file setup caused too many issues for folks not knowing which file needed to be edited. For your configuration, you would use your own settings.toml.template and replace attributes during a deploy step?

**Comment by madninja** [comment]
Closing this as unplanned. 

You can use environment variables to override settings.toml entries
