### ISSUE TITLE
Installing gateway-rs using Docker

### ISSUE THREAD

**Issue by ffries** [helium/gateway-rs#401]
Dear all,

First thanks for the hard work.
I need to integrate a Mikrotik Wap LR8 to the People's network.
But is incompatible with the Helium network, so I need gateway-rs.

Can I use Docker to install gateway-rs on my Synology NAS ?
There are several docker projects for gateway-rs.
Which Docker project should I use?

Thanks !

**Comment by MuratUrsavas** [comment]
This is the official repo Helium is using: https://quay.io/repository/team-helium/miner?tab=tags

**Comment by madninja** [comment]
Murat already mentioned where to get the gateway-rs docker image. Note that the image relies on a semtech compatible packet forwarder already installed somewhere and pointed at gateway-rs.
