### ISSUE TITLE
Keeping developer test devices out of Deny List

### ISSUE THREAD

**Issue by MuratUrsavas** [helium/gateway-rs#410]
Hi,

This place is not exactly the correct location for this, I know, but it's the most relevant right now as we're deploying big changes on our devices. Two of my test hotspots are falsely marked and put on the Deny List without a proper reason (Actually I believe we have a lot of similar hotspots in Ankara, Turkiye). I've requested a removal long time ago but nothing happened. Right now it is very crucial for me to see the results of the changes on gateway-rs.

Can we have a channel to remove and protect developer hotspots from Deny List?

Here are the list of my devices in Deny List:

* 11313cvHitCaxTHToyg6Wrnir2E3z2yxcKqstrTVmiSz6uCZskS
* 112otfLkLz34eJLKXe9UEWP4Y4hbadtSoE2dsKK8bLGmHqWquTAR

**Comment by madninja** [comment]
This is really not the place to do this.. There is a crowdspot channel already for this on Discord and gateway-rs is really not the place to be discussing unrelated topics
