### ISSUE TITLE
Automatic Region Frequency Selection

### ISSUE THREAD

**Issue by ryanteck** [helium/gateway-rs#43]
In the current miner we're able to get the region from that to configure the radio module for the correct frequency plan.

While currently we have to specify the region in development for this, will a feature such as above be introduced for gateway-rs when hotspots can be onboarded?

Thanks

**Comment by madninja** [comment]
So currently your boxes are not setting region at the factory for the packetforwarder/radio?  you wait for miner to sync up enough to get it there and then configure the radio with it?

**Comment by ryanteck** [comment]
@madninja Correct , as followed in the guide at https://docs.helium.com/mine-hnt/hotspot-makers/docker-integration/#omit-region_override

**Comment by madninja** [comment]
> @madninja Correct , as followed in the guide at https://docs.helium.com/mine-hnt/hotspot-makers/docker-integration/#omit-region_override

Yeah.. there will have to be something in gateway-rs (and perhaps the corresponding gateway service) to support this.. @cokes518 for tracking

**Comment by madninja** [comment]
https://github.com/helium/gateway-rs/pull/193 adds support on the gateway-rs side to get and track the configured region for data packets. Took a while to get here, but once the lgw validators update it'll be available in gateway-rs

**Comment by shawaj** [comment]
Nice one @madninja 🙌
