### ISSUE TITLE
helium_gateway service does not run after auto upgrade

### ISSUE THREAD

**Issue by PaulVMo** [helium/gateway-rs#48]
After auto-upgrading on a Dragino LPS8 (firmware lgw-5.4.1607519907) , the helium_gateway service is not started. This was observed upgrading from v1.0.0-alpha.8 to v1.0.0-alpha.9.

The following messages appear in the syslog showing that the upgrade occurs:

Tue May 18 15:30:33 2021 daemon.info helium_gateway[21893]:  INFO downloading helium-gateway-v1.0.0-alpha.9-dragino.ipk, asset: helium-gateway-v1.0.0-alpha.9-dragino.ipk, module: updater 
Tue May 18 15:30:35 2021 daemon.info helium_gateway[21893]:  INFO installing helium-gateway-v1.0.0-alpha.9-dragino.ipk, asset: helium-gateway-v1.0.0-alpha.9-dragino.ipk, module: updater

It is clear that helium_gateway is not running as there are no other syslog entries from helium_gateway until it is restarted or system is rebooted. Furthermore, `/etc/init.d/helium_gateway stop` returns Command not found which is the message when trying to stop the service when not running.

And, the command `helium_gateway --version` shows helium_gateway 1.0.0-alpha.9.

Finally, a potentially related symptom is that the version number shown by `opkg list-installed` also is not updated and shows the version originally installed even after the upgrade.

**Comment by madninja** [comment]
Huh.. this is annoying.. We still don't know why this happens.. I'm wondering if we need to do the same upgrade strategy that the klkgw type uses.. i.e. reboot after a package upgrade.

**Comment by PaulVMo** [comment]
Could it be something with the way that the upgrade function waits for the install_upgrade script to finish that is blocking the old version for stopping correctly? I think I recall turning off auto upgrade and running install_upgrade script manually and it did start up correctly.

**Comment by PaulVMo** [comment]
Been thinking about this more. I think maybe forking the process, and then running the upgrade command as the child might do it. As is, the upgrade process is a child of helium_gateway which is stopped by the upgrade process which in turn would kill the upgrade process since it is a child, right? So that could be leading to the issue of the upgrade not fully taking effect?. If I get some time and can get past the build errors, I might be able to give this a try.

**Comment by madninja** [comment]
> Been thinking about this more. I think maybe forking the process, and then running the upgrade command as a child of the forked process might do it. As is, the upgrade process is a child of helium_gateway which is stopped by the upgrade process which in turn would kill the upgrade process since it is a child, right? So that could be leading to the issue of the upgrade not fully taking effect?. If I get some time and can get past the build errors, I might be able to give this a try.

If we fork it we wouldn't be able to get the error result or output (which I'd like to log for failures at some point) back to the parent. I think perhaps rebooting after the upgrade completes is a simpler fix?
