### ISSUE TITLE
ignoring send to client with unknown MAC mac=00:00:00:00:00:00:00:00

### ISSUE THREAD

**Issue by softlion** [helium/gateway-rs#482]
Hello,
I'm using the docker version of

What could cause that issue ?

```
INFO run: gateway_rs::beaconer: transmitting beacon beacon_id="xxx"
WARN gateway_rs::gateway: failed to transmit beacon beacon_id="xxx" err=error receiving ACK
WARN run: gateway_rs::beaconer: transmit beacon err=gateway error: beacon transmit failed
INFO run: gateway_rs::gateway: ignoring send to client with unknown MAC mac=00:00:00:00:00:00:00:00
```

I found in the source code that it is when the lora concentrator post that;
```
            Event::NoClientWithMac(_packet, mac) => {
                info!(%mac, "ignoring send to client with unknown MAC")
```
That concentrator is a black box, so I don't know what can cause it.

That's the code I use to run gateway rs:
```
i2cdevice="i2c-0"

sudo docker run -d --name helium \
    --restart unless-stopped \
    --device "/dev/$i2cdevice" \
    --privileged \
    -v /var/run/dbus:/var/run/dbus \
    -e "GW_KEYPAIR=ecc://$i2cdevice:96?slot=0" \
    -e "GW_ONBOARDING=ecc://$i2cdevice:96?slot=0" \
    -e "GW_REGION=EU868" \
    -e "GW_LISTEN=0.0.0.0:1682" \
    -p 127.0.0.1:4467:4467 \
    --network lorawan \
    --hostname helium \
    quay.io/team-helium/miner:gateway-latest
```

**Comment by madninja** [comment]
This looks like your json packet forwarder is not configured with a mac address. Perhaps you don't have host networking turned on for the docker it's running in?

**Comment by softlion** [comment]
It's worked around. I stopped using gatewayrs. Instead I'm using another docker that already contains the multiplexer, and where the lorawan MAC address is provided as an argument.

So it looks like the issue is in gateway rs, where it is unable to get the lorawan MAC address.

Do you happen to know what code in gatewayrs is in charge of determining that address ?

**Comment by softlion** [comment]
> This looks like your json packet forwarder is not configured with a mac address. Perhaps you don't have host networking turned on for the docker it's running in?
> This looks like your json packet forwarder is not configured with a mac address. Perhaps you don't have host networking turned on for the docker it's running in?

You are right and I don't want to turn it on, I want to use an internal docker network instead.  
Instead I tried mapping only /sys/net, that fixed errors but not that specific issue.

**Comment by madninja** [comment]
yeah. a valid MAC address is required since the semtech-udp crate supports multiple radios.. figure out a way to get your packet forwarder to have a mac address. Your environment setup is a bit beyond the scope of the gateway-rs repo
