### ISSUE TITLE
Compile fails using Rustc 1.80.0 

### ISSUE THREAD

**Issue by jthiller** [helium/gateway-rs#484]
Compiling directly on a Raspberry Pi 3 under a new install `cargo build` fails to complete.

<img width="388" alt="image" src="https://github.com/user-attachments/assets/fcb643a0-1dee-4ec6-9120-22ed4f3e26b0">

<img width="884" alt="image" src="https://github.com/user-attachments/assets/dd77b7e8-e3d4-4919-a068-0c6aa01a2f46">

---

Loading 1.79.0 via rustup lends to a successful build.
<img width="476" alt="image" src="https://github.com/user-attachments/assets/b17f377b-ef08-44ac-8c66-54e3cd3bc78f">
`...`
<img width="696" alt="image" src="https://github.com/user-attachments/assets/a9adaf71-b145-4c6d-9966-ef52941b93ba">

**Comment by jthiller** [comment]
`cargo update time` took latest [time](https://github.com/time-rs/time) 0.3.36
Build with rustc 1.80.0 has a couple new warnings on gateway-rs related to the use of `time`, but completes successfully

**Comment by madninja** [comment]
Fixed with #475 

The data ack proto code and support in hpr was merged and deployed a while ago (please confirm @michaeldjeffrey ). I've updated that PR to include the rust upgrade issues. 

Note @jthiller that currently the CI build limits rust to 1.72 since there were issues with newer rust async on mipsel

**Comment by madninja** [comment]
Will need to handle #475 issues separately

**Comment by michaeldjeffrey** [comment]
> The data ack proto code and support in hpr was merged and deployed a while ago (please confirm @michaeldjeffrey ). I've updated that PR to include the rust upgrade issues.

Confirming packet acks are in HPR https://github.com/helium/helium-packet-router/pull/279
