### ISSUE TITLE
gateway-rs crashes on inbound packet

### ISSUE THREAD

**Issue by syadnom** [helium/gateway-rs#50]
nc during a send:
"T{"rxpk":[{"chan":7,"codr":"4/5","data":"QEgAAEiAJS8CmwMUKTr7OghOxMmChZt2","datr":"SF10BW125","freq":905.300000,"lsnr":13.500000,"modu":"LORA","rfch":1,"rssi":-47,"size":24,"stat":1,"time":"2021-05-27T23:11:04.778146Z","tmst":205995437}]}12512(T{"rxpk":[{"chan":5,"codr":"4/5","data":"AMTpU5w4EUMV+3eBu3xBQDKxkIu0yuw=","datr":"SF10BW125","freq":904.900000,"lsnr":-8.250000,"modu":"LORA","rfch":1,"rssi":-103,"size":23,"stat":-1,"time":"2021-05-27T23:11:08.487752Z","tmst":209705180}]}X2512(T{"rxpk":[{"chan":7,"codr":"4/5","data":"AMTpU5w4ESMlynSC0XZBQKjU9km0xu4=","datr":"SF10BW125","freq":905.300000,"lsnr":13.250000,"modu":"LORA","rfch":1,"rssi":-49,"size":23,"stat":1,"time":"2021-05-27T23:11:08.489584Z","tmst":209707501}]}▒2512(T{"stat":{"ackr":0.000000,"dwnb":0,"rxfw":4,"rxnb":4,"rxok":3,"time":"2021-05-27 23:11:11 GMT","txnb":0}}Z2512(T{"rxpk":[{"chan":5,"codr":"4/5","data":"QAwAAEiBAAANAq0UPzfb","datr":"SF10BW125","freq":904.900000,"lsnr":13.250000,"modu":"LORA","rfch":1,"rssi":-62,"size":15,"stat":1,"time":"2021-05-27T23:11:13.917361Z","tmst":215135308}]}"

syslog entry from the send;
May 27 17:09:15 raspberrypi helium_gateway[1872]: routing packet to: http://54.193.165.228:8080/, module: router
May 27 17:09:15 raspberrypi helium_gateway[1872]: ignoring raw packet PushData(Packet { random_token: 397, gateway_mac: MacAddress { bytes: [50, 53, 49, 50, 40, 0, 84, 0] }, data: Data { rxpk: Some([V1(RxPkV1 { chan: 4, codr: _4_5, data: [0, 196, 233, 83, 156, 56, 17, 35, 37, 202, 116, 130, 209, 118, 65, 64, 168, 33, 228, 203, 25, 182, 164], datr: DataRate(SF10, BW125), freq: 904.7, lsnr: 10.5, modu: LORA, rfch: 1, rssi: -50, rssis: None, size: 23, stat: OK, tmst: 96444652 })]), stat: None } }), module: gateway
May 27 17:09:15 raspberrypi helium_gateway[1872]: thread 'main' panicked at 'index out of bounds: the len is 29 but the index is 29', /cargo/registry/src/github.com-1ecc6299db9ec823/xorf-0.7.0/src/xor16.rs:64:9
May 27 17:09:15 raspberrypi helium_gateway[1872]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
May 27 17:09:15 raspberrypi systemd[1]: helium_gateway.service: Main process exited, code=killed, status=6/ABRT
May 27 17:09:15 raspberrypi systemd[1]: helium_gateway.service: Failed with result 'signal'.

cat settings.toml
listen_addr = "0.0.0.0:1680"

[log]
method = "syslog"
level = "info"
timestamp = false

[update]
platform = "raspi234"

forwarder is a mikrotik wAPLR9 on the local network.

**Comment by diogo24m** [comment]
I have the same problem

**Comment by kwa-stack** [comment]
Is it possible to build this on a raspberry pi? I'm curious.

**Comment by syadnom** [comment]
I haven't tackled how to build it yet.  I'm using the prebuilt package.

**Comment by kwa-stack** [comment]
I'm pretty much new to this a reading a lot about DIY since I own a PI. Where do I find the prebuilt packages? Thank you.

**Comment by syadnom** [comment]
right here on github
https://github.com/helium/gateway-rs/releases

**Comment by kwa-stack** [comment]
Thank you
