### ISSUE TITLE
LPS8 Malformed package

### ISSUE THREAD

**Issue by JustinChaos** [helium/gateway-rs#54]
I keep getting the following error on my LPS8 while trying to set it up for the HNT gateway. The error is:

"**pkg_init_from_file: Malformed package file helium-gateway-v1.0.0-alpha.9-dragino.ipk."**

I have reset the LPS8 multiple times and tried installing using: 

**"opkg install  /tmp/ helium-gateway-v1.0.0-alpha.9-dragino.ipk"**  

what am I doing wrong, and how do I fix this?

I have downloaded it using two different commands with the same result

**"wget -O helium-gateway-v1.0.0-alpha.9-dragino.ipk https://github.com/helium/gateway-rs/releases"**

**"wget -O helium-gateway-v1.0.0-alpha.9-dragino.ipk https://github.com/helium/gateway-rs/releases/tag/v1.0.0-alpha.9"**

**Comment by madninja** [comment]
> I keep getting the following error on my LPS8 while trying to set it up for the HNT gateway. The error is:
> 
> "**pkg_init_from_file: Malformed package file helium-gateway-v1.0.0-alpha.9-dragino.ipk."**
> 
> I have reset the LPS8 multiple times and tried installing using:
> 
> **"opkg install /tmp/ helium-gateway-v1.0.0-alpha.9-dragino.ipk"**

did you try `sudo opkg install /tmp/ helium-gateway-v1.0.0-alpha.9-dragino.ipk` and are you sure you downloaded it to the `tmp` folder?

**Comment by JustinChaos** [comment]
Hello, thank you for the response. However I am still having a similar issue, now it is saying

 opkg install  /tmp/helium-gateway-v1.0.0-alpha.9-dragino.ipk
Collected errors:
 * wfopen: /tmp/helium-gateway-v1.0.0-alpha.9-dragino.ipk: No such file or directory.
 * pkg_init_from_file: Failed to extract control file from /tmp/helium-gateway-v1.0.0-alpha.9-dragino.ipk.

**Comment by madninja** [comment]
> Hello, thank you for the response. However I am still having a similar issue, now it is saying
> 
> opkg install /tmp/helium-gateway-v1.0.0-alpha.9-dragino.ipk
> Collected errors:
> 
> * wfopen: /tmp/helium-gateway-v1.0.0-alpha.9-dragino.ipk: No such file or directory.
> * pkg_init_from_file: Failed to extract control file from /tmp/helium-gateway-v1.0.0-alpha.9-dragino.ipk.

from the error it looks like you did not download the package to the /tmp folder

**Comment by JustinChaos** [comment]
I got it working, thank you very much for all the help :)
