### ISSUE TITLE
routing error:  ***  os error 111

### ISSUE THREAD

**Issue by enric-lee** [helium/gateway-rs#66]
Hello,

I used RAK7243 raspiberry LoRa gateway ,  and I installed Release v1.0.0-alpha.13 deb package of gateway-rs  ,  modified the ip to 127.0.0.1 and port to 1680 of global_config.json.   After reboot, I met the problem as follows:

> Jul  9 08:21:44 rak-gateway helium_gateway[1386]: selected gateway, module: router, uri: http://18.216.219.228:8080/, public_key: 112AY1cJ9quokGVZL8uVQ9Jih1cHsji2VVoKApf2fVPBseHcRsgA
> Jul  9 08:21:44 rak-gateway helium_gateway[1386]: routing error: Service(Rpc(Status { code: Unknown, message: "transport error: error trying to connect: tcp connect error: Connection refused (os error 111)" })), module: router
> Jul  9 08:21:45 rak-gateway helium_gateway[1386]: ignoring raw packet PullData(Packet { random_token: 51610, gateway_mac: MacAddress { bytes: [220, 166, 50, 255, 254, 39, 28, 63] } }), module: gateway

Could please tell me where is the problem is?

**Comment by fishpepper** [comment]
I see the same error message (raspi3 + WM1302 hat) and gateways-rs built from source.

**Comment by enric-lee** [comment]
> I see the same error message (raspi3 + WM1302 hat) and gateways-rs built from source.

Do you have solution for the problem?

**Comment by fishpepper** [comment]
Turns out the gateway had a problem, madninja fixed it on their side. Its working for me now.
