### ISSUE TITLE
Dragino Gateway Model LG308

### ISSUE THREAD

**Issue by khunsomsak** [helium/gateway-rs#68]
Alpha 9.0 was working fine but not Alpha 13.0 . You can add this model in the list. The firmware is the same as LPS8 and DLOS8.

**Comment by madninja** [comment]
> Alpha 9.0 was working fine but not Alpha 13.0 . You can add this model in the list. The firmware is the same as LPS8 and DLOS8.

can you supply what was not working when you loaded alpha.13 on it?

**Comment by khunsomsak** [comment]
Change region to AS923 
keypair = "/etc/helium_gateway/gateway_key.bin"
listen_addr = "127.0.0.1:1680"
region = "AS923"

and
add region 
region = "AS923"
[log]
method = "stdio"
level = "info"
timestamp = false
[update]
platform = "dragino"

When execute helium_gateway key info
Error: Config(unsupported region: AS923)

If change back to US915, it is ok.

**Comment by madninja** [comment]
See https://github.com/helium/gateway-rs/issues/67 which you posted!

**Comment by khunsomsak** [comment]
OK, Thailand is AS923_1 
I use the default parameters in default.toml. What is the console page? https://staging-console.helium.wtf/ or https://console.helium.com/ 

My logread is.

Fri Jul  9 22:20:09 2021 daemon.info helium_gateway[1997]:  INFO routing packet to: http://54.193.165.228:8080/, module: router
Fri Jul  9 22:20:17 2021 daemon.info helium_gateway[1997]:  WARN ignoring uplink error: Service(Rpc(Status { code: Unknown, message: "no response", metadata: MetadataMap { headers: {"user-agent": "grpc-erlang/0.1.0", "content-type": "application/grpc+proto", "grpc-encoding": "identity"} } })), module: router
Fri Jul  9 22:20:32 2021 daemon.info helium_gateway[1997]:  INFO ignoring raw packet PushData(Packet { random_token: 61866, gateway_mac: MacAddress { bytes: [168, 64, 65, 29, 3, 16, 65, 80] }, data: Data { rxpk: None, stat: Some(Stat { time: "2021-07-09 15:20:32 UTC", lati: Some(13.799206), long: Some(100.338346), alti: Some(10), rxnb: 1, rxok: 1, rxfw: 1, ackr: Some(100.0), dwnb: 0, txnb: 0 }) } }), module: gateway
Fri Jul  9 22:20:34 2021 daemon.info helium_gateway[1997]:  INFO ignoring raw packet PullData(Packet { random_token: 20838, gateway_mac: MacAddress { bytes: [168, 64, 65, 29, 3, 16, 65, 80] } }), module: gateway
Fri Jul  9 22:21:02 2021 daemon.info helium_gateway[1997]:  INFO ignoring raw packet PushData(Packet { random_token: 896, gateway_mac: MacAddress { bytes: [168, 64, 65, 29, 3, 16, 65, 80] }, data: Data { rxpk: None, stat: Some(Stat { time: "2021-07-09 15:21:02 UTC", lati: Some(13.799206), long: Some(100.338346), alti: Some(10), rxnb: 0, rxok: 0, rxfw: 0, ackr: Some(0.0), dwnb: 0, txnb: 0 }) } }), module: gateway
Fri Jul  9 22:21:04 2021 daemon.info helium_gateway[1997]:  INFO ignoring raw packet PullData(Packet { random_token: 45449, gateway_mac: MacAddress { bytes: [168, 64, 65, 29, 3, 16, 65, 80] } }), module: gateway
Fri Jul  9 22:21:32 2021 daemon.info helium_gateway[1997]:  INFO ignoring raw packet PushData(Packet { random_token: 50210, gateway_mac: MacAddress { bytes: [168, 64, 65, 29, 3, 16, 65, 80] }, data: Data { rxpk: None, stat: Some(Stat { time: "2021-07-09 15:21:32 UTC", lati: Some(13.799206), long: Some(100.338346), alti: Some(10), rxnb: 1, rxok: 0, rxfw: 0, ackr: Some(0.0), dwnb: 0, txnb: 0 }) } }), module: gateway
Fri Jul  9 22:21:34 2021 daemon.info helium_gateway[1997]:  INFO ignoring raw packet PullData(Packet { random_token: 52103, gateway_mac: MacAddress { bytes: [168, 64, 65, 29, 3, 16, 65, 80] } }), module: gateway

**Comment by khunsomsak** [comment]
Just have seen Join Request and Join Accept on live data page, https://staging-console.helium.wtf/.
Need to select AS923_3 freq. So, the data is received OK.
![image](https://user-images.githubusercontent.com/33703122/125110611-fe77fc00-e10e-11eb-8171-d157558a330b.png)

AS923_3 is 923-925Mhz. (Equal TTN AS2)


AS923-925 (“AS2”) 
Used in Brunei, Cambodia, Hong Kong, Indonesia, Laos, Taiwan, Thailand, Vietnam

Uplink:

923.2 - SF7BW125 to SF12BW125
923.4 - SF7BW125 to SF12BW125
923.6 - SF7BW125 to SF12BW125
923.8 - SF7BW125 to SF12BW125
924.0 - SF7BW125 to SF12BW125
924.2 - SF7BW125 to SF12BW125
924.4 - SF7BW125 to SF12BW125
924.6 - SF7BW125 to SF12BW125
924.5 - SF7BW250
924.8 - FSK

**Comment by madninja** [comment]
ok, closing this issue since it was resolved
