### ISSUE TITLE
Data only default DBI

### ISSUE THREAD

**Issue by BFGNeil** [helium/gateway-rs#79]
After adding my data only hotspot I noticed the default DBI is going in as 12dbi for the antenna.

Whilst I know this doesn't really matter, I'd prefer to not be breaking the law on a public blockchain.

Thanks!

**Comment by madninja** [comment]
> After adding my data only hotspot I noticed the default DBI is going in as 12dbi for the antenna.
> 
> Whilst I know this doesn't really matter, I'd prefer to not be breaking the law on a public blockchain.

Where are you seeing this?

**Comment by BFGNeil** [comment]
https://explorer.helium.com/hotspots/14G7Rx9UdENQvovsuBJayZkTNUpk7Rn1WGwxPPw9dqhUwUcVWa7

**Comment by madninja** [comment]
> https://explorer.helium.com/hotspots/14G7Rx9UdENQvovsuBJayZkTNUpk7Rn1WGwxPPw9dqhUwUcVWa7

ah ok.. I believe this is related to this bug: https://github.com/helium/helium-wallet-rs/issues/179 which has a fix pending for it 

Fixed by: https://github.com/helium/helium-wallet-rs/issues/179

**Comment by madninja** [comment]
This is fixed in release: https://github.com/helium/helium-wallet-rs/releases/tag/v1.6.5
