### ISSUE TITLE
Add support for Bobcat light gateway series

### ISSUE THREAD

**Issue by JackeyTY** [helium/gateway-rs#80]
Hi,

We'd also want to add support for Bobcat light gateway series. Target: arm-openwrt-linux-muslgnueabi.

We tried to install klkgw ipk and it failed with;
root@OpenWrt-G220:~# opkg install helium-gateway-v1.0.0-alpha.13-klkgw.ipk 
Unknown package 'helium_gateway'.
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for helium_gateway found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package helium_gateway.
root@OpenWrt-G220:~# 

What's the next step for us to do? Thank you!

**Comment by shawaj** [comment]
@JackeyTY can't test it as don't have the hardware but created a build for your target https://github.com/helium/gateway-rs/pull/84

**Comment by JackeyTY** [comment]
Thanks! Actually I have one question, how to generate keys or how is it provisioned?

**Comment by madninja** [comment]
> Thanks! Actually I have one question, how to generate keys or how is it provisioned?

The code does not yet support a secured key which is why they're dataonly for now. Once the code supports secured keys (ecc608) the keys will be generated/provisioned the same way as on current full hotspots

**Comment by JackeyTY** [comment]
Got it, so should be using gateway-mfr-rs for provisioning keys on light hotspots. Thanks!

**Comment by shawaj** [comment]
@JackeyTY you said your target was `arm-openwrt-linux-muslgnueabi` - what is the actual architecture of your hardware?

https://doc.rust-lang.org/nightly/rustc/platform-support.html

**Comment by shawaj** [comment]
ping @JackeyTY - any update?

**Comment by madninja** [comment]
I'm going to close this due to lack of updates
