### ISSUE TITLE
support for non-numerical listen_addr

### ISSUE THREAD

**Issue by shawaj** [helium/gateway-rs#82]
as we are running on balena, the inter-container networking is done using the container name, so for example we would use a listen address of `packet-forwarder:1680` or similar rather than `127.0.0.1:1680` however when entering this it fails with the error message:

```
 helium-miner  Error: Config(invalid listen address "packet-forwarder:1680": invalid IP address syntax)
```

Is it possible to allow a text based listen address?

i can `ping packet-forwarder` successfully on the device so it resolves correctly, and if manually adding that IP address to the GW_LISTEN_ADDR env variable it works correctly, however that IP changes per device so is not a reliable way to run things.

**Comment by madninja** [comment]
Should be possible yeah

**Comment by shawaj** [comment]
@madninja would be super useful, although for now I have implemented a slightly hacky workaround. although it does work https://github.com/NebraLtd/hm-gatewayrs/blob/shawaj/noenv/start-gatewayrs.sh

**Comment by madninja** [comment]
> @madninja would be super useful, although for now I have implemented a slightly hacky workaround. although it does work nicely https://github.com/NebraLtd/hm-gatewayrs/blob/shawaj/noenv/start-gatewayrs.sh

It'll still get done, but this is exactly the hack I would do too :-)
