### ISSUE TITLE
Gateway-rs will forward join request and device will receive join response however no uplink packets will go through. 

### ISSUE THREAD

**Issue by oharkins** [helium/gateway-rs#86]
Details: Dragino, No Changes to settings using console-vip.helium.com  

[Logs.txt](https://github.com/helium/gateway-rs/files/7033954/Logs.txt)
![Screen Shot 2021-08-23 at 12 04 27 PM](https://user-images.githubusercontent.com/5509758/130495264-a3eac1c6-bf73-4410-bc4b-06f5b3fc002b.png)

**Comment by madninja** [comment]
This should be working fine now. Please report again if you see the problem
