### ISSUE TITLE
WARN ignoring uplink error

### ISSUE THREAD

**Issue by yigitgungor** [helium/gateway-rs#87]
Getting the error below after setting everything up with my Dragino.

Fri Aug 27 20:16:18 2021 daemon.info helium_gateway[15688]:  WARN ignoring uplink error: Service(Rpc(Status { code: Unknown, message: "no response", metadata: MetadataMap { headers: {"user-agent": "grpc-erlang/0.1.0", "content-type": "application/grpc+proto", "grpc-encoding": "identity"} } })), module: router

Version: helium_gateway 1.0.0-alpha.13

**Comment by madninja** [comment]
Yup. That would be it
