### ISSUE TITLE
Any chance of cutting a new Alpha Release?

### ISSUE THREAD

**Issue by dtischler** [helium/gateway-rs#89]
Would be nice to roll in the raspi_64 .deb package that got PR'ed in #73 , as well as other commits since Alpha 13.

We are also working on making a balena container for this, and it would be easier to pull in a Release than build from source in the Dockerfile  :-)

Thanks!

**Comment by madninja** [comment]
Release alpha.14 was just cut: https://github.com/helium/gateway-rs/releases/tag/v1.0.0-alpha.14

**Comment by dtischler** [comment]
Thanks @madninja !  I'll check this out today.  :-)

**Comment by dtischler** [comment]
The newly published raspi_64.deb installed and runs perfectly on 64-bit Raspberry Pi OS, nice.  It does currently suffer from the currently ongoing `uplink error: Service(Rpc(Status { code: Unknown, message: "no response", metadata: MetadataMap { headers: {"user-agent": "grpc-erlang/0.1.0", "content-type": "application/grpc+proto", "grpc-encoding": "identity"} }, source: None })), oui: 2, uri: http://54.176.88.149:8080/, public_key: 1124CJ9yJaHq4D6ugyPCDnSBzQik61C1BqD9VMh1vsUmjwt16HNB, module: router` issue, but, that is separate and appears to be unrelated.  

Simply confirming the 64-bit Arm .deb file installs and loads properly.  😃
