### ISSUE TITLE
no_response / timeout issue

### ISSUE THREAD

**Issue by cokes518** [helium/gateway-rs#91]
Many users running gateway-rs often have to reboot their gateways because they've noticed their devices stop sending.

After tailing logs, it appears the gateway service stops and all uplinks fail. The only fix is to reboot the gateway.

join_request and join_accept works.

**Comment by jthiller** [comment]
Cokes you beat me to the ticket.

Just to add some detail, I am seeing this behavior on an LPS8 running alpha15. Restarting the gateway does not seem to affect my success in getting packets through.

The device I am testing with is configured on production console.

from logs: 
`WARN ignoring uplink error: Service(Rpc(Status { code: Unknown, message: "no response", metadata: MetadataMap { headers: {"user-agent": "grpc-erlang/0.1.0", "content-type": "application/grpc+proto", "grpc-encoding": "identity"} }, source: None })), oui: 2, uri: http://54.176.88.149:8080/, [pubkey redacted] , module: router `

`WARN ignoring uplink error: Service(Rpc(Status { code: Cancelled, message: "Timeout expired", source: None })), oui: 1, uri: http://52.8.80.146:8080/, [pubkey redacted], module: router`

**Comment by carlrakwireless** [comment]
Do we have an update on this issue? I am using a RAK2287 concentrator and seeing the same issue.

**Comment by cokes518** [comment]
this will be resolved once this router PR is merged: https://github.com/helium/router/pull/414

we are hoping to do this today or tomorrow.

**Comment by madninja** [comment]
This was deployed to staging and production routers
